import { createSeedClient } from '@snaplet/seed';

// You can use @snaplet/copycat to generate fake data for a field, for example:
// ```
// await seed.users([{ email: ({ seed }) => copycat.email(seed) }])
// ```
// More on this in our docs: https://docs.snaplet.dev/core-concepts/seed#inside-the-snapletseed-workflow
import { copycat } from '@snaplet/copycat';

// This is a basic example generated by Snaplet to start you off, check out the docs for where to go from here
// * For more on getting started with @snaplet/seed: https://docs.snaplet.dev/getting-started/quick-start/seed
// * For a more detailed reference: https://docs.snaplet.dev/core-concepts/seed

const seed = await createSeedClient({
  dryRun: process.env.DRY !== '0',
});

// Clears all existing data in the database, but keep the structure
await seed.$resetDatabase();

// This will create 3 records in the vendors table
// it reads vendors times(x) 3
await seed.vendors((x) =>
  x(20, (ctx) => ({
    id: ctx.index + 1,
  })),
);
await seed.contracts((x) =>
  x(20, (ctx) => ({
    vendorId: Math.floor(Math.random() * 10) + 1,
  })),
);
await seed.contractDocs((x) => x(1));

// Run it with: DRY=0 npx tsx seed.mts
