import type { ImportTargetField } from './types';

export const COLUMN_ALIASES: Record<string, ImportTargetField> = {
  name: 'full_name',
  'full name': 'full_name',
  'employee name': 'full_name',
  full_name: 'full_name',
  firstname: 'first_name',
  'first name': 'first_name',
  first_name: 'first_name',
  first: 'first_name',
  'given name': 'first_name',
  lastname: 'last_name',
  'last name': 'last_name',
  last_name: 'last_name',
  last: 'last_name',
  surname: 'last_name',
  'family name': 'last_name',
  email: 'email',
  'email address': 'email',
  'e-mail': 'email',
  'user email': 'email',
  'work email': 'email',
  'employee id': 'employee_id',
  employee_id: 'employee_id',
  'unique id': 'employee_id',
  'emp id': 'employee_id',
  emp_id: 'employee_id',
  id: 'employee_id',
  region: 'region',
  country: 'country',
  division: 'division',
  'business group': 'business_group',
  business_group: 'business_group',
  businessgroup: 'business_group',
  'business grp': 'business_group',
  'bus group': 'business_group',
  'business area': 'business_group',
  department: 'department',
  dept: 'department',
  'cost center': 'cost_center',
  cost_center: 'cost_center',
  cc: 'cost_center',
  'business unit': 'business_unit',
  business_unit: 'business_unit',
  entity: 'entity',
  'legal entity': 'entity',
  legal_entity: 'entity',
  'company entity': 'entity',
  team: 'team',
  'start date': 'start_date',
  start_date: 'start_date',
  'hire date': 'start_date',
  hired: 'start_date',
  'leave date': 'leave_date',
  leave_date: 'leave_date',
  'end date': 'leave_date',
  'termination date': 'leave_date',
};
