import { z } from 'zod';

import {
  percentOfIssuedSharesViaConversionSchema,
  percentOfPreferredSharesHeldSchema,
  aggLiqPrefSchema,
  aggregateCostSchema,
  auditedFinancialStatementsSchema,
  balanceSheetSchema,
  capitalizationTableSchema,
  closingDateSchema,
  coInvestorSchema,
  commonStockSchema,
  contractualPricePerShareSchema,
  conversionRatioSchema,
  convertingIntoEquityClassSchema,
  corporateJurisdictionSchema,
  currentPricePerUnitSchema,
  discountSchema,
  effectivePricePerShareSchema,
  entityTypeSchema,
  equityClassSchema,
  equityFinancingNewMoneySchema,
  foundedYearSchema,
  fullyDilutedSharesSchema,
  fundSchema,
  fundsRecentClosingSchema,
  fundingRoundParticipatingSchema,
  highestNewMoneyPricePerShareSchema,
  informationRightsSchema,
  initialClosingSchema,
  investorFieldSchema,
  issueDateSchema,
  latestPostMoneyValuationSchema,
  leadInvestorSchema,
  majorInvestorStatusSchema,
  majorInvestorByThresholdSchema,
  majorInvestorThresholdAmountSchema,
  majorInvestorThresholdPercentSchema,
  majorInvestorThresholdSharesSchema,
  majorInvestorThresholdSideLetterSchema,
  multiplierSchema,
  myAggregateCostSchema,
  mySharesSchema,
  myTotalAggregateCostSchema,
  myWarrantSharesSchema,
  namedMajorInvestorsSchema,
  optionsOutsideOfPoolOutstandingSchema,
  originalIssuePriceSchema,
  outstandingAndReservedOptionsSchema,
  participatingSchema,
  portfolioCompanySchema,
  postMoneyAtEntrySchema,
  postMoneyValuationSchema,
  preMoneyValuationSchema,
  preferenceOrderSchema,
  preferredStockAllClassesSchema,
  pricePerShareSchema,
  proRataRightsAllSchema,
  qsbsCovenantGivenSchema,
  qsbsRepMadeSchema,
  sharesSchema,
  sharesConvertedSchema,
  sharesHeldSchema,
  sharesHeldAsFullyDilutedPercentSchema,
  sharesPurchasedSchema,
  stageSchema,
  stateOfNoticeSchema,
  statementOfIncomeCashFlowsSchema,
  statementOfStockholdersEquitySchema,
  subsequentClosingWindowDaysSchema,
  totalAggregateLiqPrefSchema,
  totalLiquidationPreferenceSchema,
  totalNewMoneySchema,
  totalNewMoneyInvestedSchema,
  totalNewMoneySharesSchema,
  totalSharesSchema,
  valuationCapSchema,
  warrantsOutstandingSchema,
  closingConditionsSchema,
  covenantsAndPostClosingObligationsSchema,
  milestoneClosingsSchema,
  requiredClosingPaymentsSchema,
  issuerPaysInvestorCounselFeesSchema,
  investorCounselFeeCapSchema,
  repAndWarrantyMatrixSchema,
  indemnificationTermsSchema,
  investorRightsSchema,
  mfnClauseSchema,
  coInvestmentRightSchema,
  enhancedInformationRightSchema,
  regulatoryAccommodationsSchema,
  confidentialityObligationsSchema,
  conflictResolutionSchema,
  cashPositionSchema,
  currencySchema,
  eventTypeSchema,
  effectiveDateSchema,
  tsValuationDealSizeSchema,
  tsInstrumentTypeSchema,
  tsLiquidationPreferenceSchema,
  tsAntiDilutionSchema,
  tsInvestorRightsSchema,
  tsFounderTermsSchema,
  commonSharesSchema,
  optionPoolSchema,
  optionPoolReservedSchema,
  preferredStockSchema,
  closingsSchema,
  closingParticipantsSchema,
  boardRepresentativesSchema,
  currentPricePerShareSchema,
  investorPartiesSchema,
  coiAuthorizedShareStructureSchema,
  coiPreferredTermsBySeriesSchema,
  coiLiquidationWaterfallSchema,
  coiProtectiveProvisionsSchema,
  coiAntiDilutionSchema,
  coiRestatedEffectiveDateSchema,
  coiRestatedAmendmentsIncorporatedSchema,
  coiConversionMechanicsSchema,
  coiRedemptionRightsSchema,
  coiDividendsSchema,
  coiPayToPlaySchema,
  iraRegistrationRightsSchema,
  iraGovernanceProvisionsSchema,
  iraDragAlongCoSaleSchema,
  safeTypeIdentificationSchema,
  safeConversionTriggersSchema,
  safeMfnProRataSchema,
  safeInvestmentAmountSchema,
  cpnCoreDebtTermsSchema,
  cpnMaturityTreatmentSchema,
  cpnSecuritySenioritySchema,
  cpnChangeOfControlSchema,
  wtExerciseMechanicsSchema,
  wtExpirationSchema,
  wtAntiDilutionAdjustmentsSchema,
  wtChangeOfControlSchema,
  subInvestorDetailsSchema,
  subSecuritiesPurchasedSchema,
  subAccreditationSchema,
  subClosingMechanicsSchema,
  kissTypeSchema,
  kissEconomicTermsSchema,
  kissConversionTriggersSchema,
  kissMfnProRataSchema,
  pnPrincipalInterestSchema,
  pnMaturityRepaymentSchema,
  pnSecurityCollateralSchema,
  pnEventsOfDefaultSchema,
  pnConversionTermsSchema,
  rofrCoveredSharesSchema,
  rofrExerciseMechanicsSchema,
  rofrTransferExemptionsSchema,
  rofrCoSaleProvisionsSchema,
  rofrTerminationSchema,
  vaPartiesScopeSchema,
  vaBoardCompositionSchema,
  vaDragAlongSchema,
  vaVotingObligationsSchema,
  vaTransferRestrictionsSchema,
  vaTerminationSchema,
  dsStructureSchema,
  dsCapitalizationSchema,
  dsIpSchema,
  dsContractsSchema,
  dsLitigationComplianceSchema,
  dsFinancialEmployeeSchema,
  boObserverIdentitySchema,
  boScopeOfRightsSchema,
  boExclusionsSchema,
  boConfidentialitySchema,
  boTerminationSchema,
  boGovernanceSchema,
  mrlVcocPurposeSchema,
  mrlManagementRightsSchema,
  mrlBoardAccessSchema,
  mrlInformationRightsSchema,
  mrlTransferTerminationSchema,
  maTransactionStructureSchema,
  maDealEconomicsSchema,
  maClosingConditionsSchema,
  maEquityTreatmentSchema,
  maIndemnificationRwSchema,
  maEmployeeMattersSchema,
  lotShareholderIdentitySchema,
  lotSharesSurrenderedSchema,
  lotConsiderationElectionSchema,
  lotWireInstructionsSchema,
  lotRepresentationsSchema,
  spTransactionEconomicsSchema,
  spRofrWaiverSchema,
  spSellerRepresentationsSchema,
  spBuyerRepresentationsSchema,
  spPostClosingSchema,
  soiMetadataSchema,
  soiCostFairValueSchema,
  soiInstrumentDetailsSchema,
  soiValuationMethodologySchema,
  soiFundAggregatesSchema,
  soiExitsSchema,
  scIssuanceDetailsSchema,
  scAuthorizedSignaturesSchema,
  scLegendsSchema,
  scCapTableCrossRefSchema,
  iaDealEconomicsSchema,
  iaWarrantiesDisclosureSchema,
  iaGovernanceProvisionsSchema,
  iaInvestorProtectionsSchema,
  iaWarrantyLimitationsSchema,
  amdOriginalDocumentSchema,
  amdChangedProvisionsSchema,
  amdConsentThresholdSchema,
  amdEconomicImpactSchema,
  amdRelatedAmendmentsSchema,
  jndUnderlyingAgreementSchema,
  jndScopeObligationsSchema,
  jndJoiningCapacitySchema,
  jndTriggerContextSchema,
  jndAuthorizationSchema,
  ctRoundStatusSchema,
  ctShareholdersSchema,
  ctOptionPoolDetailsSchema,
  ctRoundHistorySchema,
  ctWaterfallAnalysisSchema,
  pdMarketSizingSchema,
  pdTractionMetricsSchema,
  pdFundraiseDetailsSchema,
  pdTeamSchema,
  pdFinancialProjectionsSchema,
  ddDataRoomStructureSchema,
  ddFinancialDataSchema,
  ddMaterialContractsSchema,
  ddIpOwnershipSchema,
  ddEmployeeEquitySchema,
  ddLitigationComplianceSchema,
  vdFacilityStructureSchema,
  vdCostOfCapitalSchema,
  vdWarrantCoverageSchema,
  vdFinancialCovenantsSchema,
  vdNegativeCovenantsSchema,
  vdPrepaymentMechanicsSchema,
  lpaFundEconomicsSchema,
  lpaCapitalCallsSchema,
  lpaInvestmentRestrictionsSchema,
  lpaKeyPersonSchema,
  lpaGovernanceSchema,
  lpaDistributionWaterfallSchema,
  spaShareClassSchema,
  spaNumberOfSharesSchema,
  spaRepresentationsAndWarrantiesSchema,
  spaConditionsToClosingSchema,
  spaIndemnificationSurvivalPeriodSchema,
  spaBasketTypeSchema,
  spaIndemnificationCapSchema,
  spaFraudCarveOutSchema,
  spaSurvivalPeriodMonthsFundamentalRepsSchema,
  spaPreClosingCovenantsSchema,
  spaPostClosingCovenantsSchema,
  companyNameSchema,
  fundNameSchema,
  investorExtractionFundDescribeSchema,
  atTransferDetailsSchema,
  sopPlanIdentitySchema,
  sopPoolStructureSchema,
  sopAwardTypesSchema,
  sopExercisePriceSchema,
  sopTerminationExerciseSchema,
  sopChangeOfControlSchema,
  sopAdministrationSchema,
  raTypeAndPartiesSchema,
  raSharesSubjectSchema,
  raRepurchasePriceSchema,
  raTriggerEventsSchema,
  raExerciseOfRightSchema,
  raLapseTerminationSchema,
} from './investorFieldSchemas';

export const glossaryExtractionSchema = (
  investorNames: string[] | null,
  investorFunds: string[] | null,
) =>
  z.object({
    // Universal investor-basics fields
    company_name: companyNameSchema,
    fund_name: fundNameSchema(investorFunds, null),
    investor_extraction_fund_describe: investorExtractionFundDescribeSchema,
    percent_of_issued_shares_via_conversion:
      percentOfIssuedSharesViaConversionSchema,
    percent_of_preferred_shares_held: percentOfPreferredSharesHeldSchema,
    agg_liq_pref: aggLiqPrefSchema,
    aggregate_cost: aggregateCostSchema,
    audited_financial_statements: auditedFinancialStatementsSchema,
    balance_sheet: balanceSheetSchema,
    cash_position: cashPositionSchema,
    capitalization_table: capitalizationTableSchema,
    closing_conditions: closingConditionsSchema,
    closing_date: closingDateSchema,
    co_investor: coInvestorSchema,
    common_stock: commonStockSchema,
    contractual_price_per_share: contractualPricePerShareSchema,
    conversion_ratio: conversionRatioSchema,
    converting_into_equity_class: convertingIntoEquityClassSchema,
    corporate_jurisdiction: corporateJurisdictionSchema,
    covenants_and_post_closing_obligations:
      covenantsAndPostClosingObligationsSchema,
    current_price_per_unit: currentPricePerUnitSchema,
    discount: discountSchema,
    effective_price_per_share: effectivePricePerShareSchema,
    entity_type: entityTypeSchema,
    equity_class: equityClassSchema,
    equity_financing_new_money: equityFinancingNewMoneySchema,
    founded_year: foundedYearSchema,
    fully_diluted_shares: fullyDilutedSharesSchema,
    fund: fundSchema,
    funds_recent_closing: fundsRecentClosingSchema,
    funding_round_participating: fundingRoundParticipatingSchema,
    highest_new_money_price_per_share: highestNewMoneyPricePerShareSchema,
    indemnification_terms: indemnificationTermsSchema,
    information_rights: informationRightsSchema,
    initial_closing: initialClosingSchema,
    investor: investorFieldSchema,
    investor_counsel_fee_cap: investorCounselFeeCapSchema,
    issuer_pays_investor_counsel_fees: issuerPaysInvestorCounselFeesSchema,
    issue_date: issueDateSchema,
    latest_post_money_valuation: latestPostMoneyValuationSchema,
    lead_investor: leadInvestorSchema,
    major_investor_status: majorInvestorStatusSchema,
    major_investor_by_threshold: majorInvestorByThresholdSchema,
    major_investor_threshold_amount: majorInvestorThresholdAmountSchema,
    major_investor_threshold_percent: majorInvestorThresholdPercentSchema,
    major_investor_threshold_shares: majorInvestorThresholdSharesSchema,
    major_investor_threshold_side_letter:
      majorInvestorThresholdSideLetterSchema,
    milestone_closings: milestoneClosingsSchema,
    multiplier: multiplierSchema,
    my_aggregate_cost: myAggregateCostSchema(investorNames, investorFunds),
    my_shares: mySharesSchema(investorNames, investorFunds),
    my_total_aggregate_cost: myTotalAggregateCostSchema(
      investorNames,
      investorFunds,
    ),
    my_warrant_shares: myWarrantSharesSchema(investorNames, investorFunds),
    named_major_investors: namedMajorInvestorsSchema,
    options_outside_of_pool_outstanding: optionsOutsideOfPoolOutstandingSchema,
    original_issue_price: originalIssuePriceSchema,
    outstanding_and_reserved_options: outstandingAndReservedOptionsSchema,
    participating: participatingSchema,
    portfolio_company: portfolioCompanySchema,
    post_money_at_entry: postMoneyAtEntrySchema,
    post_money_valuation: postMoneyValuationSchema,
    pre_money_valuation: preMoneyValuationSchema,
    preference_order: preferenceOrderSchema,
    preferred_stock_all_classes: preferredStockAllClassesSchema,
    price_per_share: pricePerShareSchema,
    pro_rata_rights_all: proRataRightsAllSchema,
    rep_and_warranty_matrix: repAndWarrantyMatrixSchema,
    qsbs_covenant_given: qsbsCovenantGivenSchema,
    qsbs_rep_made: qsbsRepMadeSchema,
    required_closing_payments: requiredClosingPaymentsSchema,
    shares: sharesSchema,
    shares_converted: sharesConvertedSchema,
    shares_held: sharesHeldSchema,
    shares_held_as_fully_diluted_percent: sharesHeldAsFullyDilutedPercentSchema,
    shares_purchased: sharesPurchasedSchema,
    stage: stageSchema,
    state_of_notice: stateOfNoticeSchema,
    statement_of_income_cash_flows: statementOfIncomeCashFlowsSchema,
    statement_of_stockholders_equity: statementOfStockholdersEquitySchema,
    subsequent_closing_window_days: subsequentClosingWindowDaysSchema,
    total_aggregate_liq_pref: totalAggregateLiqPrefSchema,
    total_liquidation_preference: totalLiquidationPreferenceSchema,
    total_new_money: totalNewMoneySchema,
    total_new_money_invested: totalNewMoneyInvestedSchema,
    total_new_money_shares: totalNewMoneySharesSchema,
    total_shares: totalSharesSchema,
    valuation_cap: valuationCapSchema,
    warrants_outstanding: warrantsOutstandingSchema,
    investor_parties: investorPartiesSchema(investorNames, investorFunds),
    investor_rights: investorRightsSchema,
    common_shares: commonSharesSchema,
    option_pool: optionPoolSchema,
    option_pool_reserved: optionPoolReservedSchema,
    preferred_stock: preferredStockSchema,
    event_type: eventTypeSchema,
    effective_date: effectiveDateSchema,
    currency: currencySchema,
    closings: closingsSchema,
    closing_participants: closingParticipantsSchema,
    board_representatives: boardRepresentativesSchema,
    current_price_per_share: currentPricePerShareSchema,
    mfn_clause: mfnClauseSchema,
    co_investment_right: coInvestmentRightSchema,
    enhanced_information_right: enhancedInformationRightSchema,
    regulatory_accommodations: regulatoryAccommodationsSchema,
    confidentiality_obligations: confidentialityObligationsSchema,
    conflict_resolution: conflictResolutionSchema,
    ts_valuation_deal_size: tsValuationDealSizeSchema,
    ts_instrument_type: tsInstrumentTypeSchema,
    ts_liquidation_preference: tsLiquidationPreferenceSchema,
    ts_anti_dilution: tsAntiDilutionSchema,
    ts_investor_rights: tsInvestorRightsSchema,
    ts_founder_terms: tsFounderTermsSchema,
    coi_authorized_share_structure: coiAuthorizedShareStructureSchema,
    coi_preferred_terms_by_series: coiPreferredTermsBySeriesSchema,
    coi_liquidation_waterfall: coiLiquidationWaterfallSchema,
    coi_protective_provisions: coiProtectiveProvisionsSchema,
    coi_anti_dilution: coiAntiDilutionSchema,
    coi_restated_effective_date: coiRestatedEffectiveDateSchema,
    coi_restated_amendments_incorporated:
      coiRestatedAmendmentsIncorporatedSchema,
    coi_conversion_mechanics: coiConversionMechanicsSchema,
    coi_redemption_rights: coiRedemptionRightsSchema,
    coi_dividends: coiDividendsSchema,
    coi_pay_to_play: coiPayToPlaySchema,
    ira_registration_rights: iraRegistrationRightsSchema,
    ira_governance_provisions: iraGovernanceProvisionsSchema,
    ira_drag_along_co_sale: iraDragAlongCoSaleSchema,
    safe_type_identification: safeTypeIdentificationSchema,
    safe_conversion_triggers: safeConversionTriggersSchema,
    safe_mfn_pro_rata: safeMfnProRataSchema,
    safe_investment_amount: safeInvestmentAmountSchema,
    cpn_core_debt_terms: cpnCoreDebtTermsSchema,
    cpn_maturity_treatment: cpnMaturityTreatmentSchema,
    cpn_security_seniority: cpnSecuritySenioritySchema,
    cpn_change_of_control: cpnChangeOfControlSchema,
    wt_exercise_mechanics: wtExerciseMechanicsSchema,
    wt_expiration: wtExpirationSchema,
    wt_anti_dilution_adjustments: wtAntiDilutionAdjustmentsSchema,
    wt_change_of_control: wtChangeOfControlSchema,
    sub_investor_details: subInvestorDetailsSchema,
    sub_securities_purchased: subSecuritiesPurchasedSchema,
    sub_accreditation: subAccreditationSchema,
    sub_closing_mechanics: subClosingMechanicsSchema,
    kiss_type: kissTypeSchema,
    kiss_economic_terms: kissEconomicTermsSchema,
    kiss_conversion_triggers: kissConversionTriggersSchema,
    kiss_mfn_pro_rata: kissMfnProRataSchema,
    pn_principal_interest: pnPrincipalInterestSchema,
    pn_maturity_repayment: pnMaturityRepaymentSchema,
    pn_security_collateral: pnSecurityCollateralSchema,
    pn_events_of_default: pnEventsOfDefaultSchema,
    pn_conversion_terms: pnConversionTermsSchema,
    rofr_covered_shares: rofrCoveredSharesSchema,
    rofr_exercise_mechanics: rofrExerciseMechanicsSchema,
    rofr_transfer_exemptions: rofrTransferExemptionsSchema,
    rofr_co_sale_provisions: rofrCoSaleProvisionsSchema,
    rofr_termination: rofrTerminationSchema,
    va_parties_scope: vaPartiesScopeSchema,
    va_board_composition: vaBoardCompositionSchema,
    va_drag_along: vaDragAlongSchema,
    va_voting_obligations: vaVotingObligationsSchema,
    va_transfer_restrictions: vaTransferRestrictionsSchema,
    va_termination: vaTerminationSchema,
    ds_structure: dsStructureSchema,
    ds_capitalization: dsCapitalizationSchema,
    ds_ip: dsIpSchema,
    ds_contracts: dsContractsSchema,
    ds_litigation_compliance: dsLitigationComplianceSchema,
    ds_financial_employee: dsFinancialEmployeeSchema,
    bo_observer_identity: boObserverIdentitySchema,
    bo_scope_of_rights: boScopeOfRightsSchema,
    bo_exclusions: boExclusionsSchema,
    bo_confidentiality: boConfidentialitySchema,
    bo_termination: boTerminationSchema,
    bo_governance: boGovernanceSchema,
    mrl_vcoc_purpose: mrlVcocPurposeSchema,
    mrl_management_rights: mrlManagementRightsSchema,
    mrl_board_access: mrlBoardAccessSchema,
    mrl_information_rights: mrlInformationRightsSchema,
    mrl_transfer_termination: mrlTransferTerminationSchema,
    ma_transaction_structure: maTransactionStructureSchema,
    ma_deal_economics: maDealEconomicsSchema,
    ma_closing_conditions: maClosingConditionsSchema,
    ma_equity_treatment: maEquityTreatmentSchema,
    ma_indemnification_rw: maIndemnificationRwSchema,
    ma_employee_matters: maEmployeeMattersSchema,
    lot_shareholder_identity: lotShareholderIdentitySchema,
    lot_shares_surrendered: lotSharesSurrenderedSchema,
    lot_consideration_election: lotConsiderationElectionSchema,
    lot_wire_instructions: lotWireInstructionsSchema,
    lot_representations: lotRepresentationsSchema,
    sp_transaction_economics: spTransactionEconomicsSchema,
    sp_rofr_waiver: spRofrWaiverSchema,
    sp_seller_representations: spSellerRepresentationsSchema,
    sp_buyer_representations: spBuyerRepresentationsSchema,
    sp_post_closing: spPostClosingSchema,
    soi_metadata: soiMetadataSchema,
    soi_cost_fair_value: soiCostFairValueSchema,
    soi_instrument_details: soiInstrumentDetailsSchema,
    soi_valuation_methodology: soiValuationMethodologySchema,
    soi_fund_aggregates: soiFundAggregatesSchema,
    soi_exits: soiExitsSchema,
    sc_issuance_details: scIssuanceDetailsSchema,
    sc_authorized_signatures: scAuthorizedSignaturesSchema,
    sc_legends: scLegendsSchema,
    sc_cap_table_cross_ref: scCapTableCrossRefSchema,
    ia_deal_economics: iaDealEconomicsSchema,
    ia_warranties_disclosure: iaWarrantiesDisclosureSchema,
    ia_governance_provisions: iaGovernanceProvisionsSchema,
    ia_investor_protections: iaInvestorProtectionsSchema,
    ia_warranty_limitations: iaWarrantyLimitationsSchema,
    amd_original_document: amdOriginalDocumentSchema,
    amd_changed_provisions: amdChangedProvisionsSchema,
    amd_consent_threshold: amdConsentThresholdSchema,
    amd_economic_impact: amdEconomicImpactSchema,
    amd_related_amendments: amdRelatedAmendmentsSchema,
    jnd_underlying_agreement: jndUnderlyingAgreementSchema,
    jnd_scope_obligations: jndScopeObligationsSchema,
    jnd_joining_capacity: jndJoiningCapacitySchema,
    jnd_trigger_context: jndTriggerContextSchema,
    jnd_authorization: jndAuthorizationSchema,
    ct_round_status: ctRoundStatusSchema,
    ct_shareholders: ctShareholdersSchema,
    ct_option_pool_details: ctOptionPoolDetailsSchema,
    ct_round_history: ctRoundHistorySchema,
    ct_waterfall_analysis: ctWaterfallAnalysisSchema,
    pd_market_sizing: pdMarketSizingSchema,
    pd_traction_metrics: pdTractionMetricsSchema,
    pd_fundraise_details: pdFundraiseDetailsSchema,
    pd_team: pdTeamSchema,
    pd_financial_projections: pdFinancialProjectionsSchema,
    dd_data_room_structure: ddDataRoomStructureSchema,
    dd_financial_data: ddFinancialDataSchema,
    dd_material_contracts: ddMaterialContractsSchema,
    dd_ip_ownership: ddIpOwnershipSchema,
    dd_employee_equity: ddEmployeeEquitySchema,
    dd_litigation_compliance: ddLitigationComplianceSchema,
    vd_facility_structure: vdFacilityStructureSchema,
    vd_cost_of_capital: vdCostOfCapitalSchema,
    vd_warrant_coverage: vdWarrantCoverageSchema,
    vd_financial_covenants: vdFinancialCovenantsSchema,
    vd_negative_covenants: vdNegativeCovenantsSchema,
    vd_prepayment_mechanics: vdPrepaymentMechanicsSchema,
    lpa_fund_economics: lpaFundEconomicsSchema,
    lpa_capital_calls: lpaCapitalCallsSchema,
    lpa_investment_restrictions: lpaInvestmentRestrictionsSchema,
    lpa_key_person: lpaKeyPersonSchema,
    lpa_governance: lpaGovernanceSchema,
    lpa_distribution_waterfall: lpaDistributionWaterfallSchema,
    // SPA master-field-aligned extraction fields
    share_class: spaShareClassSchema,
    number_of_shares: spaNumberOfSharesSchema,
    representations_and_warranties: spaRepresentationsAndWarrantiesSchema,
    conditions_to_closing: spaConditionsToClosingSchema,
    indemnification_survival_period: spaIndemnificationSurvivalPeriodSchema,
    basket_type: spaBasketTypeSchema,
    indemnification_cap: spaIndemnificationCapSchema,
    fraud_carve_out: spaFraudCarveOutSchema,
    survival_period_months_fundamental_reps:
      spaSurvivalPeriodMonthsFundamentalRepsSchema,
    pre_closing_covenants: spaPreClosingCovenantsSchema,
    post_closing_covenants: spaPostClosingCovenantsSchema,
    at_transfer_details: atTransferDetailsSchema,
    sop_plan_identity: sopPlanIdentitySchema,
    sop_pool_structure: sopPoolStructureSchema,
    sop_award_types: sopAwardTypesSchema,
    sop_exercise_price: sopExercisePriceSchema,
    sop_termination_exercise: sopTerminationExerciseSchema,
    sop_change_of_control: sopChangeOfControlSchema,
    sop_administration: sopAdministrationSchema,
    ra_type_and_parties: raTypeAndPartiesSchema,
    ra_shares_subject: raSharesSubjectSchema,
    ra_repurchase_price: raRepurchasePriceSchema,
    ra_trigger_events: raTriggerEventsSchema,
    ra_exercise_of_right: raExerciseOfRightSchema,
    ra_lapse_termination: raLapseTerminationSchema,
  });

const referenceSchema = glossaryExtractionSchema(null, null);
export type GlossaryExtraction = z.infer<typeof referenceSchema>;
