'use server';

import ExcelJS from 'exceljs';
import { format } from 'date-fns';
import logger from '@/utils/pino';
import { auditLogger, getUserAuditContext } from '@/lib/audit';
import { assertCsvExportAllowed } from '@/lib/csv-export/assert-export';
import { formatCurrency } from '@/app/lib/utils';
import { getEffectiveBaseCurrency, getEffectiveDateFormat } from '@/data/users';
import { formatDate } from '@/lib/date-format';
import {
  BusinessSponsorAndGroupData,
  PriceChangeData,
  TopVendorData,
} from '@/lib/v2/reports/monthly-report/transforms';

interface MonthlyReportData {
  overview: {
    currentMonthSpend: {
      amount: number;
      label: string;
    };
    nextMonthSpend: {
      amount: number;
      change: number;
      changePercent: number;
      label: string;
    };
  };
  spendByBusinessGroup: BusinessSponsorAndGroupData[];
  spendByBusinessSponsor: BusinessSponsorAndGroupData[];
  priceChanges: PriceChangeData[];
  upcomingRenewalsContracts: any[];
  topVendorsBySpend: TopVendorData[];
  selectedTag?: string | null;
}

/**
 * Format a number as currency string for Excel. Every figure the report engine
 * produces is converted into the org's base currency before it is grouped, so
 * `currency` is that base — except the renewals sheet, which lists one contract
 * per row and passes each contract's own currency.
 */
function formatCurrencyForExcel(amount: number, currency: string): string {
  return formatCurrency(amount, currency, true) || '0';
}

/**
 * Format percentage for Excel
 */
function formatPercentage(value: number): string {
  if (value === 0) return '0%';
  const absValue = Math.abs(value);
  if (absValue >= 1) return value.toFixed(1) + '%';
  if (absValue >= 0.1) return value.toFixed(2) + '%';
  return value.toFixed(3) + '%';
}

/**
 * Create Overview worksheet
 */
function createOverviewSheet(
  workbook: ExcelJS.Workbook,
  overview: MonthlyReportData['overview'],
  baseCurrency: string,
  selectedTag?: string | null,
  viewMode: 'amortized' | 'actual' = 'amortized',
): void {
  const currentDate = format(new Date(), 'MMMM d, yyyy');
  const worksheet = workbook.addWorksheet('Overview');

  // Add title with optional tag and view mode
  const viewLabel = viewMode === 'actual' ? 'Actual Cost' : 'Amortized';
  const title = selectedTag
    ? `Monthly Budget Report (${viewLabel}) - ${selectedTag}`
    : `Monthly Budget Report (${viewLabel})`;
  const titleRow = worksheet.addRow([title]);
  titleRow.font = { bold: true };

  // Add generated date
  worksheet.addRow(['Generated by PostSig', currentDate]);

  // Empty row
  worksheet.addRow([]);

  // Add headers
  const headerRow = worksheet.addRow([
    `${viewLabel} Spend`,
    'Amount',
    'Change',
  ]);
  headerRow.font = { bold: true };

  // Add data rows
  worksheet.addRow([
    'Current Month',
    formatCurrencyForExcel(overview.currentMonthSpend.amount, baseCurrency),
    '-',
  ]);

  worksheet.addRow([
    'Next Month',
    formatCurrencyForExcel(overview.nextMonthSpend.amount, baseCurrency),
    `${formatCurrencyForExcel(overview.nextMonthSpend.change, baseCurrency)} (${formatPercentage(overview.nextMonthSpend.changePercent)})`,
  ]);

  // Set column widths
  worksheet.columns = [
    { width: 30 }, // Spend column
    { width: 20 }, // Amount
    { width: 25 }, // Change
  ];
}

/**
 * Create Spend by Business Sponsor worksheet
 */
// Every row on these sheets is one contract's slice of a sponsor/group, so it
// exports in that contract's own currency (PSK-1796). The sheets emit no rollup
// rows, so nothing here needs the base currency.
function createSpendByBusinessSponsorSheet(
  workbook: ExcelJS.Workbook,
  spendByBusinessSponsor: BusinessSponsorAndGroupData[],
  viewMode: 'amortized' | 'actual' = 'amortized',
): void {
  const worksheet = workbook.addWorksheet('Spend by Business Sponsor');
  const viewLabel = viewMode === 'actual' ? 'Actual Cost' : 'Amortized';

  // Add headers
  const headerRow = worksheet.addRow([
    'Business Sponsor',
    'Vendor',
    'Product',
    'Split Fee',
    `Current Month (${viewLabel})`,
    `Next Month (${viewLabel})`,
    'Change',
    'Tags',
  ]);
  headerRow.font = { bold: true };

  // Add data rows
  spendByBusinessSponsor.forEach((sponsor) => {
    sponsor.subRows.forEach((subRow) => {
      worksheet.addRow([
        sponsor.name, // Repeat sponsor name on each row for easy filtering
        subRow.vendor,
        subRow.product,
        subRow.isSplit ? 'Yes' : 'No',
        formatCurrencyForExcel(subRow.displayCurrentMonth, subRow.currency),
        formatCurrencyForExcel(subRow.displayNextMonth, subRow.currency),
        formatCurrencyForExcel(subRow.displayChange, subRow.currency),
        subRow.tags.join(', '),
      ]);
    });
  });

  // Set column widths
  worksheet.columns = [
    { width: 25 }, // Business Sponsor
    { width: 25 }, // Vendor
    { width: 30 }, // Product
    { width: 12 }, // Split Fee
    { width: 28 }, // Current Month
    { width: 28 }, // Next Month
    { width: 18 }, // Change
    { width: 25 }, // Tags
  ];
}

/**
 * Create Spend by Business Group worksheet
 */
// Every row on these sheets is one contract's slice of a sponsor/group, so it
// exports in that contract's own currency (PSK-1796). The sheets emit no rollup
// rows, so nothing here needs the base currency.
function createSpendByBusinessGroupSheet(
  workbook: ExcelJS.Workbook,
  spendByBusinessGroup: BusinessSponsorAndGroupData[],
  viewMode: 'amortized' | 'actual' = 'amortized',
): void {
  const worksheet = workbook.addWorksheet('Spend by Business Group');
  const viewLabel = viewMode === 'actual' ? 'Actual Cost' : 'Amortized';

  // Add headers
  const headerRow = worksheet.addRow([
    'Business Group',
    'Vendor',
    'Product',
    'Split Fee',
    `Current Month (${viewLabel})`,
    `Next Month (${viewLabel})`,
    'Change',
    'Tags',
  ]);
  headerRow.font = { bold: true };

  // Add data rows
  spendByBusinessGroup.forEach((group) => {
    group.subRows.forEach((subRow) => {
      worksheet.addRow([
        group.name,
        subRow.vendor,
        subRow.product,
        subRow.isSplit ? 'Yes' : 'No',
        formatCurrencyForExcel(subRow.displayCurrentMonth, subRow.currency),
        formatCurrencyForExcel(subRow.displayNextMonth, subRow.currency),
        formatCurrencyForExcel(subRow.displayChange, subRow.currency),
        subRow.tags.join(', '),
      ]);
    });
  });

  // Set column widths
  worksheet.columns = [
    { width: 25 }, // Business Group
    { width: 25 }, // Vendor
    { width: 30 }, // Product
    { width: 12 }, // Split Fee
    { width: 28 }, // Current Month
    { width: 28 }, // Next Month
    { width: 18 }, // Change
    { width: 25 }, // Tags
  ];
}

/**
 * Create Price Changes worksheet
 */
// Each row is a single contract, so it exports in that contract's own currency
// (PSK-1796) — matching the renewals sheet below and the on-screen table.
function createPriceChangesSheet(
  workbook: ExcelJS.Workbook,
  priceChanges: PriceChangeData[],
): void {
  const worksheet = workbook.addWorksheet('Price Changes');

  // Add headers
  const headerRow = worksheet.addRow([
    'Vendor',
    'Product',
    'Previous Price',
    'New Price',
    'Change Amount',
    'Change %',
    'Reason',
    'Tags',
  ]);
  headerRow.font = { bold: true };

  // Add data rows
  priceChanges.forEach((change) => {
    const changePercent =
      change.previousPrice > 0
        ? ((change.change / change.previousPrice) * 100).toFixed(1) + '%'
        : 'N/A';

    worksheet.addRow([
      change.vendor,
      change.product,
      formatCurrencyForExcel(change.previousPrice, change.currency),
      formatCurrencyForExcel(change.newPrice, change.currency),
      formatCurrencyForExcel(change.change, change.currency),
      changePercent,
      change.reasonForChange,
      change.tags.join(', '),
    ]);
  });

  // Set column widths
  worksheet.columns = [
    { width: 25 }, // Vendor
    { width: 30 }, // Product
    { width: 18 }, // Previous Price
    { width: 18 }, // New Price
    { width: 18 }, // Change Amount
    { width: 12 }, // Change %
    { width: 35 }, // Reason
    { width: 25 }, // Tags
  ];
}

/**
 * Create Upcoming Renewals worksheet
 */
function createUpcomingRenewalsSheet(
  workbook: ExcelJS.Workbook,
  upcomingRenewalsContracts: any[],
  dateFormat: string,
): void {
  const worksheet = workbook.addWorksheet('Upcoming Renewals');

  // Add headers
  const headerRow = worksheet.addRow([
    'Vendor',
    'Product',
    'End Date',
    'Cancel By',
    'Current Annual',
    'Projected Annual',
    'Tags',
  ]);
  headerRow.font = { bold: true };

  // Add data rows
  upcomingRenewalsContracts.forEach((contract) => {
    // Extract vendor name
    const vendorName = contract.vendor || '';

    // Extract product names
    const products = contract.currentYearProducts || contract.product;
    let productNames = '';
    if (Array.isArray(products) && products.length > 0) {
      productNames = products
        .map((p: any) => p.vendor_products?.name || p)
        .filter(Boolean)
        .join(', ');
    } else if (typeof products === 'string') {
      productNames = products;
    }

    // Extract tags
    const tags = contract.tags?.map((tag: any) => tag.name).join(', ') || '';

    // Extract dates
    const endDateRaw = Array.isArray(contract.termEndDate)
      ? contract.termEndDate[0]?.date || ''
      : contract.termEndDate || '';
    const endDate = endDateRaw ? formatDate(endDateRaw, dateFormat, '') : '';
    const cancelByDate = contract.cancelByDate
      ? formatDate(contract.cancelByDate, dateFormat, '')
      : '';

    // Extract annual fees. One contract per row, so these stay in the
    // contract's own currency.
    const contractCurrency = contract.currency || 'USD';
    const currentAnnual = contract.currentBudget || 0;
    const projectedAnnual = contract.projectedBudget || currentAnnual;

    worksheet.addRow([
      vendorName,
      productNames,
      endDate,
      cancelByDate,
      formatCurrencyForExcel(currentAnnual, contractCurrency),
      formatCurrencyForExcel(projectedAnnual, contractCurrency),
      tags,
    ]);
  });

  // Set column widths
  worksheet.columns = [
    { width: 25 }, // Vendor
    { width: 30 }, // Product
    { width: 12 }, // End Date
    { width: 15 }, // Cancel By
    { width: 18 }, // Current Annual
    { width: 18 }, // Projected Annual
    { width: 25 }, // Tags
  ];
}

/**
 * Create Top Vendors worksheet
 */
function createTopVendorsSheet(
  workbook: ExcelJS.Workbook,
  topVendors: TopVendorData[],
  baseCurrency: string,
): void {
  const worksheet = workbook.addWorksheet('Top 10 Vendors');

  // Add headers
  const headerRow = worksheet.addRow(['Vendor', 'Monthly Spend']);
  headerRow.font = { bold: true };

  // Add data rows
  topVendors.forEach((vendor) => {
    worksheet.addRow([
      vendor.name,
      formatCurrencyForExcel(vendor.spend, baseCurrency),
    ]);
  });

  // Set column widths
  worksheet.columns = [
    { width: 30 }, // Vendor
    { width: 18 }, // Monthly Spend
  ];
}

/**
 * Export monthly report data to Excel
 * Returns a number array that can be converted to a Blob on the client
 */
export async function exportMonthlyReportExcel(
  monthlyReportData: MonthlyReportData,
  selectedTag?: string | null,
  viewMode: 'amortized' | 'actual' = 'amortized',
): Promise<number[]> {
  await assertCsvExportAllowed('cpm');
  const dateFormat = await getEffectiveDateFormat();
  const baseCurrency = await getEffectiveBaseCurrency();
  try {
    // Create a new workbook
    const workbook = new ExcelJS.Workbook();

    // Create all worksheets
    createOverviewSheet(
      workbook,
      monthlyReportData.overview,
      baseCurrency,
      selectedTag,
      viewMode,
    );
    createSpendByBusinessGroupSheet(
      workbook,
      monthlyReportData.spendByBusinessGroup,
      viewMode,
    );
    createSpendByBusinessSponsorSheet(
      workbook,
      monthlyReportData.spendByBusinessSponsor,
      viewMode,
    );
    createPriceChangesSheet(workbook, monthlyReportData.priceChanges);
    createUpcomingRenewalsSheet(
      workbook,
      monthlyReportData.upcomingRenewalsContracts,
      dateFormat,
    );
    createTopVendorsSheet(
      workbook,
      monthlyReportData.topVendorsBySpend,
      baseCurrency,
    );

    const rawBuffer = await workbook.xlsx.writeBuffer();

    const bytes =
      rawBuffer instanceof Uint8Array
        ? rawBuffer
        : new Uint8Array(rawBuffer as ArrayBuffer);

    await auditLogger.logExportEvent(
      'monthly-report-xlsx',
      await getUserAuditContext(),
      {
        format: 'xlsx',
        // The spend sheets write one row per subRow, not per group — count
        // what lands in the workbook.
        rowCount:
          (monthlyReportData.spendByBusinessGroup ?? []).reduce(
            (n, group) => n + (group.subRows?.length ?? 0),
            0,
          ) +
          (monthlyReportData.spendByBusinessSponsor ?? []).reduce(
            (n, sponsor) => n + (sponsor.subRows?.length ?? 0),
            0,
          ) +
          (monthlyReportData.priceChanges?.length ?? 0) +
          (monthlyReportData.upcomingRenewalsContracts?.length ?? 0) +
          (monthlyReportData.topVendorsBySpend?.length ?? 0),
        viewMode,
        selectedTag: selectedTag ?? undefined,
        filename: 'monthly-report.xlsx',
      },
    );

    return Array.from(bytes);
  } catch (error) {
    logger.error({ error }, 'Failed to generate monthly report Excel');
    throw new Error('Failed to generate monthly report Excel');
  }
}
