export {
  isAllocationMode,
  type AllocationContext,
  type AllocationEmployee,
  type AllocationLineRow,
  type AllocationMode,
  type AllocationProduct,
  type AllocationRow,
  type AllocationTargetRef,
  type ContractSeat,
  type ResolvedContractAllocation,
  type ResolvedLine,
  type ResolvedScope,
  type RolledUpLine,
} from './types';
export {
  buildAllocationContext,
  loadAllocationContext,
  loadAllocationContextForContract,
  loadAllocationContextForRequest,
  type AllocationContextInput,
  type AllocationEmployeeInput,
} from './context';
export {
  isFullyUnallocated,
  resolveAllocations,
  rollupToLevel,
} from './resolver';
export {
  PERCENT_SUM_TOLERANCE,
  normalizeScopes,
  saveContractAllocation,
  type AllocationLineInput,
  type AllocationScopeInput,
  type SaveContractAllocationParams,
} from './service';
export {
  PICKER_CATEGORY_LABELS,
  TARGET_TYPE_LABELS,
  buildPickerCatalog,
  targetKey,
  targetTypeLabel,
  type PickerCatalogInput,
  type PickerCategory,
  type PickerCategoryKey,
  type PickerEmployee,
  type PickerItem,
} from './picker';
export {
  ACTIVE_USERS_MODE_LABEL,
  allocationProvenance,
  amountToPercent,
  applicableScopes,
  applyEqualSplit,
  balanceMessage,
  canSaveScopes,
  clampPercent,
  editorScopeFromResolved,
  equalSplitPercents,
  needsScopeChoice,
  activeUsersPreview,
  seatHolderTargets,
  seatsForScope,
  percentToAmount,
  provenanceLabel,
  scopeValueFor,
  roundPercent,
  scopeTotals,
  toSaveScopes,
  unlinkedSeatsNote,
  type AllocationProvenance,
  type EditorLine,
  type EditorScope,
  type ScopeSeat,
  type ScopeTotals,
  type SplitMethod,
} from './editor';
export {
  EMPTY_SCOPE_VALUES,
  getContractScopeValues,
  hasRecordedFee,
  inheritScopeValues,
  scopeValuesFromEngineSpend,
  scopeValuesOf,
  type ContractScopeValues,
  type RecordedProductFee,
  type ScopeValues,
} from './amounts';
export {
  loadCostAllocationTabData,
  type AllocationSeat,
  type CostAllocationTabData,
} from './tab-data';
export { attachAllocationActivityNames } from './activity-names';
// The flag stays out of this barrel on purpose: flag.ts reaches the flag
// store through a service client, and callers import it directly.
export {
  DEFAULT_INVOICE_REPORT_PERIOD,
  DEFAULT_ROLLUP_REPORT_PERIOD,
  ENGINE_WINDOW_BOUNDS,
  REPORT_PERIODS,
  REPORT_PERIOD_LABELS,
  REPORT_PERIOD_PHRASES,
  isInReportWindow,
  isReportPeriod,
  resolveInvoiceWindow,
  resolveReportWindow,
  resolveRollupWindow,
  type PresetReportPeriod,
  type ReportPeriod,
  type ReportWindow,
  type ReportWindowParams,
  type ResolvedReportWindow,
} from './report-window';
export {
  filterInvoiceReportRows,
  invoiceReportTargetOptions,
  invoiceReportTargetTotals,
  invoiceReportTotalAmount,
  invoiceReportVendorOptions,
  sortInvoiceReportRows,
  type InvoiceReportData,
  type InvoiceReportFilters,
  type InvoiceReportRow,
  type InvoiceReportSortKey,
  type InvoiceReportTarget,
  type InvoiceReportContractRef,
  type InvoiceReportOption,
  type InvoiceReportTargetTotal,
  type SortDirection,
} from './invoice-report-rows';
export {
  buildInvoiceReportRows,
  invoiceBillingDate,
  loadInvoiceCostAllocationReport,
  type InvoiceReportSource,
} from './invoice-report';
export {
  orgUnitPath,
  parentPath,
  sharedNameBreadcrumbs,
  targetPath,
} from './target-path';
export {
  assertBudgetTargetInOrg,
  budgetTargetKey,
  budgetsByTargetKey,
  fiscalYearsTouched,
  loadBudgets,
  saveBudget,
  type BudgetRow,
  type BudgetTarget,
  type SaveBudgetParams,
} from './budgets';
export {
  OUTSIDE_HIERARCHY_LABEL,
  ROLLUP_VIEW_LABELS,
  UNASSIGNED_LABEL,
  buildAllocationRollup,
  flattenRollupView,
  isFlatRollup,
  type AllocationRollupData,
  type AllocationRollupRows,
  type RollupBuildInput,
  type RollupDisplayRow,
  type RollupRow,
  type RollupTarget,
  type RollupView,
  type RollupViewKey,
  type UnallocatedContractRow,
} from './rollup-report-rows';
export { loadAllocationRollupReport } from './rollup-report';
export {
  selectUnallocatedContracts,
  summarizeUnallocated,
  unallocatedContractRows,
  type UnallocatedContractSource,
  type UnallocatedSummary,
} from './unallocated';
