create table "public"."contract_statuses" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name" text,
  "description" text
);

alter table
  "public"."contract_statuses" enable row level security;

create table "public"."contract_types" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "name" character varying,
  "description" text
);

alter table
  "public"."contract_types" enable row level security;

alter table
  "public"."contracts"
add
  column "type_id" bigint;

CREATE UNIQUE INDEX contract_statuses_pkey ON public.contract_statuses USING btree (id);

CREATE UNIQUE INDEX contract_types_pkey ON public.contract_types USING btree (id);

alter table
  "public"."contract_statuses"
add
  constraint "contract_statuses_pkey" PRIMARY KEY using index "contract_statuses_pkey";

alter table
  "public"."contract_types"
add
  constraint "contract_types_pkey" PRIMARY KEY using index "contract_types_pkey";

alter table
  "public"."contracts"
add
  constraint "contracts_type_id_fkey" FOREIGN KEY (type_id) REFERENCES contract_types(id) ON UPDATE CASCADE not valid;

alter table
  "public"."contracts" validate constraint "contracts_type_id_fkey";

alter table
  "public"."contracts"
add
  constraint "contracts_status_id_fkey" FOREIGN KEY (status_id) REFERENCES contract_statuses(id) ON UPDATE CASCADE not valid;

alter table
  "public"."contracts" validate constraint "contracts_status_id_fkey";

grant delete on table "public"."contract_statuses" to "anon";

grant
insert
  on table "public"."contract_statuses" to "anon";

grant references on table "public"."contract_statuses" to "anon";

grant
select
  on table "public"."contract_statuses" to "anon";

grant trigger on table "public"."contract_statuses" to "anon";

grant truncate on table "public"."contract_statuses" to "anon";

grant
update
  on table "public"."contract_statuses" to "anon";

grant delete on table "public"."contract_statuses" to "authenticated";

grant
insert
  on table "public"."contract_statuses" to "authenticated";

grant references on table "public"."contract_statuses" to "authenticated";

grant
select
  on table "public"."contract_statuses" to "authenticated";

grant trigger on table "public"."contract_statuses" to "authenticated";

grant truncate on table "public"."contract_statuses" to "authenticated";

grant
update
  on table "public"."contract_statuses" to "authenticated";

grant delete on table "public"."contract_statuses" to "service_role";

grant
insert
  on table "public"."contract_statuses" to "service_role";

grant references on table "public"."contract_statuses" to "service_role";

grant
select
  on table "public"."contract_statuses" to "service_role";

grant trigger on table "public"."contract_statuses" to "service_role";

grant truncate on table "public"."contract_statuses" to "service_role";

grant
update
  on table "public"."contract_statuses" to "service_role";

grant delete on table "public"."contract_types" to "anon";

grant
insert
  on table "public"."contract_types" to "anon";

grant references on table "public"."contract_types" to "anon";

grant
select
  on table "public"."contract_types" to "anon";

grant trigger on table "public"."contract_types" to "anon";

grant truncate on table "public"."contract_types" to "anon";

grant
update
  on table "public"."contract_types" to "anon";

grant delete on table "public"."contract_types" to "authenticated";

grant
insert
  on table "public"."contract_types" to "authenticated";

grant references on table "public"."contract_types" to "authenticated";

grant
select
  on table "public"."contract_types" to "authenticated";

grant trigger on table "public"."contract_types" to "authenticated";

grant truncate on table "public"."contract_types" to "authenticated";

grant
update
  on table "public"."contract_types" to "authenticated";

grant delete on table "public"."contract_types" to "service_role";

grant
insert
  on table "public"."contract_types" to "service_role";

grant references on table "public"."contract_types" to "service_role";

grant
select
  on table "public"."contract_types" to "service_role";

grant trigger on table "public"."contract_types" to "service_role";

grant truncate on table "public"."contract_types" to "service_role";

grant
update
  on table "public"."contract_types" to "service_role";