create table "public"."contract_docs" (
    "id" integer generated by default as identity not null,
    "contract_id" integer,
    "type" character varying,
    "file_path" character varying,
    "description" text,
    "updated_at" timestamp without time zone,
    "created_at" timestamp without time zone
);

create table "public"."contracts" (
    "id" integer generated by default as identity not null,
    "vendor_id" integer,
    "term_start_date" date,
    "term_end_date" date,
    "cancel_by_date" integer,
    "auto_renewal" boolean,
    "subscription_term" character varying,
    "billing_frequency" character varying,
    "payment_terms" text,
    "exclusivity_terms" character varying,
    "multi_year" boolean,
    "annual_increase" integer,
    "owner" character varying,
    "currency" character varying,
    "other_attributes" jsonb,
    "products_fees" jsonb,
    "user_id" uuid
);

alter table
    "public"."contracts" enable row level security;

create table "public"."vendors" (
    "id" integer generated by default as identity not null,
    "name" character varying,
    "address" text,
    "email" character varying,
    "phone" integer,
    "created_at" timestamp without time zone
);

CREATE UNIQUE INDEX contract_docs_pkey ON public.contract_docs USING btree (id);

CREATE UNIQUE INDEX contracts_pkey ON public.contracts USING btree (id);

CREATE UNIQUE INDEX vendors_pkey ON public.vendors USING btree (id);

alter table
    "public"."contract_docs"
add
    constraint "contract_docs_pkey" PRIMARY KEY using index "contract_docs_pkey";

alter table
    "public"."contracts"
add
    constraint "contracts_pkey" PRIMARY KEY using index "contracts_pkey";

alter table
    "public"."vendors"
add
    constraint "vendors_pkey" PRIMARY KEY using index "vendors_pkey";

alter table
    "public"."contract_docs"
add
    constraint "contract_docs_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table
    "public"."contract_docs" validate constraint "contract_docs_contract_id_fkey";

alter table
    "public"."contracts"
add
    constraint "contracts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE not valid;

alter table
    "public"."contracts" validate constraint "contracts_user_id_fkey";

alter table
    "public"."contracts"
add
    constraint "contracts_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON UPDATE CASCADE not valid;

alter table
    "public"."contracts" validate constraint "contracts_vendor_id_fkey";

grant delete on table "public"."contract_docs" to "anon";

grant
insert
    on table "public"."contract_docs" to "anon";

grant references on table "public"."contract_docs" to "anon";

grant
select
    on table "public"."contract_docs" to "anon";

grant trigger on table "public"."contract_docs" to "anon";

grant truncate on table "public"."contract_docs" to "anon";

grant
update
    on table "public"."contract_docs" to "anon";

grant delete on table "public"."contract_docs" to "authenticated";

grant
insert
    on table "public"."contract_docs" to "authenticated";

grant references on table "public"."contract_docs" to "authenticated";

grant
select
    on table "public"."contract_docs" to "authenticated";

grant trigger on table "public"."contract_docs" to "authenticated";

grant truncate on table "public"."contract_docs" to "authenticated";

grant
update
    on table "public"."contract_docs" to "authenticated";

grant delete on table "public"."contract_docs" to "service_role";

grant
insert
    on table "public"."contract_docs" to "service_role";

grant references on table "public"."contract_docs" to "service_role";

grant
select
    on table "public"."contract_docs" to "service_role";

grant trigger on table "public"."contract_docs" to "service_role";

grant truncate on table "public"."contract_docs" to "service_role";

grant
update
    on table "public"."contract_docs" to "service_role";

grant delete on table "public"."contracts" to "anon";

grant
insert
    on table "public"."contracts" to "anon";

grant references on table "public"."contracts" to "anon";

grant
select
    on table "public"."contracts" to "anon";

grant trigger on table "public"."contracts" to "anon";

grant truncate on table "public"."contracts" to "anon";

grant
update
    on table "public"."contracts" to "anon";

grant delete on table "public"."contracts" to "authenticated";

grant
insert
    on table "public"."contracts" to "authenticated";

grant references on table "public"."contracts" to "authenticated";

grant
select
    on table "public"."contracts" to "authenticated";

grant trigger on table "public"."contracts" to "authenticated";

grant truncate on table "public"."contracts" to "authenticated";

grant
update
    on table "public"."contracts" to "authenticated";

grant delete on table "public"."contracts" to "service_role";

grant
insert
    on table "public"."contracts" to "service_role";

grant references on table "public"."contracts" to "service_role";

grant
select
    on table "public"."contracts" to "service_role";

grant trigger on table "public"."contracts" to "service_role";

grant truncate on table "public"."contracts" to "service_role";

grant
update
    on table "public"."contracts" to "service_role";

grant delete on table "public"."vendors" to "anon";

grant
insert
    on table "public"."vendors" to "anon";

grant references on table "public"."vendors" to "anon";

grant
select
    on table "public"."vendors" to "anon";

grant trigger on table "public"."vendors" to "anon";

grant truncate on table "public"."vendors" to "anon";

grant
update
    on table "public"."vendors" to "anon";

grant delete on table "public"."vendors" to "authenticated";

grant
insert
    on table "public"."vendors" to "authenticated";

grant references on table "public"."vendors" to "authenticated";

grant
select
    on table "public"."vendors" to "authenticated";

grant trigger on table "public"."vendors" to "authenticated";

grant truncate on table "public"."vendors" to "authenticated";

grant
update
    on table "public"."vendors" to "authenticated";

grant delete on table "public"."vendors" to "service_role";

grant
insert
    on table "public"."vendors" to "service_role";

grant references on table "public"."vendors" to "service_role";

grant
select
    on table "public"."vendors" to "service_role";

grant trigger on table "public"."vendors" to "service_role";

grant truncate on table "public"."vendors" to "service_role";

grant
update
    on table "public"."vendors" to "service_role";
