alter type "public"."app_permission" rename to "app_permission__old_version_to_be_dropped";

create type "public"."app_permission" as enum ('contracts.select', 'contracts.update', 'contracts.delete', 'contracts.insert', 'vendor_products.select', 'vendor_products.update', 'vendor_products.delete', 'vendor_products.insert', 'vendor_products_details.select', 'vendor_products_details.update', 'vendor_products_details.delete', 'vendor_products_details.insert', 'contract_docs.select','contract_docs.insert','contract_docs.update', 'activities.select', 'activities.insert', 'activities.update', 'contract_statuses.select', 'contract_types.select');

ALTER TABLE public.role_permissions ADD COLUMN new_permission app_permission;
UPDATE public.role_permissions SET new_permission = permission::text::app_permission;
ALTER TABLE public.role_permissions DROP COLUMN permission;
ALTER TABLE public.role_permissions RENAME COLUMN new_permission TO permission;

drop type "public"."app_permission__old_version_to_be_dropped" cascade;

create table "public"."vendor_products" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now(),
    "vendor_id" integer,
    "user_id" uuid
);


alter table "public"."vendor_products" enable row level security;

create table "public"."vendor_products_details" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "contract_id" integer,
    "year" integer,
    "fees" bigint,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid
);


alter table "public"."vendor_products_details" enable row level security;

alter table "public"."role_permissions" alter column permission type "public"."app_permission" using permission::text::"public"."app_permission";

alter table "public"."contracts" add column "related_contract_id" integer;

CREATE UNIQUE INDEX unique_name ON public.vendor_products USING btree (name);

CREATE UNIQUE INDEX vendor_product_details_pkey ON public.vendor_products_details USING btree (id);

CREATE UNIQUE INDEX vendor_products_pkey ON public.vendor_products USING btree (id);

alter table "public"."vendor_products" add constraint "vendor_products_pkey" PRIMARY KEY using index "vendor_products_pkey";

alter table "public"."vendor_products_details" add constraint "vendor_product_details_pkey" PRIMARY KEY using index "vendor_product_details_pkey";

alter table "public"."vendor_products" add constraint "unique_name" UNIQUE using index "unique_name";

alter table "public"."vendor_products" add constraint "vendor_products_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vendor_products" validate constraint "vendor_products_user_id_fkey";

alter table "public"."vendor_products" add constraint "vendor_products_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vendor_products" validate constraint "vendor_products_vendor_id_fkey";

alter table "public"."vendor_products_details" add constraint "vendor_products_details_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vendor_products_details" validate constraint "vendor_products_details_contract_id_fkey";

alter table "public"."vendor_products_details" add constraint "vendor_products_details_product_id_fkey" FOREIGN KEY (product_id) REFERENCES vendor_products(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vendor_products_details" validate constraint "vendor_products_details_product_id_fkey";

alter table "public"."vendor_products_details" add constraint "vendor_products_details_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."vendor_products_details" validate constraint "vendor_products_details_user_id_fkey";

grant delete on table "public"."vendor_products" to "anon";

grant insert on table "public"."vendor_products" to "anon";

grant references on table "public"."vendor_products" to "anon";

grant select on table "public"."vendor_products" to "anon";

grant trigger on table "public"."vendor_products" to "anon";

grant truncate on table "public"."vendor_products" to "anon";

grant update on table "public"."vendor_products" to "anon";

grant delete on table "public"."vendor_products" to "authenticated";

grant insert on table "public"."vendor_products" to "authenticated";

grant references on table "public"."vendor_products" to "authenticated";

grant select on table "public"."vendor_products" to "authenticated";

grant trigger on table "public"."vendor_products" to "authenticated";

grant truncate on table "public"."vendor_products" to "authenticated";

grant update on table "public"."vendor_products" to "authenticated";

grant delete on table "public"."vendor_products" to "service_role";

grant insert on table "public"."vendor_products" to "service_role";

grant references on table "public"."vendor_products" to "service_role";

grant select on table "public"."vendor_products" to "service_role";

grant trigger on table "public"."vendor_products" to "service_role";

grant truncate on table "public"."vendor_products" to "service_role";

grant update on table "public"."vendor_products" to "service_role";

grant delete on table "public"."vendor_products_details" to "anon";

grant insert on table "public"."vendor_products_details" to "anon";

grant references on table "public"."vendor_products_details" to "anon";

grant select on table "public"."vendor_products_details" to "anon";

grant trigger on table "public"."vendor_products_details" to "anon";

grant truncate on table "public"."vendor_products_details" to "anon";

grant update on table "public"."vendor_products_details" to "anon";

grant delete on table "public"."vendor_products_details" to "authenticated";

grant insert on table "public"."vendor_products_details" to "authenticated";

grant references on table "public"."vendor_products_details" to "authenticated";

grant select on table "public"."vendor_products_details" to "authenticated";

grant trigger on table "public"."vendor_products_details" to "authenticated";

grant truncate on table "public"."vendor_products_details" to "authenticated";

grant update on table "public"."vendor_products_details" to "authenticated";

grant delete on table "public"."vendor_products_details" to "service_role";

grant insert on table "public"."vendor_products_details" to "service_role";

grant references on table "public"."vendor_products_details" to "service_role";

grant select on table "public"."vendor_products_details" to "service_role";

grant trigger on table "public"."vendor_products_details" to "service_role";

grant truncate on table "public"."vendor_products_details" to "service_role";

grant update on table "public"."vendor_products_details" to "service_role";

CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  bind_permissions int;
begin
  select count(*)
  from public.role_permissions
  where role_permissions.permission = authorize.requested_permission
    and (role_permissions.role = (select (auth.jwt() ->> 'user_role')::public.app_role))
  into bind_permissions;

  return bind_permissions > 0;
end;
$function$
;

create policy "Allow authorized insert access"
on "public"."contracts"
as permissive
for insert
to public
with check (authorize('contracts.insert'::app_permission));


create policy "Allow authorized delete access"
on "public"."vendor_products"
as permissive
for delete
to public
using (authorize('vendor_products.delete'::app_permission));


create policy "Allow authorized insert access"
on "public"."vendor_products"
as permissive
for insert
to public
with check (authorize('vendor_products.insert'::app_permission));


create policy "Allow authorized select access"
on "public"."vendor_products"
as permissive
for select
to public
using (authorize('vendor_products.select'::app_permission));


create policy "Allow authorized update access"
on "public"."vendor_products"
as permissive
for update
to public
using (authorize('vendor_products.update'::app_permission));


create policy "Allow authorized delete access"
on "public"."vendor_products_details"
as permissive
for delete
to public
using (authorize('vendor_products_details.delete'::app_permission));


create policy "Allow authorized insert access"
on "public"."vendor_products_details"
as permissive
for insert
to public
with check (authorize('vendor_products_details.insert'::app_permission));


create policy "Allow authorized select access"
on "public"."vendor_products_details"
as permissive
for select
to public
using (authorize('vendor_products_details.select'::app_permission));


create policy "Allow authorized update access"
on "public"."vendor_products_details"
as permissive
for update
to public
using (authorize('vendor_products_details.update'::app_permission));
