create table "public"."contract_status" (
  "id" bigint generated by default as identity not null,
  "name" character varying not null,
  "description" character varying
);

alter table
  "public"."contract_status" enable row level security;

alter table
  "public"."contracts"
add
  column "status_id" bigint;

alter table
  "public"."users"
add
  column "accepted_terms" boolean default false;

alter table
  "public"."users"
add
  column "show_ftux" boolean not null default true;

set
  check_function_bodies = off;

  CREATE OR REPLACE FUNCTION public.update_auth_user_ftux() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
  BEGIN
    UPDATE auth.users
    SET raw_user_meta_data = jsonb_set(
      coalesce(raw_user_meta_data, '{}'::jsonb),
      '{show_ftux}',
      to_jsonb(NEW.show_ftux),
      true
    )
    WHERE id = NEW.id;

    RETURN NEW;
  END;
  $$;

  CREATE OR REPLACE FUNCTION public.update_auth_user_terms() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
  BEGIN
    UPDATE auth.users
    SET raw_user_meta_data = jsonb_set(
      coalesce(raw_user_meta_data, '{}'::jsonb),
      '{accepted_terms}',
      to_jsonb(NEW.accepted_terms),
      true
    )
    WHERE id = NEW.id;

    RETURN NEW;
  END;
  $$;

  CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
  BEGIN
    INSERT INTO public.users (id, name, email, job_title, organization, department)
    VALUES (
      new.id,
      new.raw_user_meta_data ->> 'name',
      NEW.email,
      NEW.raw_user_meta_data ->> 'job_title',
      NEW.raw_user_meta_data ->> 'organization',
      NEW.raw_user_meta_data ->> 'department'
    );

    UPDATE auth.users
    SET raw_user_meta_data = jsonb_set(
      coalesce(raw_user_meta_data, '{}'::jsonb),
      '{show_ftux}',
      'true'::jsonb,
      true
    )
    WHERE id = NEW.id;

    UPDATE auth.users
    SET raw_user_meta_data = jsonb_set(
      coalesce(raw_user_meta_data, '{}'::jsonb),
      '{accepted_terms}',
      'false'::jsonb,
      true
    )
    WHERE id = NEW.id;

    RETURN NEW;
  END;
  $$;

grant delete on table "public"."contract_status" to "anon";

grant
insert
  on table "public"."contract_status" to "anon";

grant references on table "public"."contract_status" to "anon";

grant
select
  on table "public"."contract_status" to "anon";

grant trigger on table "public"."contract_status" to "anon";

grant truncate on table "public"."contract_status" to "anon";

grant
update
  on table "public"."contract_status" to "anon";

grant delete on table "public"."contract_status" to "authenticated";

grant
insert
  on table "public"."contract_status" to "authenticated";

grant references on table "public"."contract_status" to "authenticated";

grant
select
  on table "public"."contract_status" to "authenticated";

grant trigger on table "public"."contract_status" to "authenticated";

grant truncate on table "public"."contract_status" to "authenticated";

grant
update
  on table "public"."contract_status" to "authenticated";

grant delete on table "public"."contract_status" to "service_role";

grant
insert
  on table "public"."contract_status" to "service_role";

grant references on table "public"."contract_status" to "service_role";

grant
select
  on table "public"."contract_status" to "service_role";

grant trigger on table "public"."contract_status" to "service_role";

grant truncate on table "public"."contract_status" to "service_role";

grant
update
  on table "public"."contract_status" to "service_role";

CREATE TRIGGER update_auth_user_ftux
AFTER
UPDATE
  OF show_ftux ON public.users FOR EACH ROW EXECUTE FUNCTION update_auth_user_ftux();

CREATE TRIGGER update_auth_user_terms
AFTER
UPDATE
  OF accepted_terms ON public.users FOR EACH ROW EXECUTE FUNCTION update_auth_user_terms();
