create table "public"."sub_asset_classes" (
    "id" bigint generated by default as identity not null,
    "parent_id" bigint,
    "name" text
);


alter table "public"."sub_asset_classes" enable row level security;

CREATE UNIQUE INDEX sub_asset_classes_pkey ON public.sub_asset_classes USING btree (id);

alter table "public"."sub_asset_classes" add constraint "sub_asset_classes_pkey" PRIMARY KEY using index "sub_asset_classes_pkey";

alter table "public"."sub_asset_classes" add constraint "sub_asset_classes_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES asset_classes(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."sub_asset_classes" validate constraint "sub_asset_classes_parent_id_fkey";

grant delete on table "public"."sub_asset_classes" to "anon";

grant insert on table "public"."sub_asset_classes" to "anon";

grant references on table "public"."sub_asset_classes" to "anon";

grant select on table "public"."sub_asset_classes" to "anon";

grant trigger on table "public"."sub_asset_classes" to "anon";

grant truncate on table "public"."sub_asset_classes" to "anon";

grant update on table "public"."sub_asset_classes" to "anon";

grant delete on table "public"."sub_asset_classes" to "authenticated";

grant insert on table "public"."sub_asset_classes" to "authenticated";

grant references on table "public"."sub_asset_classes" to "authenticated";

grant select on table "public"."sub_asset_classes" to "authenticated";

grant trigger on table "public"."sub_asset_classes" to "authenticated";

grant truncate on table "public"."sub_asset_classes" to "authenticated";

grant update on table "public"."sub_asset_classes" to "authenticated";

grant delete on table "public"."sub_asset_classes" to "service_role";

grant insert on table "public"."sub_asset_classes" to "service_role";

grant references on table "public"."sub_asset_classes" to "service_role";

grant select on table "public"."sub_asset_classes" to "service_role";

grant trigger on table "public"."sub_asset_classes" to "service_role";

grant truncate on table "public"."sub_asset_classes" to "service_role";

grant update on table "public"."sub_asset_classes" to "service_role";
