create table "public"."asset_classes" (
    "id" bigint generated by default as identity primary key,
    "name" text
);


alter table "public"."asset_classes" enable row level security;

create table "public"."contract_asset_classes" (
    "contract_id" integer not null,
    "asset_class_id" integer not null
);

alter table "public"."contract_asset_classes" enable row level security;


CREATE UNIQUE INDEX contract_asset_classes_pkey ON public.contract_asset_classes USING btree (contract_id, asset_class_id);

alter table "public"."contract_asset_classes" add constraint "contract_asset_classes_pkey" PRIMARY KEY using index "contract_asset_classes_pkey";

alter table "public"."contract_asset_classes" add constraint "contract_asset_classes_asset_class_id_fkey" FOREIGN KEY (asset_class_id) REFERENCES asset_classes(id) not valid;

alter table "public"."contract_asset_classes" validate constraint "contract_asset_classes_asset_class_id_fkey";

alter table "public"."contract_asset_classes" add constraint "contract_asset_classes_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) not valid;

alter table "public"."contract_asset_classes" validate constraint "contract_asset_classes_contract_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.contract_search(contracts)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
  search_document text;
BEGIN
  SELECT
    coalesce($1.summary, '') || ' ' ||
    coalesce((
      SELECT string_agg(v.name || ' ' || v.description, ' ')
      FROM vendors v
      WHERE v.id = $1.vendor_id
    ), '') || ' ' ||
    coalesce((
      SELECT string_agg(vp.name, ' ')
      FROM vendor_products_details vpd
      JOIN vendor_products vp ON vpd.product_id = vp.id
      WHERE vpd.contract_id = $1.id
    ), '') || ' ' ||
    coalesce((
      SELECT string_agg(ac.name, ' ')
      FROM contract_asset_classes cac
      JOIN asset_classes ac ON ac.id = cac.asset_class_id
      WHERE cac.contract_id = $1.id
    ), '') || ' ' ||
    coalesce((
      SELECT ct.name
      FROM contract_types ct
      WHERE ct.id = $1.type_id
    ), '')
  INTO search_document;

  RETURN search_document;
END;
$function$
;

grant select on table public.asset_classes to authenticated;

grant all on table public.asset_classes to service_role;

grant select on table public.contract_asset_classes to authenticated;

grant insert, update on table public.asset_classes to authenticated;

grant all on table public.contract_asset_classes to service_role;
