create table "public"."contract_addendums" (
    "id" integer generated by default as identity not null,
    "vendor_id" integer,
    "term_start_date" date,
    "term_end_date" date,
    "cancel_by_date" integer,
    "auto_renewal" boolean,
    "subscription_term" character varying,
    "billing_frequency" character varying,
    "payment_terms" text,
    "exclusivity_terms" character varying,
    "multi_year" boolean,
    "annual_increase" integer,
    "owner" character varying,
    "currency" character varying,
    "other_attributes" jsonb,
    "products_fees" jsonb,
    "user_id" uuid,
    "updated_at" timestamp with time zone,
    "cancellation_process" text,
    "distribution_rights" character varying,
    "execution_date" date,
    "geo_restrictions" character varying,
    "marketing_rights" character varying,
    "permissions" text,
    "renewal_period" text,
    "scope_of_use" text,
    "suspension_of_service" text,
    "cancel_date" date,
    "business_group" text,
    "business_justification" text,
    "business_sponsor" text,
    "name" text,
    "business_order" text,
    "contract_id" integer
);


alter table "public"."contract_addendums" enable row level security;

create table "public"."contract_orphans" (
    "id" integer generated by default as identity not null,
    "vendor_id" integer,
    "term_start_date" date,
    "term_end_date" date,
    "cancel_by_date" integer,
    "auto_renewal" boolean,
    "subscription_term" character varying,
    "billing_frequency" character varying,
    "payment_terms" text,
    "exclusivity_terms" character varying,
    "multi_year" boolean,
    "annual_increase" integer,
    "owner" character varying,
    "currency" character varying,
    "other_attributes" jsonb,
    "products_fees" jsonb,
    "user_id" uuid,
    "updated_at" timestamp with time zone,
    "cancellation_process" text,
    "distribution_rights" character varying,
    "execution_date" date,
    "geo_restrictions" character varying,
    "marketing_rights" character varying,
    "permissions" text,
    "renewal_period" text,
    "scope_of_use" text,
    "suspension_of_service" text,
    "cancel_date" date,
    "business_group" text,
    "business_justification" text,
    "business_sponsor" text,
    "name" text,
    "business_order" text
);


alter table "public"."contract_orphans" enable row level security;

CREATE UNIQUE INDEX contract_addendums_pkey ON public.contract_addendums USING btree (id);

CREATE UNIQUE INDEX contract_orphans_pkey ON public.contract_orphans USING btree (id);

alter table "public"."contract_addendums" add constraint "contract_addendums_pkey" PRIMARY KEY using index "contract_addendums_pkey";

alter table "public"."contract_orphans" add constraint "contract_orphans_pkey" PRIMARY KEY using index "contract_orphans_pkey";

alter table "public"."contract_addendums" add constraint "contract_addendums_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."contract_addendums" validate constraint "contract_addendums_contract_id_fkey";

grant delete on table "public"."contract_addendums" to "anon";

grant insert on table "public"."contract_addendums" to "anon";

grant references on table "public"."contract_addendums" to "anon";

grant select on table "public"."contract_addendums" to "anon";

grant trigger on table "public"."contract_addendums" to "anon";

grant truncate on table "public"."contract_addendums" to "anon";

grant update on table "public"."contract_addendums" to "anon";

grant delete on table "public"."contract_addendums" to "authenticated";

grant insert on table "public"."contract_addendums" to "authenticated";

grant references on table "public"."contract_addendums" to "authenticated";

grant select on table "public"."contract_addendums" to "authenticated";

grant trigger on table "public"."contract_addendums" to "authenticated";

grant truncate on table "public"."contract_addendums" to "authenticated";

grant update on table "public"."contract_addendums" to "authenticated";

grant delete on table "public"."contract_addendums" to "service_role";

grant insert on table "public"."contract_addendums" to "service_role";

grant references on table "public"."contract_addendums" to "service_role";

grant select on table "public"."contract_addendums" to "service_role";

grant trigger on table "public"."contract_addendums" to "service_role";

grant truncate on table "public"."contract_addendums" to "service_role";

grant update on table "public"."contract_addendums" to "service_role";

grant delete on table "public"."contract_orphans" to "anon";

grant insert on table "public"."contract_orphans" to "anon";

grant references on table "public"."contract_orphans" to "anon";

grant select on table "public"."contract_orphans" to "anon";

grant trigger on table "public"."contract_orphans" to "anon";

grant truncate on table "public"."contract_orphans" to "anon";

grant update on table "public"."contract_orphans" to "anon";

grant delete on table "public"."contract_orphans" to "authenticated";

grant insert on table "public"."contract_orphans" to "authenticated";

grant references on table "public"."contract_orphans" to "authenticated";

grant select on table "public"."contract_orphans" to "authenticated";

grant trigger on table "public"."contract_orphans" to "authenticated";

grant truncate on table "public"."contract_orphans" to "authenticated";

grant update on table "public"."contract_orphans" to "authenticated";

grant delete on table "public"."contract_orphans" to "service_role";

grant insert on table "public"."contract_orphans" to "service_role";

grant references on table "public"."contract_orphans" to "service_role";

grant select on table "public"."contract_orphans" to "service_role";

grant trigger on table "public"."contract_orphans" to "service_role";

grant truncate on table "public"."contract_orphans" to "service_role";

grant update on table "public"."contract_orphans" to "service_role";

create policy "Enable select for users based on user_id"
on "public"."contract_addendums"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Enable update for extractors based on email"
on "public"."contract_addendums"
as permissive
for update
to public
using ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)))
with check ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)));


create policy "Enable users to update their own contracts"
on "public"."contract_addendums"
as permissive
for update
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Give full access to extractors"
on "public"."contract_addendums"
as permissive
for select
to authenticated
using ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)));


create policy "Users can insert into contracts"
on "public"."contract_addendums"
as permissive
for insert
to authenticated
with check (true);


create policy "Users can view their own contracts"
on "public"."contract_addendums"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Enable select for users based on user_id"
on "public"."contract_orphans"
as permissive
for select
to public
using ((auth.uid() = user_id));


create policy "Enable update for extractors based on email"
on "public"."contract_orphans"
as permissive
for update
to public
using ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)))
with check ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)));


create policy "Enable users to update their own contracts"
on "public"."contract_orphans"
as permissive
for update
to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


create policy "Give full access to extractors"
on "public"."contract_orphans"
as permissive
for select
to authenticated
using ((((auth.jwt() ->> 'email'::text) = 'ext_1@postsig.com'::text) OR ((auth.jwt() ->> 'email'::text) = 'extraction@postsig.com'::text)));


create policy "Users can insert into contracts"
on "public"."contract_orphans"
as permissive
for insert
to authenticated
with check (true);


create policy "Users can view their own contracts"
on "public"."contract_orphans"
as permissive
for select
to public
using ((auth.uid() = user_id));



