create table "public"."contract_comments" (
    "id" bigint generated by default as identity not null,
    "contract_id" bigint not null,
    "user_id" uuid not null,
    "parent_comment_id" bigint,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "is_deleted" boolean not null default false,
    "content" jsonb
);


alter table "public"."contract_comments" enable row level security;

CREATE UNIQUE INDEX contract_comments_pkey ON public.contract_comments USING btree (id);

CREATE INDEX idx_contract_comments_contract_id ON public.contract_comments USING btree (contract_id);

CREATE INDEX idx_contract_comments_created_at ON public.contract_comments USING btree (created_at DESC);

CREATE INDEX idx_contract_comments_parent_id ON public.contract_comments USING btree (parent_comment_id) WHERE (parent_comment_id IS NOT NULL);

CREATE INDEX idx_contract_comments_user_id ON public.contract_comments USING btree (user_id);

alter table "public"."contract_comments" add constraint "contract_comments_pkey" PRIMARY KEY using index "contract_comments_pkey";

alter table "public"."contract_comments" add constraint "contract_comments_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE not valid;

alter table "public"."contract_comments" validate constraint "contract_comments_contract_id_fkey";

alter table "public"."contract_comments" add constraint "contract_comments_parent_comment_id_fkey" FOREIGN KEY (parent_comment_id) REFERENCES contract_comments(id) ON DELETE CASCADE not valid;

alter table "public"."contract_comments" validate constraint "contract_comments_parent_comment_id_fkey";

alter table "public"."contract_comments" add constraint "contract_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."contract_comments" validate constraint "contract_comments_user_id_fkey";

alter table "public"."contract_comments" add constraint "contract_comments_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."contract_comments" validate constraint "contract_comments_user_id_fkey1";

alter table "public"."contract_comments" add constraint "valid_content_structure" CHECK (((jsonb_typeof(content) = 'object'::text) AND (content ? 'type'::text) AND ((content ->> 'type'::text) = 'doc'::text) AND (content ? 'content'::text))) not valid;

alter table "public"."contract_comments" validate constraint "valid_content_structure";

grant delete on table "public"."contract_comments" to "authenticated";

grant insert on table "public"."contract_comments" to "authenticated";

grant references on table "public"."contract_comments" to "authenticated";

grant select on table "public"."contract_comments" to "authenticated";

grant trigger on table "public"."contract_comments" to "authenticated";

grant truncate on table "public"."contract_comments" to "authenticated";

grant update on table "public"."contract_comments" to "authenticated";

grant delete on table "public"."contract_comments" to "service_role";

grant insert on table "public"."contract_comments" to "service_role";

grant references on table "public"."contract_comments" to "service_role";

grant select on table "public"."contract_comments" to "service_role";

grant trigger on table "public"."contract_comments" to "service_role";

grant truncate on table "public"."contract_comments" to "service_role";

grant update on table "public"."contract_comments" to "service_role";

create policy "Delete own comments"
on "public"."contract_comments"
as permissive
for delete
to authenticated
using ((user_id = auth.uid()));


create policy "Enable insert for authenticated users only"
on "public"."contract_comments"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."contract_comments"
as permissive
for select
to authenticated
using (true);


create policy "Update own comments"
on "public"."contract_comments"
as permissive
for update
to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));
