create table "public"."client_entities" (
    "id" integer generated by default as identity not null,
    "name" text,
    "address" text,
    "organization_id" uuid not null,
    "created_at" timestamp without time zone default now(),
    "updated_at" timestamp without time zone default now()
);


alter table "public"."client_entities" enable row level security;

alter table "public"."contracts" add column "client_entity_id" integer;

CREATE INDEX client_entities_organization_id_idx ON public.client_entities USING btree (organization_id);

CREATE UNIQUE INDEX client_entities_pkey ON public.client_entities USING btree (id);

alter table "public"."client_entities" add constraint "client_entities_pkey" PRIMARY KEY using index "client_entities_pkey";

alter table "public"."client_entities" add constraint "client_entities_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."client_entities" validate constraint "client_entities_organization_id_fkey";

alter table "public"."contracts" add constraint "contracts_client_entity_id_fkey" FOREIGN KEY (client_entity_id) REFERENCES client_entities(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."contracts" validate constraint "contracts_client_entity_id_fkey";

create policy "Enable all for authenticated users"
on "public"."client_entities"
as permissive
for all
to authenticated
using (true)
with check (true);

CREATE OR REPLACE FUNCTION public.update_client_entities_updated_at()
 RETURNS trigger
 AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trigger_update_client_entities_updated_at BEFORE UPDATE ON public.client_entities FOR EACH ROW EXECUTE FUNCTION update_client_entities_updated_at();
