create type "public"."prompt_candidate_status" as enum ('pending', 'drafting', 'refining', 'evaluating', 'finalized', 'archived');

create table "public"."contract_definitions" (
    "id" uuid not null default gen_random_uuid(),
    "type_key" text not null,
    "display_name" text not null,
    "description" text,
    "is_active" boolean not null default true,
    "ui_layout_config" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."contract_type_fields" (
    "id" uuid not null default gen_random_uuid(),
    "contract_definition_id" uuid not null,
    "master_field_id" uuid not null,
    "prompt_template_group_id" uuid,
    "label_override" text,
    "is_required_for_extraction" boolean not null default false,
    "is_required_for_completion" boolean not null default false,
    "prompt_template_version_override" uuid,
    "display_order" integer default 0,
    "is_active_for_this_type" boolean not null default true,
    "ui_component_hint_override" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."extraction_audit" (
    "id" uuid not null default gen_random_uuid(),
    "contract_id" integer,
    "field_key" text not null,
    "prompt_template_id" uuid,
    "extraction_result" jsonb,
    "confidence_score" numeric(5,4),
    "extracted_at" timestamp with time zone not null default now(),
    "extraction_status" text,
    "notes" text,
    "user_id" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."finalized_prompts" (
    "id" uuid not null default gen_random_uuid(),
    "prompt_version_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "prompt_text" text not null,
    "evaluation_summary" jsonb not null,
    "labels" text[] not null default '{}'::text[],
    "metadata" jsonb,
    "usage_count" integer default 0
);

alter table "public"."finalized_prompts" enable row level security;

create table "public"."master_field_definitions" (
    "id" uuid not null default gen_random_uuid(),
    "field_key" text not null,
    "default_label" text not null,
    "default_data_type" text not null,
    "default_select_options" jsonb,
    "default_ui_component_hint" text,
    "default_validation_rules" jsonb,
    "default_tooltip_text" text,
    "category" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."prompt_candidates" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "candidate_data" jsonb not null,
    "status" prompt_candidate_status not null default 'pending'::prompt_candidate_status,
    "source" text
);

alter table "public"."prompt_candidates" enable row level security;

create table "public"."prompt_evaluations" (
    "id" uuid not null default gen_random_uuid(),
    "prompt_version_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "sample_document_id" text not null,
    "evaluation_metrics" jsonb not null,
    "evaluation_passed" boolean,
    "notes" text
);

alter table "public"."prompt_evaluations" enable row level security;

create table "public"."prompt_template_groups" (
    "id" uuid not null default gen_random_uuid(),
    "group_key" text not null,
    "description" text,
    "active_version_id" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

alter table "public"."prompt_template_groups" enable row level security;

create table "public"."prompt_templates" (
    "id" uuid not null default gen_random_uuid(),
    "prompt_key" text not null,
    "prompt_group_id" uuid not null,
    "template_content" text not null,
    "version" integer generated by default as identity not null,
    "llm_parameters" jsonb,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

create table "public"."prompt_versions" (
    "id" uuid not null default gen_random_uuid(),
    "prompt_candidate_id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "version_number" integer not null,
    "prompt_text" text not null,
    "llm_feedback" jsonb,
    "refinement_details" jsonb,
    "is_draft" boolean not null default true,
    "is_finalized_for_evaluation" boolean not null default false,
    "parent_version_id" uuid
);

alter table "public"."prompt_versions" enable row level security;

CREATE UNIQUE INDEX contract_definitions_pkey ON public.contract_definitions USING btree (id);

CREATE UNIQUE INDEX contract_definitions_type_key_key ON public.contract_definitions USING btree (type_key);

CREATE UNIQUE INDEX contract_type_fields_contract_definition_id_master_field_id_key ON public.contract_type_fields USING btree (contract_definition_id, master_field_id);

CREATE UNIQUE INDEX contract_type_fields_pkey ON public.contract_type_fields USING btree (id);

CREATE UNIQUE INDEX extraction_audit_pkey ON public.extraction_audit USING btree (id);

CREATE UNIQUE INDEX finalized_prompts_pkey ON public.finalized_prompts USING btree (id);

CREATE UNIQUE INDEX finalized_prompts_prompt_version_id_key ON public.finalized_prompts USING btree (prompt_version_id);

CREATE UNIQUE INDEX master_field_definitions_field_key_key ON public.master_field_definitions USING btree (field_key);

CREATE UNIQUE INDEX master_field_definitions_pkey ON public.master_field_definitions USING btree (id);

CREATE UNIQUE INDEX prompt_candidates_pkey ON public.prompt_candidates USING btree (id);

CREATE UNIQUE INDEX prompt_evaluations_pkey ON public.prompt_evaluations USING btree (id);

CREATE UNIQUE INDEX prompt_template_groups_group_key_key ON public.prompt_template_groups USING btree (group_key);

CREATE UNIQUE INDEX prompt_template_groups_pkey ON public.prompt_template_groups USING btree (id);

CREATE UNIQUE INDEX prompt_templates_pkey ON public.prompt_templates USING btree (id);

CREATE UNIQUE INDEX prompt_templates_prompt_group_id_version_key ON public.prompt_templates USING btree (prompt_group_id, version);

CREATE UNIQUE INDEX prompt_versions_pkey ON public.prompt_versions USING btree (id);

CREATE UNIQUE INDEX uq_candidate_version ON public.prompt_versions USING btree (prompt_candidate_id, version_number);

alter table "public"."contract_definitions" add constraint "contract_definitions_pkey" PRIMARY KEY using index "contract_definitions_pkey";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_pkey" PRIMARY KEY using index "contract_type_fields_pkey";

alter table "public"."extraction_audit" add constraint "extraction_audit_pkey" PRIMARY KEY using index "extraction_audit_pkey";

alter table "public"."finalized_prompts" add constraint "finalized_prompts_pkey" PRIMARY KEY using index "finalized_prompts_pkey";

alter table "public"."master_field_definitions" add constraint "master_field_definitions_pkey" PRIMARY KEY using index "master_field_definitions_pkey";

alter table "public"."prompt_candidates" add constraint "prompt_candidates_pkey" PRIMARY KEY using index "prompt_candidates_pkey";

alter table "public"."prompt_evaluations" add constraint "prompt_evaluations_pkey" PRIMARY KEY using index "prompt_evaluations_pkey";

alter table "public"."prompt_template_groups" add constraint "prompt_template_groups_pkey" PRIMARY KEY using index "prompt_template_groups_pkey";

alter table "public"."prompt_templates" add constraint "prompt_templates_pkey" PRIMARY KEY using index "prompt_templates_pkey";

alter table "public"."prompt_versions" add constraint "prompt_versions_pkey" PRIMARY KEY using index "prompt_versions_pkey";

alter table "public"."contract_definitions" add constraint "contract_definitions_type_key_key" UNIQUE using index "contract_definitions_type_key_key";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_contract_definition_id_fkey" FOREIGN KEY (contract_definition_id) REFERENCES contract_definitions(id) ON DELETE CASCADE not valid;

alter table "public"."contract_type_fields" validate constraint "contract_type_fields_contract_definition_id_fkey";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_contract_definition_id_master_field_id_key" UNIQUE using index "contract_type_fields_contract_definition_id_master_field_id_key";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_master_field_id_fkey" FOREIGN KEY (master_field_id) REFERENCES master_field_definitions(id) ON DELETE RESTRICT not valid;

alter table "public"."contract_type_fields" validate constraint "contract_type_fields_master_field_id_fkey";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_prompt_template_group_id_fkey" FOREIGN KEY (prompt_template_group_id) REFERENCES prompt_template_groups(id) ON DELETE SET NULL not valid;

alter table "public"."contract_type_fields" validate constraint "contract_type_fields_prompt_template_group_id_fkey";

alter table "public"."contract_type_fields" add constraint "contract_type_fields_prompt_template_version_override_fkey" FOREIGN KEY (prompt_template_version_override) REFERENCES prompt_templates(id) ON DELETE SET NULL not valid;

alter table "public"."contract_type_fields" validate constraint "contract_type_fields_prompt_template_version_override_fkey";

alter table "public"."extraction_audit" add constraint "extraction_audit_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE not valid;

alter table "public"."extraction_audit" validate constraint "extraction_audit_contract_id_fkey";

alter table "public"."extraction_audit" add constraint "extraction_audit_prompt_template_id_fkey" FOREIGN KEY (prompt_template_id) REFERENCES prompt_templates(id) ON DELETE SET NULL not valid;

alter table "public"."extraction_audit" validate constraint "extraction_audit_prompt_template_id_fkey";

alter table "public"."extraction_audit" add constraint "extraction_audit_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL not valid;

alter table "public"."extraction_audit" validate constraint "extraction_audit_user_id_fkey";

alter table "public"."finalized_prompts" add constraint "finalized_prompts_prompt_version_id_fkey" FOREIGN KEY (prompt_version_id) REFERENCES prompt_versions(id) ON DELETE RESTRICT not valid;

alter table "public"."finalized_prompts" validate constraint "finalized_prompts_prompt_version_id_fkey";

alter table "public"."finalized_prompts" add constraint "finalized_prompts_prompt_version_id_key" UNIQUE using index "finalized_prompts_prompt_version_id_key";

alter table "public"."master_field_definitions" add constraint "master_field_definitions_field_key_key" UNIQUE using index "master_field_definitions_field_key_key";

alter table "public"."prompt_evaluations" add constraint "prompt_evaluations_prompt_version_id_fkey" FOREIGN KEY (prompt_version_id) REFERENCES prompt_versions(id) ON DELETE CASCADE not valid;

alter table "public"."prompt_evaluations" validate constraint "prompt_evaluations_prompt_version_id_fkey";

alter table "public"."prompt_template_groups" add constraint "fk_active_version" FOREIGN KEY (active_version_id) REFERENCES prompt_templates(id) ON DELETE SET NULL not valid;

alter table "public"."prompt_template_groups" validate constraint "fk_active_version";

alter table "public"."prompt_template_groups" add constraint "prompt_template_groups_group_key_key" UNIQUE using index "prompt_template_groups_group_key_key";

alter table "public"."prompt_templates" add constraint "prompt_templates_prompt_group_id_fkey" FOREIGN KEY (prompt_group_id) REFERENCES prompt_template_groups(id) ON DELETE CASCADE not valid;

alter table "public"."prompt_templates" validate constraint "prompt_templates_prompt_group_id_fkey";

alter table "public"."prompt_templates" add constraint "prompt_templates_prompt_group_id_version_key" UNIQUE using index "prompt_templates_prompt_group_id_version_key";

alter table "public"."prompt_versions" add constraint "prompt_versions_parent_version_id_fkey" FOREIGN KEY (parent_version_id) REFERENCES prompt_versions(id) ON DELETE SET NULL not valid;

alter table "public"."prompt_versions" validate constraint "prompt_versions_parent_version_id_fkey";

alter table "public"."prompt_versions" add constraint "prompt_versions_prompt_candidate_id_fkey" FOREIGN KEY (prompt_candidate_id) REFERENCES prompt_candidates(id) ON DELETE CASCADE not valid;

alter table "public"."prompt_versions" validate constraint "prompt_versions_prompt_candidate_id_fkey";

alter table "public"."prompt_versions" add constraint "uq_candidate_version" UNIQUE using index "uq_candidate_version";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.trigger_set_timestamp()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
        BEGIN
          NEW.updated_at = NOW();
          RETURN NEW;
        END;
        $function$
;


grant delete on table "public"."contract_definitions" to "anon";

grant insert on table "public"."contract_definitions" to "anon";

grant references on table "public"."contract_definitions" to "anon";

grant select on table "public"."contract_definitions" to "anon";

grant trigger on table "public"."contract_definitions" to "anon";

grant truncate on table "public"."contract_definitions" to "anon";

grant update on table "public"."contract_definitions" to "anon";

grant delete on table "public"."contract_definitions" to "authenticated";

grant insert on table "public"."contract_definitions" to "authenticated";

grant references on table "public"."contract_definitions" to "authenticated";

grant select on table "public"."contract_definitions" to "authenticated";

grant trigger on table "public"."contract_definitions" to "authenticated";

grant truncate on table "public"."contract_definitions" to "authenticated";

grant update on table "public"."contract_definitions" to "authenticated";

grant delete on table "public"."contract_definitions" to "service_role";

grant insert on table "public"."contract_definitions" to "service_role";

grant references on table "public"."contract_definitions" to "service_role";

grant select on table "public"."contract_definitions" to "service_role";

grant trigger on table "public"."contract_definitions" to "service_role";

grant truncate on table "public"."contract_definitions" to "service_role";

grant update on table "public"."contract_definitions" to "service_role";

grant delete on table "public"."contract_type_fields" to "anon";

grant insert on table "public"."contract_type_fields" to "anon";

grant references on table "public"."contract_type_fields" to "anon";

grant select on table "public"."contract_type_fields" to "anon";

grant trigger on table "public"."contract_type_fields" to "anon";

grant truncate on table "public"."contract_type_fields" to "anon";

grant update on table "public"."contract_type_fields" to "anon";

grant delete on table "public"."contract_type_fields" to "authenticated";

grant insert on table "public"."contract_type_fields" to "authenticated";

grant references on table "public"."contract_type_fields" to "authenticated";

grant select on table "public"."contract_type_fields" to "authenticated";

grant trigger on table "public"."contract_type_fields" to "authenticated";

grant truncate on table "public"."contract_type_fields" to "authenticated";

grant update on table "public"."contract_type_fields" to "authenticated";

grant delete on table "public"."contract_type_fields" to "service_role";

grant insert on table "public"."contract_type_fields" to "service_role";

grant references on table "public"."contract_type_fields" to "service_role";

grant select on table "public"."contract_type_fields" to "service_role";

grant trigger on table "public"."contract_type_fields" to "service_role";

grant truncate on table "public"."contract_type_fields" to "service_role";

grant update on table "public"."contract_type_fields" to "service_role";

grant delete on table "public"."extraction_audit" to "anon";

grant insert on table "public"."extraction_audit" to "anon";

grant references on table "public"."extraction_audit" to "anon";

grant select on table "public"."extraction_audit" to "anon";

grant trigger on table "public"."extraction_audit" to "anon";

grant truncate on table "public"."extraction_audit" to "anon";

grant update on table "public"."extraction_audit" to "anon";

grant delete on table "public"."extraction_audit" to "authenticated";

grant insert on table "public"."extraction_audit" to "authenticated";

grant references on table "public"."extraction_audit" to "authenticated";

grant select on table "public"."extraction_audit" to "authenticated";

grant trigger on table "public"."extraction_audit" to "authenticated";

grant truncate on table "public"."extraction_audit" to "authenticated";

grant update on table "public"."extraction_audit" to "authenticated";

grant delete on table "public"."extraction_audit" to "service_role";

grant insert on table "public"."extraction_audit" to "service_role";

grant references on table "public"."extraction_audit" to "service_role";

grant select on table "public"."extraction_audit" to "service_role";

grant trigger on table "public"."extraction_audit" to "service_role";

grant truncate on table "public"."extraction_audit" to "service_role";

grant update on table "public"."extraction_audit" to "service_role";

grant delete on table "public"."finalized_prompts" to "anon";

grant insert on table "public"."finalized_prompts" to "anon";

grant references on table "public"."finalized_prompts" to "anon";

grant select on table "public"."finalized_prompts" to "anon";

grant trigger on table "public"."finalized_prompts" to "anon";

grant truncate on table "public"."finalized_prompts" to "anon";

grant update on table "public"."finalized_prompts" to "anon";

grant delete on table "public"."finalized_prompts" to "authenticated";

grant insert on table "public"."finalized_prompts" to "authenticated";

grant references on table "public"."finalized_prompts" to "authenticated";

grant select on table "public"."finalized_prompts" to "authenticated";

grant trigger on table "public"."finalized_prompts" to "authenticated";

grant truncate on table "public"."finalized_prompts" to "authenticated";

grant update on table "public"."finalized_prompts" to "authenticated";

grant delete on table "public"."finalized_prompts" to "service_role";

grant insert on table "public"."finalized_prompts" to "service_role";

grant references on table "public"."finalized_prompts" to "service_role";

grant select on table "public"."finalized_prompts" to "service_role";

grant trigger on table "public"."finalized_prompts" to "service_role";

grant truncate on table "public"."finalized_prompts" to "service_role";

grant update on table "public"."finalized_prompts" to "service_role";

grant delete on table "public"."master_field_definitions" to "anon";

grant insert on table "public"."master_field_definitions" to "anon";

grant references on table "public"."master_field_definitions" to "anon";

grant select on table "public"."master_field_definitions" to "anon";

grant trigger on table "public"."master_field_definitions" to "anon";

grant truncate on table "public"."master_field_definitions" to "anon";

grant update on table "public"."master_field_definitions" to "anon";

grant delete on table "public"."master_field_definitions" to "authenticated";

grant insert on table "public"."master_field_definitions" to "authenticated";

grant references on table "public"."master_field_definitions" to "authenticated";

grant select on table "public"."master_field_definitions" to "authenticated";

grant trigger on table "public"."master_field_definitions" to "authenticated";

grant truncate on table "public"."master_field_definitions" to "authenticated";

grant update on table "public"."master_field_definitions" to "authenticated";

grant delete on table "public"."master_field_definitions" to "service_role";

grant insert on table "public"."master_field_definitions" to "service_role";

grant references on table "public"."master_field_definitions" to "service_role";

grant select on table "public"."master_field_definitions" to "service_role";

grant trigger on table "public"."master_field_definitions" to "service_role";

grant truncate on table "public"."master_field_definitions" to "service_role";

grant update on table "public"."master_field_definitions" to "service_role";

grant delete on table "public"."prompt_candidates" to "anon";

grant insert on table "public"."prompt_candidates" to "anon";

grant references on table "public"."prompt_candidates" to "anon";

grant select on table "public"."prompt_candidates" to "anon";

grant trigger on table "public"."prompt_candidates" to "anon";

grant truncate on table "public"."prompt_candidates" to "anon";

grant update on table "public"."prompt_candidates" to "anon";

grant delete on table "public"."prompt_candidates" to "authenticated";

grant insert on table "public"."prompt_candidates" to "authenticated";

grant references on table "public"."prompt_candidates" to "authenticated";

grant select on table "public"."prompt_candidates" to "authenticated";

grant trigger on table "public"."prompt_candidates" to "authenticated";

grant truncate on table "public"."prompt_candidates" to "authenticated";

grant update on table "public"."prompt_candidates" to "authenticated";

grant delete on table "public"."prompt_candidates" to "service_role";

grant insert on table "public"."prompt_candidates" to "service_role";

grant references on table "public"."prompt_candidates" to "service_role";

grant select on table "public"."prompt_candidates" to "service_role";

grant trigger on table "public"."prompt_candidates" to "service_role";

grant truncate on table "public"."prompt_candidates" to "service_role";

grant update on table "public"."prompt_candidates" to "service_role";

grant delete on table "public"."prompt_evaluations" to "anon";

grant insert on table "public"."prompt_evaluations" to "anon";

grant references on table "public"."prompt_evaluations" to "anon";

grant select on table "public"."prompt_evaluations" to "anon";

grant trigger on table "public"."prompt_evaluations" to "anon";

grant truncate on table "public"."prompt_evaluations" to "anon";

grant update on table "public"."prompt_evaluations" to "anon";

grant delete on table "public"."prompt_evaluations" to "authenticated";

grant insert on table "public"."prompt_evaluations" to "authenticated";

grant references on table "public"."prompt_evaluations" to "authenticated";

grant select on table "public"."prompt_evaluations" to "authenticated";

grant trigger on table "public"."prompt_evaluations" to "authenticated";

grant truncate on table "public"."prompt_evaluations" to "authenticated";

grant update on table "public"."prompt_evaluations" to "authenticated";

grant delete on table "public"."prompt_evaluations" to "service_role";

grant insert on table "public"."prompt_evaluations" to "service_role";

grant references on table "public"."prompt_evaluations" to "service_role";

grant select on table "public"."prompt_evaluations" to "service_role";

grant trigger on table "public"."prompt_evaluations" to "service_role";

grant truncate on table "public"."prompt_evaluations" to "service_role";

grant update on table "public"."prompt_evaluations" to "service_role";

grant delete on table "public"."prompt_template_groups" to "anon";

grant insert on table "public"."prompt_template_groups" to "anon";

grant references on table "public"."prompt_template_groups" to "anon";

grant select on table "public"."prompt_template_groups" to "anon";

grant trigger on table "public"."prompt_template_groups" to "anon";

grant truncate on table "public"."prompt_template_groups" to "anon";

grant update on table "public"."prompt_template_groups" to "anon";

grant delete on table "public"."prompt_template_groups" to "authenticated";

grant insert on table "public"."prompt_template_groups" to "authenticated";

grant references on table "public"."prompt_template_groups" to "authenticated";

grant select on table "public"."prompt_template_groups" to "authenticated";

grant trigger on table "public"."prompt_template_groups" to "authenticated";

grant truncate on table "public"."prompt_template_groups" to "authenticated";

grant update on table "public"."prompt_template_groups" to "authenticated";

grant delete on table "public"."prompt_template_groups" to "service_role";

grant insert on table "public"."prompt_template_groups" to "service_role";

grant references on table "public"."prompt_template_groups" to "service_role";

grant select on table "public"."prompt_template_groups" to "service_role";

grant trigger on table "public"."prompt_template_groups" to "service_role";

grant truncate on table "public"."prompt_template_groups" to "service_role";

grant update on table "public"."prompt_template_groups" to "service_role";

grant delete on table "public"."prompt_templates" to "anon";

grant insert on table "public"."prompt_templates" to "anon";

grant references on table "public"."prompt_templates" to "anon";

grant select on table "public"."prompt_templates" to "anon";

grant trigger on table "public"."prompt_templates" to "anon";

grant truncate on table "public"."prompt_templates" to "anon";

grant update on table "public"."prompt_templates" to "anon";

grant delete on table "public"."prompt_templates" to "authenticated";

grant insert on table "public"."prompt_templates" to "authenticated";

grant references on table "public"."prompt_templates" to "authenticated";

grant select on table "public"."prompt_templates" to "authenticated";

grant trigger on table "public"."prompt_templates" to "authenticated";

grant truncate on table "public"."prompt_templates" to "authenticated";

grant update on table "public"."prompt_templates" to "authenticated";

grant delete on table "public"."prompt_templates" to "service_role";

grant insert on table "public"."prompt_templates" to "service_role";

grant references on table "public"."prompt_templates" to "service_role";

grant select on table "public"."prompt_templates" to "service_role";

grant trigger on table "public"."prompt_templates" to "service_role";

grant truncate on table "public"."prompt_templates" to "service_role";

grant update on table "public"."prompt_templates" to "service_role";

grant delete on table "public"."prompt_versions" to "anon";

grant insert on table "public"."prompt_versions" to "anon";

grant references on table "public"."prompt_versions" to "anon";

grant select on table "public"."prompt_versions" to "anon";

grant trigger on table "public"."prompt_versions" to "anon";

grant truncate on table "public"."prompt_versions" to "anon";

grant update on table "public"."prompt_versions" to "anon";

grant delete on table "public"."prompt_versions" to "authenticated";

grant insert on table "public"."prompt_versions" to "authenticated";

grant references on table "public"."prompt_versions" to "authenticated";

grant select on table "public"."prompt_versions" to "authenticated";

grant trigger on table "public"."prompt_versions" to "authenticated";

grant truncate on table "public"."prompt_versions" to "authenticated";

grant update on table "public"."prompt_versions" to "authenticated";

grant delete on table "public"."prompt_versions" to "service_role";

grant insert on table "public"."prompt_versions" to "service_role";

grant references on table "public"."prompt_versions" to "service_role";

grant select on table "public"."prompt_versions" to "service_role";

grant trigger on table "public"."prompt_versions" to "service_role";

grant truncate on table "public"."prompt_versions" to "service_role";

grant update on table "public"."prompt_versions" to "service_role";

CREATE TRIGGER set_contract_definitions_updated_at BEFORE UPDATE ON public.contract_definitions FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_contract_type_fields_updated_at BEFORE UPDATE ON public.contract_type_fields FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_extraction_audit_updated_at BEFORE UPDATE ON public.extraction_audit FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_master_field_definitions_updated_at BEFORE UPDATE ON public.master_field_definitions FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_prompt_template_groups_updated_at BEFORE UPDATE ON public.prompt_template_groups FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_prompt_templates_updated_at BEFORE UPDATE ON public.prompt_templates FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();


