create table "public"."contract_users" (
    "id" bigint generated by default as identity not null,
    "contract_id" integer,
    "name" text not null,
    "email" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);


alter table "public"."contract_users" enable row level security;

CREATE UNIQUE INDEX contract_users_email_key ON public.contract_users USING btree (email);

CREATE UNIQUE INDEX contract_users_pkey ON public.contract_users USING btree (id);

alter table "public"."contract_users" add constraint "contract_users_pkey" PRIMARY KEY using index "contract_users_pkey";

alter table "public"."contract_users" add constraint "contract_users_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE not valid;

alter table "public"."contract_users" validate constraint "contract_users_contract_id_fkey";

alter table "public"."contract_users" add constraint "contract_users_email_key" UNIQUE using index "contract_users_email_key";

grant delete on table "public"."contract_users" to "anon";

grant insert on table "public"."contract_users" to "anon";

grant references on table "public"."contract_users" to "anon";

grant select on table "public"."contract_users" to "anon";

grant trigger on table "public"."contract_users" to "anon";

grant truncate on table "public"."contract_users" to "anon";

grant update on table "public"."contract_users" to "anon";

grant delete on table "public"."contract_users" to "authenticated";

grant insert on table "public"."contract_users" to "authenticated";

grant references on table "public"."contract_users" to "authenticated";

grant select on table "public"."contract_users" to "authenticated";

grant trigger on table "public"."contract_users" to "authenticated";

grant truncate on table "public"."contract_users" to "authenticated";

grant update on table "public"."contract_users" to "authenticated";

grant delete on table "public"."contract_users" to "service_role";

grant insert on table "public"."contract_users" to "service_role";

grant references on table "public"."contract_users" to "service_role";

grant select on table "public"."contract_users" to "service_role";

grant trigger on table "public"."contract_users" to "service_role";

grant truncate on table "public"."contract_users" to "service_role";

grant update on table "public"."contract_users" to "service_role";
