-- Migration: Create product version tables and fix RLS policies
-- 1. Fix contract_versions RLS to use contracts_visible_to() helper
-- 2. Add unique constraint on vendor_products_details.id for FK reference
-- 3. Create vendor_products_versions table
-- 4. Create vendor_products_details_versions table
-- 5. Create vendor_products_users_versions table

--------------------------------------------------------------------------------
-- Fix contract_versions RLS policy
--------------------------------------------------------------------------------

DROP POLICY IF EXISTS "contract_versions_read" ON public.contract_versions;

CREATE POLICY "contract_versions_read" ON public.contract_versions
    FOR SELECT
    TO authenticated
    USING (
        contract_id IN (
            SELECT id FROM contracts_visible_to(
                (SELECT organization_id FROM users WHERE id = auth.uid()),
                auth.uid()
            )
        )
    );

DROP POLICY IF EXISTS "contract_versions_anon_deny" ON public.contract_versions;

CREATE POLICY "contract_versions_anon_deny" ON public.contract_versions
    FOR ALL
    TO anon
    USING (false);

--------------------------------------------------------------------------------
-- Add unique constraint on vendor_products_details.id for FK reference
-- (Primary key was changed to composite key, but we need id for version FK)
--------------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS vendor_products_details_id_unique
    ON public.vendor_products_details(id);

--------------------------------------------------------------------------------
-- Create vendor_products_versions table
--------------------------------------------------------------------------------

CREATE TABLE public.vendor_products_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_product_id integer NOT NULL REFERENCES public.vendor_products(id) ON DELETE CASCADE,
    contract_id integer NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
    contract_version_id bigint NOT NULL REFERENCES public.contract_versions(id) ON DELETE CASCADE,
    version_id bigint NOT NULL,
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_to timestamptz,
    changed_data jsonb,
    created_by uuid REFERENCES public.users(id) ON UPDATE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor text,
    comment text,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,

    -- Mirrored vendor_products columns
    vendor_id integer,
    name character varying,
    delivery_method_id integer,
    updated_at timestamptz,

    CONSTRAINT vendor_products_versions_product_version_unique UNIQUE (vendor_product_id, version_id)
);

CREATE INDEX idx_vendor_products_versions_vendor_product_id ON public.vendor_products_versions(vendor_product_id);
CREATE INDEX idx_vendor_products_versions_contract_id ON public.vendor_products_versions(contract_id);
CREATE INDEX idx_vendor_products_versions_contract_version_id ON public.vendor_products_versions(contract_version_id);
CREATE INDEX idx_vendor_products_versions_organization_id ON public.vendor_products_versions(organization_id);
CREATE INDEX idx_vendor_products_versions_valid_from ON public.vendor_products_versions(valid_from);
CREATE INDEX idx_vendor_products_versions_created_by ON public.vendor_products_versions(created_by);

COMMENT ON TABLE public.vendor_products_versions IS 'Stores versioned snapshots of vendor products for edit history tracking';
COMMENT ON COLUMN public.vendor_products_versions.vendor_product_id IS 'Reference to the original vendor_product being versioned';
COMMENT ON COLUMN public.vendor_products_versions.contract_id IS 'The contract this vendor product version is associated with';
COMMENT ON COLUMN public.vendor_products_versions.contract_version_id IS 'Reference to the specific contract version this was part of';
COMMENT ON COLUMN public.vendor_products_versions.version_id IS 'Incrementing version number per vendor product (1, 2, 3, ...)';
COMMENT ON COLUMN public.vendor_products_versions.valid_from IS 'Timestamp when this version became active';
COMMENT ON COLUMN public.vendor_products_versions.valid_to IS 'Timestamp when this version was superseded (NULL if current)';
COMMENT ON COLUMN public.vendor_products_versions.changed_data IS 'JSON object tracking field changes, e.g., {"name": {"old": "Product A", "new": "Product B"}}';
COMMENT ON COLUMN public.vendor_products_versions.actor IS 'Type of actor that made the change (e.g., "user", "system", "api")';

ALTER TABLE public.vendor_products_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "vendor_products_versions_read" ON public.vendor_products_versions
    FOR SELECT
    TO authenticated
    USING (
        contract_id IN (
            SELECT id FROM contracts_visible_to(
                (SELECT organization_id FROM users WHERE id = auth.uid()),
                auth.uid()
            )
        )
    );

CREATE POLICY "vendor_products_versions_anon_deny" ON public.vendor_products_versions
    FOR ALL
    TO anon
    USING (false);

--------------------------------------------------------------------------------
-- Create vendor_products_details_versions table
--------------------------------------------------------------------------------

CREATE TABLE public.vendor_products_details_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_products_details_id integer NOT NULL REFERENCES public.vendor_products_details(id) ON DELETE CASCADE,
    contract_id integer NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
    contract_version_id bigint NOT NULL REFERENCES public.contract_versions(id) ON DELETE CASCADE,
    version_id bigint NOT NULL,
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_to timestamptz,
    changed_data jsonb,
    created_by uuid REFERENCES public.users(id) ON UPDATE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor text,
    comment text,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,

    -- Mirrored vendor_products_details columns
    product_id integer,
    fees numeric,
    n_users integer,
    year integer,
    user_id uuid,

    CONSTRAINT vendor_products_details_versions_details_version_unique UNIQUE (vendor_products_details_id, version_id)
);

CREATE INDEX idx_vendor_products_details_versions_details_id ON public.vendor_products_details_versions(vendor_products_details_id);
CREATE INDEX idx_vendor_products_details_versions_contract_id ON public.vendor_products_details_versions(contract_id);
CREATE INDEX idx_vendor_products_details_versions_contract_version_id ON public.vendor_products_details_versions(contract_version_id);
CREATE INDEX idx_vendor_products_details_versions_organization_id ON public.vendor_products_details_versions(organization_id);
CREATE INDEX idx_vendor_products_details_versions_valid_from ON public.vendor_products_details_versions(valid_from);
CREATE INDEX idx_vendor_products_details_versions_created_by ON public.vendor_products_details_versions(created_by);

COMMENT ON TABLE public.vendor_products_details_versions IS 'Stores versioned snapshots of vendor product details for edit history tracking';
COMMENT ON COLUMN public.vendor_products_details_versions.vendor_products_details_id IS 'Reference to the original vendor_products_details record being versioned';
COMMENT ON COLUMN public.vendor_products_details_versions.contract_id IS 'The contract this vendor product details version is associated with';
COMMENT ON COLUMN public.vendor_products_details_versions.contract_version_id IS 'Reference to the specific contract version this was part of';
COMMENT ON COLUMN public.vendor_products_details_versions.version_id IS 'Incrementing version number per vendor product details record (1, 2, 3, ...)';
COMMENT ON COLUMN public.vendor_products_details_versions.valid_from IS 'Timestamp when this version became active';
COMMENT ON COLUMN public.vendor_products_details_versions.valid_to IS 'Timestamp when this version was superseded (NULL if current)';
COMMENT ON COLUMN public.vendor_products_details_versions.changed_data IS 'JSON object tracking field changes, e.g., {"fees": {"old": 100, "new": 150}}';
COMMENT ON COLUMN public.vendor_products_details_versions.actor IS 'Type of actor that made the change (e.g., "user", "system", "api")';

ALTER TABLE public.vendor_products_details_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "vendor_products_details_versions_read" ON public.vendor_products_details_versions
    FOR SELECT
    TO authenticated
    USING (
        contract_id IN (
            SELECT id FROM contracts_visible_to(
                (SELECT organization_id FROM users WHERE id = auth.uid()),
                auth.uid()
            )
        )
    );

CREATE POLICY "vendor_products_details_versions_anon_deny" ON public.vendor_products_details_versions
    FOR ALL
    TO anon
    USING (false);

--------------------------------------------------------------------------------
-- Create vendor_products_users_versions table
--------------------------------------------------------------------------------

CREATE TABLE public.vendor_products_users_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_products_users_id integer NOT NULL REFERENCES public.vendor_products_users(id) ON DELETE CASCADE,
    contract_id integer NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
    contract_version_id bigint NOT NULL REFERENCES public.contract_versions(id) ON DELETE CASCADE,
    version_id bigint NOT NULL,
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_to timestamptz,
    changed_data jsonb,
    created_by uuid REFERENCES public.users(id) ON UPDATE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,

    -- Mirrored vendor_products_users columns
    product_id integer,
    number_of_users integer,

    CONSTRAINT vendor_products_users_versions_users_version_unique UNIQUE (vendor_products_users_id, version_id)
);

CREATE INDEX idx_vendor_products_users_versions_users_id ON public.vendor_products_users_versions(vendor_products_users_id);
CREATE INDEX idx_vendor_products_users_versions_contract_id ON public.vendor_products_users_versions(contract_id);
CREATE INDEX idx_vendor_products_users_versions_contract_version_id ON public.vendor_products_users_versions(contract_version_id);
CREATE INDEX idx_vendor_products_users_versions_organization_id ON public.vendor_products_users_versions(organization_id);
CREATE INDEX idx_vendor_products_users_versions_valid_from ON public.vendor_products_users_versions(valid_from);
CREATE INDEX idx_vendor_products_users_versions_created_by ON public.vendor_products_users_versions(created_by);

COMMENT ON TABLE public.vendor_products_users_versions IS 'Stores versioned snapshots of vendor product user counts for edit history tracking';
COMMENT ON COLUMN public.vendor_products_users_versions.vendor_products_users_id IS 'Reference to the original vendor_products_users record being versioned';
COMMENT ON COLUMN public.vendor_products_users_versions.contract_id IS 'The contract this vendor product users version is associated with';
COMMENT ON COLUMN public.vendor_products_users_versions.contract_version_id IS 'Reference to the specific contract version this was part of';
COMMENT ON COLUMN public.vendor_products_users_versions.version_id IS 'Incrementing version number per vendor product users record (1, 2, 3, ...)';
COMMENT ON COLUMN public.vendor_products_users_versions.valid_from IS 'Timestamp when this version became active';
COMMENT ON COLUMN public.vendor_products_users_versions.valid_to IS 'Timestamp when this version was superseded (NULL if current)';
COMMENT ON COLUMN public.vendor_products_users_versions.changed_data IS 'JSON object tracking field changes, e.g., {"number_of_users": {"old": 10, "new": 15}}';

ALTER TABLE public.vendor_products_users_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "vendor_products_users_versions_read" ON public.vendor_products_users_versions
    FOR SELECT
    TO authenticated
    USING (
        contract_id IN (
            SELECT id FROM contracts_visible_to(
                (SELECT organization_id FROM users WHERE id = auth.uid()),
                auth.uid()
            )
        )
    );

CREATE POLICY "vendor_products_users_versions_anon_deny" ON public.vendor_products_users_versions
    FOR ALL
    TO anon
    USING (false);
