create table "public"."document_field_values" (
    "id" bigint generated by default as identity not null,
    "module_document_id" bigint not null,
    "module_extraction_id" uuid,
    "value_text" text,
    "value_number" numeric(18,4),
    "value_boolean" boolean,
    "value_date" date,
    "value_json" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."document_types" (
    "id" bigint generated by default as identity not null,
    "module_id" bigint not null,
    "code" character varying(50) not null,
    "name" character varying(100) not null,
    "description" text,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."module_document_extractions" (
    "id" uuid not null default gen_random_uuid(),
    "module_document_id" bigint not null,
    "file_id" bigint not null,
    "raw_extraction" jsonb not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."module_document_files" (
    "id" bigint generated by default as identity not null,
    "public_id" uuid default gen_random_uuid(),
    "module_document_id" bigint not null,
    "file_path" text not null,
    "file_name" character varying(500) not null,
    "file_size" bigint,
    "file_type" character varying(50),
    "file_hash" character varying(64),
    "is_deleted" boolean default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."module_documents" (
    "id" bigint generated by default as identity not null,
    "public_id" uuid default gen_random_uuid(),
    "organization_id" uuid not null,
    "user_id" uuid not null,
    "module_id" bigint not null,
    "document_type_id" bigint not null,
    "metadata" jsonb default '{}'::jsonb,
    "status" character varying(20) not null default 'uploaded'::character varying,
    "is_deleted" boolean default false,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX document_field_values_module_document_id_module_extraction__key ON public.document_field_values USING btree (module_document_id, module_extraction_id);

CREATE UNIQUE INDEX document_field_values_pkey ON public.document_field_values USING btree (id);

CREATE UNIQUE INDEX document_types_module_id_code_key ON public.document_types USING btree (module_id, code);

CREATE UNIQUE INDEX document_types_pkey ON public.document_types USING btree (id);

CREATE INDEX idx_doc_types_module ON public.document_types USING btree (module_id);

CREATE INDEX idx_docs_created ON public.module_documents USING btree (organization_id, created_at DESC);

CREATE INDEX idx_docs_module ON public.module_documents USING btree (module_id);

CREATE INDEX idx_docs_not_deleted ON public.module_documents USING btree (organization_id) WHERE (is_deleted = false);

CREATE INDEX idx_docs_org ON public.module_documents USING btree (organization_id);

CREATE INDEX idx_docs_status ON public.module_documents USING btree (status);

CREATE INDEX idx_docs_type ON public.module_documents USING btree (document_type_id);

CREATE INDEX idx_docs_user ON public.module_documents USING btree (user_id);

CREATE UNIQUE INDEX module_document_extractions_module_document_id_file_id_key ON public.module_document_extractions USING btree (module_document_id, file_id);

CREATE UNIQUE INDEX module_document_extractions_pkey ON public.module_document_extractions USING btree (id);

CREATE UNIQUE INDEX module_document_files_pkey ON public.module_document_files USING btree (id);

CREATE UNIQUE INDEX module_documents_pkey ON public.module_documents USING btree (id);

CREATE UNIQUE INDEX module_documents_public_id_key ON public.module_documents USING btree (public_id);

alter table "public"."document_field_values" add constraint "document_field_values_pkey" PRIMARY KEY using index "document_field_values_pkey";

alter table "public"."document_types" add constraint "document_types_pkey" PRIMARY KEY using index "document_types_pkey";

alter table "public"."module_document_extractions" add constraint "module_document_extractions_pkey" PRIMARY KEY using index "module_document_extractions_pkey";

alter table "public"."module_document_files" add constraint "module_document_files_pkey" PRIMARY KEY using index "module_document_files_pkey";

alter table "public"."module_documents" add constraint "module_documents_pkey" PRIMARY KEY using index "module_documents_pkey";

alter table "public"."document_field_values" add constraint "document_field_values_module_document_id_fkey" FOREIGN KEY (module_document_id) REFERENCES module_documents(id) ON DELETE CASCADE not valid;

alter table "public"."document_field_values" validate constraint "document_field_values_module_document_id_fkey";

alter table "public"."document_field_values" add constraint "document_field_values_module_document_id_module_extraction__key" UNIQUE using index "document_field_values_module_document_id_module_extraction__key";

alter table "public"."document_field_values" add constraint "document_field_values_module_extraction_id_fkey" FOREIGN KEY (module_extraction_id) REFERENCES module_document_extractions(id) ON DELETE SET NULL not valid;

alter table "public"."document_field_values" validate constraint "document_field_values_module_extraction_id_fkey";

alter table "public"."document_types" add constraint "document_types_module_id_code_key" UNIQUE using index "document_types_module_id_code_key";

alter table "public"."document_types" add constraint "document_types_module_id_fkey" FOREIGN KEY (module_id) REFERENCES app_modules(id) not valid;

alter table "public"."document_types" validate constraint "document_types_module_id_fkey";

alter table "public"."module_document_extractions" add constraint "module_document_extractions_file_id_fkey" FOREIGN KEY (file_id) REFERENCES module_document_files(id) not valid;

alter table "public"."module_document_extractions" validate constraint "module_document_extractions_file_id_fkey";

alter table "public"."module_document_extractions" add constraint "module_document_extractions_module_document_id_file_id_key" UNIQUE using index "module_document_extractions_module_document_id_file_id_key";

alter table "public"."module_document_extractions" add constraint "module_document_extractions_module_document_id_fkey" FOREIGN KEY (module_document_id) REFERENCES module_documents(id) ON DELETE CASCADE not valid;

alter table "public"."module_document_extractions" validate constraint "module_document_extractions_module_document_id_fkey";

alter table "public"."module_document_files" add constraint "module_document_files_module_document_id_fkey" FOREIGN KEY (module_document_id) REFERENCES module_documents(id) ON DELETE CASCADE not valid;

alter table "public"."module_document_files" validate constraint "module_document_files_module_document_id_fkey";

alter table "public"."module_documents" add constraint "module_documents_document_type_id_fkey" FOREIGN KEY (document_type_id) REFERENCES document_types(id) not valid;

alter table "public"."module_documents" validate constraint "module_documents_document_type_id_fkey";

alter table "public"."module_documents" add constraint "module_documents_module_id_fkey" FOREIGN KEY (module_id) REFERENCES app_modules(id) not valid;

alter table "public"."module_documents" validate constraint "module_documents_module_id_fkey";

alter table "public"."module_documents" add constraint "module_documents_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."module_documents" validate constraint "module_documents_organization_id_fkey";

alter table "public"."module_documents" add constraint "module_documents_public_id_key" UNIQUE using index "module_documents_public_id_key";

alter table "public"."module_documents" add constraint "module_documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."module_documents" validate constraint "module_documents_user_id_fkey";

grant delete on table "public"."app_modules" to "postgres";

grant insert on table "public"."app_modules" to "postgres";

grant references on table "public"."app_modules" to "postgres";

grant select on table "public"."app_modules" to "postgres";

grant trigger on table "public"."app_modules" to "postgres";

grant truncate on table "public"."app_modules" to "postgres";

grant update on table "public"."app_modules" to "postgres";

grant delete on table "public"."document_field_values" to "anon";

grant insert on table "public"."document_field_values" to "anon";

grant references on table "public"."document_field_values" to "anon";

grant select on table "public"."document_field_values" to "anon";

grant trigger on table "public"."document_field_values" to "anon";

grant truncate on table "public"."document_field_values" to "anon";

grant update on table "public"."document_field_values" to "anon";

grant delete on table "public"."document_field_values" to "authenticated";

grant insert on table "public"."document_field_values" to "authenticated";

grant references on table "public"."document_field_values" to "authenticated";

grant select on table "public"."document_field_values" to "authenticated";

grant trigger on table "public"."document_field_values" to "authenticated";

grant truncate on table "public"."document_field_values" to "authenticated";

grant update on table "public"."document_field_values" to "authenticated";

grant delete on table "public"."document_field_values" to "postgres";

grant insert on table "public"."document_field_values" to "postgres";

grant references on table "public"."document_field_values" to "postgres";

grant select on table "public"."document_field_values" to "postgres";

grant trigger on table "public"."document_field_values" to "postgres";

grant truncate on table "public"."document_field_values" to "postgres";

grant update on table "public"."document_field_values" to "postgres";

grant delete on table "public"."document_field_values" to "service_role";

grant insert on table "public"."document_field_values" to "service_role";

grant references on table "public"."document_field_values" to "service_role";

grant select on table "public"."document_field_values" to "service_role";

grant trigger on table "public"."document_field_values" to "service_role";

grant truncate on table "public"."document_field_values" to "service_role";

grant update on table "public"."document_field_values" to "service_role";

grant delete on table "public"."document_types" to "anon";

grant insert on table "public"."document_types" to "anon";

grant references on table "public"."document_types" to "anon";

grant select on table "public"."document_types" to "anon";

grant trigger on table "public"."document_types" to "anon";

grant truncate on table "public"."document_types" to "anon";

grant update on table "public"."document_types" to "anon";

grant delete on table "public"."document_types" to "authenticated";

grant insert on table "public"."document_types" to "authenticated";

grant references on table "public"."document_types" to "authenticated";

grant select on table "public"."document_types" to "authenticated";

grant trigger on table "public"."document_types" to "authenticated";

grant truncate on table "public"."document_types" to "authenticated";

grant update on table "public"."document_types" to "authenticated";

grant delete on table "public"."document_types" to "postgres";

grant insert on table "public"."document_types" to "postgres";

grant references on table "public"."document_types" to "postgres";

grant select on table "public"."document_types" to "postgres";

grant trigger on table "public"."document_types" to "postgres";

grant truncate on table "public"."document_types" to "postgres";

grant update on table "public"."document_types" to "postgres";

grant delete on table "public"."document_types" to "service_role";

grant insert on table "public"."document_types" to "service_role";

grant references on table "public"."document_types" to "service_role";

grant select on table "public"."document_types" to "service_role";

grant trigger on table "public"."document_types" to "service_role";

grant truncate on table "public"."document_types" to "service_role";

grant update on table "public"."document_types" to "service_role";

grant delete on table "public"."module_document_extractions" to "anon";

grant insert on table "public"."module_document_extractions" to "anon";

grant references on table "public"."module_document_extractions" to "anon";

grant select on table "public"."module_document_extractions" to "anon";

grant trigger on table "public"."module_document_extractions" to "anon";

grant truncate on table "public"."module_document_extractions" to "anon";

grant update on table "public"."module_document_extractions" to "anon";

grant delete on table "public"."module_document_extractions" to "authenticated";

grant insert on table "public"."module_document_extractions" to "authenticated";

grant references on table "public"."module_document_extractions" to "authenticated";

grant select on table "public"."module_document_extractions" to "authenticated";

grant trigger on table "public"."module_document_extractions" to "authenticated";

grant truncate on table "public"."module_document_extractions" to "authenticated";

grant update on table "public"."module_document_extractions" to "authenticated";

grant delete on table "public"."module_document_extractions" to "postgres";

grant insert on table "public"."module_document_extractions" to "postgres";

grant references on table "public"."module_document_extractions" to "postgres";

grant select on table "public"."module_document_extractions" to "postgres";

grant trigger on table "public"."module_document_extractions" to "postgres";

grant truncate on table "public"."module_document_extractions" to "postgres";

grant update on table "public"."module_document_extractions" to "postgres";

grant delete on table "public"."module_document_extractions" to "service_role";

grant insert on table "public"."module_document_extractions" to "service_role";

grant references on table "public"."module_document_extractions" to "service_role";

grant select on table "public"."module_document_extractions" to "service_role";

grant trigger on table "public"."module_document_extractions" to "service_role";

grant truncate on table "public"."module_document_extractions" to "service_role";

grant update on table "public"."module_document_extractions" to "service_role";

grant delete on table "public"."module_document_files" to "anon";

grant insert on table "public"."module_document_files" to "anon";

grant references on table "public"."module_document_files" to "anon";

grant select on table "public"."module_document_files" to "anon";

grant trigger on table "public"."module_document_files" to "anon";

grant truncate on table "public"."module_document_files" to "anon";

grant update on table "public"."module_document_files" to "anon";

grant delete on table "public"."module_document_files" to "authenticated";

grant insert on table "public"."module_document_files" to "authenticated";

grant references on table "public"."module_document_files" to "authenticated";

grant select on table "public"."module_document_files" to "authenticated";

grant trigger on table "public"."module_document_files" to "authenticated";

grant truncate on table "public"."module_document_files" to "authenticated";

grant update on table "public"."module_document_files" to "authenticated";

grant delete on table "public"."module_document_files" to "postgres";

grant insert on table "public"."module_document_files" to "postgres";

grant references on table "public"."module_document_files" to "postgres";

grant select on table "public"."module_document_files" to "postgres";

grant trigger on table "public"."module_document_files" to "postgres";

grant truncate on table "public"."module_document_files" to "postgres";

grant update on table "public"."module_document_files" to "postgres";

grant delete on table "public"."module_document_files" to "service_role";

grant insert on table "public"."module_document_files" to "service_role";

grant references on table "public"."module_document_files" to "service_role";

grant select on table "public"."module_document_files" to "service_role";

grant trigger on table "public"."module_document_files" to "service_role";

grant truncate on table "public"."module_document_files" to "service_role";

grant update on table "public"."module_document_files" to "service_role";

grant delete on table "public"."module_documents" to "anon";

grant insert on table "public"."module_documents" to "anon";

grant references on table "public"."module_documents" to "anon";

grant select on table "public"."module_documents" to "anon";

grant trigger on table "public"."module_documents" to "anon";

grant truncate on table "public"."module_documents" to "anon";

grant update on table "public"."module_documents" to "anon";

grant delete on table "public"."module_documents" to "authenticated";

grant insert on table "public"."module_documents" to "authenticated";

grant references on table "public"."module_documents" to "authenticated";

grant select on table "public"."module_documents" to "authenticated";

grant trigger on table "public"."module_documents" to "authenticated";

grant truncate on table "public"."module_documents" to "authenticated";

grant update on table "public"."module_documents" to "authenticated";

grant delete on table "public"."module_documents" to "postgres";

grant insert on table "public"."module_documents" to "postgres";

grant references on table "public"."module_documents" to "postgres";

grant select on table "public"."module_documents" to "postgres";

grant trigger on table "public"."module_documents" to "postgres";

grant truncate on table "public"."module_documents" to "postgres";

grant update on table "public"."module_documents" to "postgres";

grant delete on table "public"."module_documents" to "service_role";

grant insert on table "public"."module_documents" to "service_role";

grant references on table "public"."module_documents" to "service_role";

grant select on table "public"."module_documents" to "service_role";

grant trigger on table "public"."module_documents" to "service_role";

grant truncate on table "public"."module_documents" to "service_role";

grant update on table "public"."module_documents" to "service_role";

grant delete on table "public"."organization_modules" to "postgres";

grant insert on table "public"."organization_modules" to "postgres";

grant references on table "public"."organization_modules" to "postgres";

grant select on table "public"."organization_modules" to "postgres";

grant trigger on table "public"."organization_modules" to "postgres";

grant truncate on table "public"."organization_modules" to "postgres";

grant update on table "public"."organization_modules" to "postgres";

grant delete on table "public"."user_module_access" to "postgres";

grant insert on table "public"."user_module_access" to "postgres";

grant references on table "public"."user_module_access" to "postgres";

grant select on table "public"."user_module_access" to "postgres";

grant trigger on table "public"."user_module_access" to "postgres";

grant truncate on table "public"."user_module_access" to "postgres";

grant update on table "public"."user_module_access" to "postgres";


