create sequence "public"."contract_data_delivery_types_id_seq";

create table "public"."contract_data_delivery_types" (
    "id" integer not null default nextval('contract_data_delivery_types_id_seq'::regclass),
    "contract_id" integer,
    "data_delivery_type_id" integer,
    "created_at" timestamp without time zone default now()
);


alter table "public"."contract_data_delivery_types" enable row level security;


create table "public"."data_delivery_types" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."data_delivery_types" enable row level security;

alter sequence "public"."contract_data_delivery_types_id_seq" owned by "public"."contract_data_delivery_types"."id";


CREATE UNIQUE INDEX contract_data_delivery_types_contract_id_data_delivery_type_key ON public.contract_data_delivery_types USING btree (contract_id, data_delivery_type_id);

CREATE UNIQUE INDEX contract_data_delivery_types_pkey ON public.contract_data_delivery_types USING btree (id);

CREATE UNIQUE INDEX data_delivery_types_pkey ON public.data_delivery_types USING btree (id);

alter table "public"."contract_data_delivery_types" add constraint "contract_data_delivery_types_pkey" PRIMARY KEY using index "contract_data_delivery_types_pkey";


alter table "public"."data_delivery_types" add constraint "data_delivery_types_pkey" PRIMARY KEY using index "data_delivery_types_pkey";

alter table "public"."contract_data_delivery_types" add constraint "contract_data_delivery_types_contract_id_data_delivery_type_key" UNIQUE using index "contract_data_delivery_types_contract_id_data_delivery_type_key";

alter table "public"."contract_data_delivery_types" add constraint "contract_data_delivery_types_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) not valid;

alter table "public"."contract_data_delivery_types" validate constraint "contract_data_delivery_types_contract_id_fkey";

alter table "public"."contract_data_delivery_types" add constraint "contract_data_delivery_types_data_delivery_type_id_fkey" FOREIGN KEY (data_delivery_type_id) REFERENCES data_delivery_types(id) not valid;

alter table "public"."contract_data_delivery_types" validate constraint "contract_data_delivery_types_data_delivery_type_id_fkey";

grant delete on table "public"."contract_data_delivery_types" to "authenticated";

grant insert on table "public"."contract_data_delivery_types" to "authenticated";

grant references on table "public"."contract_data_delivery_types" to "authenticated";

grant select on table "public"."contract_data_delivery_types" to "authenticated";

grant trigger on table "public"."contract_data_delivery_types" to "authenticated";

grant truncate on table "public"."contract_data_delivery_types" to "authenticated";

grant update on table "public"."contract_data_delivery_types" to "authenticated";

grant delete on table "public"."contract_data_delivery_types" to "service_role";

grant insert on table "public"."contract_data_delivery_types" to "service_role";

grant references on table "public"."contract_data_delivery_types" to "service_role";

grant select on table "public"."contract_data_delivery_types" to "service_role";

grant trigger on table "public"."contract_data_delivery_types" to "service_role";

grant truncate on table "public"."contract_data_delivery_types" to "service_role";

grant update on table "public"."contract_data_delivery_types" to "service_role";

grant delete on table "public"."data_delivery_types" to "authenticated";

grant insert on table "public"."data_delivery_types" to "authenticated";

grant references on table "public"."data_delivery_types" to "authenticated";

grant select on table "public"."data_delivery_types" to "authenticated";

grant trigger on table "public"."data_delivery_types" to "authenticated";

grant truncate on table "public"."data_delivery_types" to "authenticated";

grant update on table "public"."data_delivery_types" to "authenticated";

grant delete on table "public"."data_delivery_types" to "service_role";

grant insert on table "public"."data_delivery_types" to "service_role";

grant references on table "public"."data_delivery_types" to "service_role";

grant select on table "public"."data_delivery_types" to "service_role";

grant trigger on table "public"."data_delivery_types" to "service_role";

grant truncate on table "public"."data_delivery_types" to "service_role";

grant update on table "public"."data_delivery_types" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."contract_data_delivery_types"
as permissive
for insert
to authenticated, service_role
with check (true);


create policy "Enable read access for all users"
on "public"."contract_data_delivery_types"
as permissive
for select
to authenticated
using (true);

create policy "Enable insert for authenticated users only"
on "public"."data_delivery_types"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."data_delivery_types"
as permissive
for select
to authenticated
using (true);
