create table "public"."contract_docs_versions" (
    "id" integer generated by default as identity not null,
    "contract_id" integer not null,
    "file_path" character varying not null,
    "file_name" character varying not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "description" text
);


alter table "public"."contract_docs_versions" enable row level security;

CREATE INDEX contract_docs_versions_contract_created_idx ON public.contract_docs_versions USING btree (contract_id, created_at DESC);

CREATE UNIQUE INDEX contract_docs_versions_pkey ON public.contract_docs_versions USING btree (id);

alter table "public"."contract_docs_versions" add constraint "contract_docs_versions_pkey" PRIMARY KEY using index "contract_docs_versions_pkey";

alter table "public"."contract_docs_versions" add constraint "contract_docs_versions_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."contract_docs_versions" validate constraint "contract_docs_versions_contract_id_fkey";

alter table "public"."contract_docs_versions" add constraint "contract_docs_versions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."contract_docs_versions" validate constraint "contract_docs_versions_user_id_fkey";

grant delete on table "public"."contract_docs_versions" to "anon";

grant insert on table "public"."contract_docs_versions" to "anon";

grant references on table "public"."contract_docs_versions" to "anon";

grant select on table "public"."contract_docs_versions" to "anon";

grant trigger on table "public"."contract_docs_versions" to "anon";

grant truncate on table "public"."contract_docs_versions" to "anon";

grant update on table "public"."contract_docs_versions" to "anon";

grant delete on table "public"."contract_docs_versions" to "authenticated";

grant insert on table "public"."contract_docs_versions" to "authenticated";

grant references on table "public"."contract_docs_versions" to "authenticated";

grant select on table "public"."contract_docs_versions" to "authenticated";

grant trigger on table "public"."contract_docs_versions" to "authenticated";

grant truncate on table "public"."contract_docs_versions" to "authenticated";

grant update on table "public"."contract_docs_versions" to "authenticated";

grant delete on table "public"."contract_docs_versions" to "service_role";

grant insert on table "public"."contract_docs_versions" to "service_role";

grant references on table "public"."contract_docs_versions" to "service_role";

grant select on table "public"."contract_docs_versions" to "service_role";

grant trigger on table "public"."contract_docs_versions" to "service_role";

grant truncate on table "public"."contract_docs_versions" to "service_role";

grant update on table "public"."contract_docs_versions" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."contract_docs_versions"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for all users"
on "public"."contract_docs_versions"
as permissive
for select
to authenticated
using ((auth.uid() = user_id));



