create table "public"."vendor_products_users" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "contract_id" integer,
    "number_of_users" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now()
);

alter table "public"."contract_users" drop constraint "contract_users_contract_email_unique";

drop index if exists "public"."contract_users_contract_email_unique";

alter table "public"."vendor_products_users" enable row level security;

alter table "public"."contract_users" add column "product_id" bigint;

CREATE UNIQUE INDEX contract_users_email_product_unique_idx ON public.contract_users USING btree (contract_id, email, COALESCE(product_id, (0)::bigint));

CREATE UNIQUE INDEX unique_contract_null_product ON public.vendor_products_users USING btree (contract_id) WHERE (product_id IS NULL);

CREATE UNIQUE INDEX vendor_products_users_pkey ON public.vendor_products_users USING btree (id);

CREATE UNIQUE INDEX vendor_products_users_product_id_key ON public.vendor_products_users USING btree (product_id);


alter table "public"."vendor_products_users" add constraint "vendor_products_users_pkey" PRIMARY KEY using index "vendor_products_users_pkey";

alter table "public"."contract_users" add constraint "contract_users_product_id_fkey" FOREIGN KEY (product_id) REFERENCES vendor_products(id) ON DELETE SET NULL not valid;

alter table "public"."contract_users" validate constraint "contract_users_product_id_fkey";

alter table "public"."vendor_products_users" add constraint "vendor_products_users_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE not valid;

alter table "public"."vendor_products_users" validate constraint "vendor_products_users_contract_id_fkey";

alter table "public"."vendor_products_users" add constraint "vendor_products_users_product_id_fkey" FOREIGN KEY (product_id) REFERENCES vendor_products(id) ON DELETE SET NULL not valid;

alter table "public"."vendor_products_users" validate constraint "vendor_products_users_product_id_fkey";

alter table "public"."vendor_products_users" add constraint "vendor_products_users_product_id_key" UNIQUE using index "vendor_products_users_product_id_key";

grant delete on table "public"."vendor_products_users" to "authenticated";

grant insert on table "public"."vendor_products_users" to "authenticated";

grant references on table "public"."vendor_products_users" to "authenticated";

grant select on table "public"."vendor_products_users" to "authenticated";

grant trigger on table "public"."vendor_products_users" to "authenticated";

grant truncate on table "public"."vendor_products_users" to "authenticated";

grant update on table "public"."vendor_products_users" to "authenticated";

grant delete on table "public"."vendor_products_users" to "service_role";

grant insert on table "public"."vendor_products_users" to "service_role";

grant references on table "public"."vendor_products_users" to "service_role";

grant select on table "public"."vendor_products_users" to "service_role";

grant trigger on table "public"."vendor_products_users" to "service_role";

grant truncate on table "public"."vendor_products_users" to "service_role";

grant update on table "public"."vendor_products_users" to "service_role";
