-- Create contract_versions table for tracking contract edits
-- This table mirrors the contracts table structure with additional versioning columns

CREATE TABLE public.contract_versions (
    -- Version tracking columns
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id integer NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
    version_id bigint NOT NULL,
    valid_from timestamptz NOT NULL DEFAULT now(),
    valid_to timestamptz,
    changed_data jsonb,
    created_by uuid REFERENCES public.users(id) ON UPDATE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor text,
    comment text,

    -- Mirrored contract columns (identical to contracts table)
    vendor_id integer,
    cancel_by_date integer,
    auto_renewal boolean,
    billing_frequency character varying,
    payment_terms text,
    exclusivity_terms character varying,
    multi_year boolean,
    annual_increase real,
    owner character varying,
    currency character varying,
    other_attributes jsonb,
    products_fees jsonb,
    user_id uuid,
    updated_at timestamptz,
    cancellation_process text,
    distribution_rights character varying,
    execution_date date,
    geo_restrictions character varying,
    marketing_rights character varying,
    permissions text,
    scope_of_use text,
    suspension_of_service text,
    business_group text,
    business_justification text,
    business_order text,
    ai_extraction jsonb,
    status_id bigint,
    type_id bigint,
    open_ai_file_id character varying,
    summary text,
    related_contract_id integer,
    renewal_type text,
    ai_validation jsonb,
    locked_by uuid,
    locked_by_email text,
    tos_urls jsonb,
    submitted_by text,
    postsig_notes text,
    data_disposal_tnc text,
    discount integer,
    ext_validation jsonb,
    status contract_status NOT NULL DEFAULT 'active'::contract_status,
    ai_extraction_status ai_extraction_status,
    activities text,
    derivative_works text,
    end_users text,
    internal_external_users text,
    market_data_types text,
    audit_requirements text,
    term_end_date jsonb,
    term_start_date jsonb,
    cancel_date jsonb,
    trying_to_update_another_doc boolean,
    all_parties_signed text,
    date_of_last_signature date,
    required_signature_count integer,
    doc_fully_executed boolean,
    number_of_users text,
    ai_notes text,
    is_duplicate boolean NOT NULL DEFAULT false,
    will_not_renew boolean DEFAULT false,
    arbitration_and_conflict_resolution text,
    cost_mitigation text,
    security_awareness text,
    service_level_agreements text,
    vendor_location text,
    ai_training_restrictions text,
    will_not_renew_meta jsonb,
    metadata jsonb,
    legacy_renewal_period text,
    renewal_period integer,
    subscription_term double precision,
    annual_increase_months integer,
    business_sponsor jsonb DEFAULT '[]'::jsonb,
    folder_id uuid,
    organization_id uuid,

    CONSTRAINT contract_versions_contract_version_unique UNIQUE (contract_id, version_id)
);

CREATE INDEX idx_contract_versions_contract_id ON public.contract_versions(contract_id);
CREATE INDEX idx_contract_versions_organization_id ON public.contract_versions(organization_id);
CREATE INDEX idx_contract_versions_valid_from ON public.contract_versions(valid_from);
CREATE INDEX idx_contract_versions_created_by ON public.contract_versions(created_by);

COMMENT ON TABLE public.contract_versions IS 'Stores versioned snapshots of contracts for edit history tracking';
COMMENT ON COLUMN public.contract_versions.version_id IS 'Incrementing version number per contract (1, 2, 3, ...)';
COMMENT ON COLUMN public.contract_versions.valid_from IS 'Timestamp when this version became active';
COMMENT ON COLUMN public.contract_versions.valid_to IS 'Timestamp when this version was superseded (NULL if current)';
COMMENT ON COLUMN public.contract_versions.changed_data IS 'JSON object tracking field changes, e.g., {"currency": {"old": "usd", "new": "eur"}}';
COMMENT ON COLUMN public.contract_versions.actor IS 'Type of actor that made the change (e.g., "user", "system", "api")';

-- Enable RLS
ALTER TABLE public.contract_versions ENABLE ROW LEVEL SECURITY;

-- RLS policy: users can read versions for contracts they have access to
CREATE POLICY "contract_versions_read" ON public.contract_versions
    FOR SELECT
    TO authenticated
    USING (
        organization_id IN (
            SELECT organization_id FROM users WHERE id = auth.uid()
        )
        AND
        EXISTS (
            SELECT 1 FROM contracts c
            WHERE c.id = contract_versions.contract_id
            AND c.organization_id = contract_versions.organization_id
            AND (
                is_org_admin(c.organization_id, auth.uid())
                OR EXISTS (
                    SELECT 1 FROM contract_acl_user cu
                    WHERE cu.organization_id = c.organization_id
                    AND cu.contract_id = c.id
                    AND cu.user_id = auth.uid()
                )
                OR EXISTS (
                    SELECT 1 FROM contract_acl_group cg
                    JOIN group_members gm ON gm.organization_id = cg.organization_id
                        AND gm.group_id = cg.group_id
                        AND gm.user_id = auth.uid()
                    WHERE cg.organization_id = c.organization_id
                    AND cg.contract_id = c.id
                )
                OR EXISTS (
                    WITH f_child AS (
                        SELECT f.id, f.path
                        FROM folder_contracts fc
                        JOIN folders f ON f.id = fc.folder_id AND f.organization_id = c.organization_id
                        WHERE fc.organization_id = c.organization_id AND fc.contract_id = c.id
                    ),
                    u_grants AS (
                        SELECT fu.folder_id, f.path
                        FROM folder_acl_user fu
                        JOIN folders f ON f.id = fu.folder_id AND f.organization_id = fu.organization_id
                        WHERE fu.organization_id = c.organization_id AND fu.user_id = auth.uid()
                    ),
                    g_grants AS (
                        SELECT fg.folder_id, f.path
                        FROM folder_acl_group fg
                        JOIN group_members gm ON gm.organization_id = fg.organization_id
                            AND gm.group_id = fg.group_id
                            AND gm.user_id = auth.uid()
                        JOIN folders f ON f.id = fg.folder_id AND f.organization_id = fg.organization_id
                        WHERE fg.organization_id = c.organization_id
                    )
                    SELECT 1 FROM f_child fc_inner
                    WHERE EXISTS (SELECT 1 FROM u_grants ug WHERE ug.path @> fc_inner.path)
                       OR EXISTS (SELECT 1 FROM g_grants gg WHERE gg.path @> fc_inner.path)
                )
            )
        )
    );
