create table "public"."app_invites" (
    "id" bigint generated by default as identity not null,
    "token" text,
    "organization_id" uuid,
    "user_id" uuid,
    "expires_at" timestamp with time zone,
    "expired" boolean not null default false,
    "invited_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


alter table "public"."app_invites" enable row level security;


CREATE UNIQUE INDEX app_invites_pkey ON public.app_invites USING btree (id);

CREATE UNIQUE INDEX app_invites_token_key ON public.app_invites USING btree (token);


alter table "public"."app_invites" add constraint "app_invites_pkey" PRIMARY KEY using index "app_invites_pkey";

alter table "public"."app_invites" add constraint "app_invites_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) not valid;

alter table "public"."app_invites" validate constraint "app_invites_organization_id_fkey";

alter table "public"."app_invites" add constraint "app_invites_token_key" UNIQUE using index "app_invites_token_key";

alter table "public"."app_invites" add constraint "app_invites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) not valid;

alter table "public"."app_invites" validate constraint "app_invites_user_id_fkey";

grant delete on table "public"."app_invites" to "service_role";

grant insert on table "public"."app_invites" to "service_role";

grant references on table "public"."app_invites" to "service_role";

grant select on table "public"."app_invites" to "service_role";

grant trigger on table "public"."app_invites" to "service_role";

grant truncate on table "public"."app_invites" to "service_role";

grant update on table "public"."app_invites" to "service_role";


create policy "Enable read access for all users"
on "public"."app_invites"
as permissive
for select
to service_role
using (true);
