-- NOTE TO ZIYA: THIS IS JUST AN IDEA FOR POSSIBLE WAY TO HANDLE COMPANY ENTITY TO LINK VARIOUS DOCUMENTS/FIELDS
-- Migration: Create companies table (cloned from vendors) and module_entities
-- This establishes the foundation for multi-module entity support

--------------------------------------------------------------------------------
-- 1. Create company status enum (similar to VendorStatus)
--------------------------------------------------------------------------------
CREATE TYPE "CompanyStatus" AS ENUM ('active', 'inactive', 'merged', 'acquired');

--------------------------------------------------------------------------------
-- 2. Create companies table (global shared entities)
--------------------------------------------------------------------------------
CREATE TABLE public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT,
    description TEXT,
    address TEXT,
    email VARCHAR(255),
    phone VARCHAR(50),
    industry TEXT,
    headquarters TEXT,
    legal_jurisdiction TEXT,
    founded_year INTEGER,
    status "CompanyStatus" DEFAULT 'active',
    -- For M&A tracking (similar to vendors)
    merged_into_company_id BIGINT REFERENCES public.companies(id) ON DELETE SET NULL,
    merger_effective_date TIMESTAMPTZ,
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX idx_companies_name ON public.companies(name);
CREATE INDEX idx_companies_domain ON public.companies(domain);
CREATE INDEX idx_companies_status ON public.companies(status);

-- RLS: Global read access for authenticated users (similar to vendors)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "companies_select" ON public.companies
    FOR SELECT
    TO authenticated
    USING (true);

-- For now, any authenticated user can insert/update
-- (can restrict to admins later if needed)
CREATE POLICY "companies_insert" ON public.companies
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "companies_update" ON public.companies
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Deny anon access
CREATE POLICY "companies_anon_deny" ON public.companies
    FOR ALL
    TO anon
    USING (false);

--------------------------------------------------------------------------------
-- 3. Create module_entities table (org-scoped entity instances)
--------------------------------------------------------------------------------
CREATE TABLE public.module_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID DEFAULT gen_random_uuid() UNIQUE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id),
    module_id BIGINT NOT NULL REFERENCES public.app_modules(id),
    company_id BIGINT REFERENCES public.companies(id),
    -- Entity type within the module (e.g., 'portfolio_company', 'borrower')
    entity_type TEXT NOT NULL,
    -- Display name (may differ from company name, e.g., "Series A - Acme")
    name TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    -- Flexible metadata for type-specific fields
    metadata JSONB DEFAULT '{}',
    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    -- Ensure unique entity per org/module/company/type combination
    UNIQUE(organization_id, module_id, company_id, entity_type)
);

-- Indexes
CREATE INDEX idx_module_entities_org ON public.module_entities(organization_id);
CREATE INDEX idx_module_entities_module ON public.module_entities(module_id);
CREATE INDEX idx_module_entities_company ON public.module_entities(company_id);
CREATE INDEX idx_module_entities_type ON public.module_entities(entity_type);
CREATE INDEX idx_module_entities_org_module ON public.module_entities(organization_id, module_id);

-- RLS: Org-scoped access
ALTER TABLE public.module_entities ENABLE ROW LEVEL SECURITY;

-- SELECT: Users can read entities in their organization
CREATE POLICY "module_entities_select" ON public.module_entities
    FOR SELECT
    TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id
            FROM users u
            WHERE u.id = auth.uid()
        )
    );

-- INSERT: Users with admin role can create entities
CREATE POLICY "module_entities_insert" ON public.module_entities
    FOR INSERT
    TO authenticated
    WITH CHECK (
        organization_id IN (
            SELECT u.organization_id
            FROM users u
            WHERE u.id = auth.uid()
        )
    );

-- UPDATE: Users with admin role can update entities
CREATE POLICY "module_entities_update" ON public.module_entities
    FOR UPDATE
    TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id
            FROM users u
            WHERE u.id = auth.uid()
        )
    )
    WITH CHECK (
        organization_id IN (
            SELECT u.organization_id
            FROM users u
            WHERE u.id = auth.uid()
        )
    );

-- DELETE: Users with admin role can delete entities
CREATE POLICY "module_entities_delete" ON public.module_entities
    FOR DELETE
    TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id
            FROM users u
            WHERE u.id = auth.uid()
        )
    );

-- Deny anon access
CREATE POLICY "module_entities_anon_deny" ON public.module_entities
    FOR ALL
    TO anon
    USING (false);

-- Audit trigger
CREATE TRIGGER audit_module_entities_trigger
    AFTER INSERT OR DELETE OR UPDATE
    ON public.module_entities
    FOR EACH ROW
    EXECUTE FUNCTION audit_trigger_function();

--------------------------------------------------------------------------------
-- 4. Add entity_id to module_documents
--------------------------------------------------------------------------------
ALTER TABLE public.module_documents
    ADD COLUMN entity_id BIGINT REFERENCES public.module_entities(id) ON DELETE SET NULL;

CREATE INDEX idx_module_documents_entity ON public.module_documents(entity_id);

--------------------------------------------------------------------------------
-- 5. Grant permissions
--------------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.companies TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.companies TO service_role;
GRANT SELECT ON public.companies TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_entities TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_entities TO service_role;
