create extension if not exists "vector" with schema "public";

create table "public"."contract_citations" (
    "id" bigint generated by default as identity not null,
    "contract_id" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "citation_text" jsonb,
    "user_id" uuid,
    "organization_id" uuid
);


alter table "public"."contract_citations" enable row level security;

create table "public"."documents" (
    "id" text not null,
    "content" text,
    "metadata" jsonb,
    "embedding" vector(1536),
    "user_id" uuid,
    "organization_id" uuid
);


alter table "public"."documents" enable row level security;

alter table "public"."contract_relationships" add column "metadata" jsonb;

CREATE UNIQUE INDEX contract_citations_contract_id_key ON public.contract_citations USING btree (contract_id);

CREATE UNIQUE INDEX contract_citations_pkey ON public.contract_citations USING btree (id);

CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (id);

alter table "public"."contract_citations" add constraint "contract_citations_pkey" PRIMARY KEY using index "contract_citations_pkey";

alter table "public"."documents" add constraint "documents_pkey" PRIMARY KEY using index "documents_pkey";

alter table "public"."contract_citations" add constraint "contract_citations_contract_id_fkey" FOREIGN KEY (contract_id) REFERENCES contracts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."contract_citations" validate constraint "contract_citations_contract_id_fkey";

alter table "public"."contract_citations" add constraint "contract_citations_contract_id_key" UNIQUE using index "contract_citations_contract_id_key";

alter table "public"."contract_citations" add constraint "contract_citations_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE not valid;

alter table "public"."contract_citations" validate constraint "contract_citations_organization_id_fkey";

alter table "public"."contract_citations" add constraint "contract_citations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE not valid;

alter table "public"."contract_citations" validate constraint "contract_citations_user_id_fkey";

alter table "public"."documents" add constraint "documents_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON UPDATE CASCADE not valid;

alter table "public"."documents" validate constraint "documents_organization_id_fkey";

alter table "public"."documents" add constraint "documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE not valid;

alter table "public"."documents" validate constraint "documents_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_documents(query_embedding vector, match_threshold double precision DEFAULT 0.7, match_count integer DEFAULT 5)
 RETURNS TABLE(id text, content text, metadata jsonb, similarity double precision)
 LANGUAGE plpgsql
AS $function$
begin
  return query
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where 1 - (documents.embedding <=> query_embedding) > match_threshold
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$function$
;

grant delete on table "public"."contract_citations" to "anon";

grant insert on table "public"."contract_citations" to "anon";

grant references on table "public"."contract_citations" to "anon";

grant select on table "public"."contract_citations" to "anon";

grant trigger on table "public"."contract_citations" to "anon";

grant truncate on table "public"."contract_citations" to "anon";

grant update on table "public"."contract_citations" to "anon";

grant delete on table "public"."contract_citations" to "authenticated";

grant insert on table "public"."contract_citations" to "authenticated";

grant references on table "public"."contract_citations" to "authenticated";

grant select on table "public"."contract_citations" to "authenticated";

grant trigger on table "public"."contract_citations" to "authenticated";

grant truncate on table "public"."contract_citations" to "authenticated";

grant update on table "public"."contract_citations" to "authenticated";

grant delete on table "public"."contract_citations" to "service_role";

grant insert on table "public"."contract_citations" to "service_role";

grant references on table "public"."contract_citations" to "service_role";

grant select on table "public"."contract_citations" to "service_role";

grant trigger on table "public"."contract_citations" to "service_role";

grant truncate on table "public"."contract_citations" to "service_role";

grant update on table "public"."contract_citations" to "service_role";

grant delete on table "public"."documents" to "anon";

grant insert on table "public"."documents" to "anon";

grant references on table "public"."documents" to "anon";

grant select on table "public"."documents" to "anon";

grant trigger on table "public"."documents" to "anon";

grant truncate on table "public"."documents" to "anon";

grant update on table "public"."documents" to "anon";

grant delete on table "public"."documents" to "authenticated";

grant insert on table "public"."documents" to "authenticated";

grant references on table "public"."documents" to "authenticated";

grant select on table "public"."documents" to "authenticated";

grant trigger on table "public"."documents" to "authenticated";

grant truncate on table "public"."documents" to "authenticated";

grant update on table "public"."documents" to "authenticated";

grant delete on table "public"."documents" to "service_role";

grant insert on table "public"."documents" to "service_role";

grant references on table "public"."documents" to "service_role";

grant select on table "public"."documents" to "service_role";

grant trigger on table "public"."documents" to "service_role";

grant truncate on table "public"."documents" to "service_role";

grant update on table "public"."documents" to "service_role";


