-- module_archives: per-module record that a ZIP / archive container was received.
-- Archive contents are processed elsewhere (or not at all); this table only
-- captures "we have your file" so users can verify receipt without polluting
-- module_documents (which is reserved for documents that flow through the
-- extraction pipeline).

CREATE TABLE public.module_archives (
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id        uuid DEFAULT gen_random_uuid(),
    organization_id  uuid NOT NULL,
    user_id          uuid NOT NULL,
    module_id        bigint NOT NULL,
    file_path        text NOT NULL,
    file_name        varchar(500) NOT NULL,
    file_size        bigint,
    file_type        varchar(100),
    file_hash        varchar(64),
    metadata         jsonb DEFAULT '{}'::jsonb,
    is_deleted       boolean DEFAULT false,
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX module_archives_pkey ON public.module_archives USING btree (id);
CREATE UNIQUE INDEX module_archives_public_id_key ON public.module_archives USING btree (public_id);
CREATE INDEX idx_module_archives_org_created ON public.module_archives USING btree (organization_id, created_at DESC);
CREATE INDEX idx_module_archives_org_module ON public.module_archives USING btree (organization_id, module_id);
CREATE INDEX idx_module_archives_user ON public.module_archives USING btree (user_id);
CREATE INDEX idx_module_archives_not_deleted ON public.module_archives USING btree (organization_id) WHERE (is_deleted = false);

ALTER TABLE public.module_archives
    ADD CONSTRAINT module_archives_pkey PRIMARY KEY USING INDEX module_archives_pkey;

ALTER TABLE public.module_archives
    ADD CONSTRAINT module_archives_organization_id_fkey
    FOREIGN KEY (organization_id) REFERENCES public.organizations(id);

ALTER TABLE public.module_archives
    ADD CONSTRAINT module_archives_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE public.module_archives
    ADD CONSTRAINT module_archives_module_id_fkey
    FOREIGN KEY (module_id) REFERENCES public.app_modules(id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_archives TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.module_archives TO service_role;

ALTER TABLE public.module_archives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "module_archives_anon_deny" ON public.module_archives
    FOR ALL TO anon
    USING (false);

CREATE POLICY "module_archives_select" ON public.module_archives
    FOR SELECT TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id FROM public.users u WHERE u.id = auth.uid()
        )
    );

CREATE POLICY "module_archives_insert" ON public.module_archives
    FOR INSERT TO authenticated
    WITH CHECK (
        organization_id IN (
            SELECT u.organization_id FROM public.users u WHERE u.id = auth.uid()
        )
    );

CREATE POLICY "module_archives_update" ON public.module_archives
    FOR UPDATE TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id FROM public.users u WHERE u.id = auth.uid()
        )
        AND (
            user_id = auth.uid()
            OR EXISTS (
                SELECT 1 FROM public.user_roles2 ur
                WHERE ur.user_id = auth.uid() AND ur.role_id IN (11, 12)
            )
        )
    )
    WITH CHECK (
        organization_id IN (
            SELECT u.organization_id FROM public.users u WHERE u.id = auth.uid()
        )
    );

CREATE POLICY "module_archives_delete" ON public.module_archives
    FOR DELETE TO authenticated
    USING (
        organization_id IN (
            SELECT u.organization_id FROM public.users u WHERE u.id = auth.uid()
        )
        AND EXISTS (
            SELECT 1 FROM public.user_roles2 ur
            WHERE ur.user_id = auth.uid() AND ur.role_id IN (11, 12)
        )
    );

-- Internal/PostSig-staff audit trail (writes to public.audit_log)
CREATE TRIGGER audit_module_archives_trigger
    AFTER INSERT OR UPDATE OR DELETE ON public.module_archives
    FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_function();

-- Org-readable module audit trail (writes to public.module_audit_logs)
CREATE TRIGGER module_audit_module_archives_trigger
    AFTER INSERT OR UPDATE OR DELETE ON public.module_archives
    FOR EACH ROW EXECUTE FUNCTION public.module_audit_trigger_function();
