-- Table
create table "public"."module_document_funds" (
    "id" bigint generated by default as identity not null,
    "module_document_id" bigint not null,
    "fund_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid not null
);

-- Primary key
CREATE UNIQUE INDEX module_document_funds_pkey ON public.module_document_funds USING btree (id);

alter table "public"."module_document_funds" add constraint "module_document_funds_pkey" PRIMARY KEY using index "module_document_funds_pkey";

-- Unique constraint to prevent duplicate fund associations per document
CREATE UNIQUE INDEX idx_module_document_funds_doc_fund ON public.module_document_funds USING btree (module_document_id, fund_id);

-- Indexes
CREATE INDEX idx_module_document_funds_org ON public.module_document_funds USING btree (organization_id);
CREATE INDEX idx_module_document_funds_document ON public.module_document_funds USING btree (module_document_id);
CREATE INDEX idx_module_document_funds_fund ON public.module_document_funds USING btree (fund_id);

-- Foreign keys
alter table "public"."module_document_funds" add constraint "module_document_funds_fund_id_fkey" FOREIGN KEY (fund_id) REFERENCES public.inv_fund(id) ON DELETE CASCADE not valid;
alter table "public"."module_document_funds" validate constraint "module_document_funds_fund_id_fkey";

alter table "public"."module_document_funds" add constraint "module_document_funds_module_document_id_fkey" FOREIGN KEY (module_document_id) REFERENCES public.module_documents(id) ON DELETE CASCADE not valid;
alter table "public"."module_document_funds" validate constraint "module_document_funds_module_document_id_fkey";

alter table "public"."module_document_funds" add constraint "module_document_funds_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."module_document_funds" validate constraint "module_document_funds_organization_id_fkey";

-- RLS
alter table "public"."module_document_funds" enable row level security;

CREATE POLICY "org_access" ON public.module_document_funds
    FOR ALL
    TO authenticated
    USING (organization_id = public.user_organization_id())
    WITH CHECK (organization_id = public.user_organization_id());

CREATE POLICY "module_document_funds_anon_deny" ON public.module_document_funds
    FOR ALL
    TO anon
    USING (false);

-- Audit
CREATE TRIGGER module_audit_module_document_funds_trigger
    AFTER INSERT OR UPDATE OR DELETE
    ON public.module_document_funds
    FOR EACH ROW
    EXECUTE FUNCTION module_audit_trigger_function();

-- Grants
grant select, insert, update, delete on table "public"."module_document_funds" to "authenticated";

grant all on table "public"."module_document_funds" to "postgres";
grant all on table "public"."module_document_funds" to "service_role";
