create table "public"."module_document_status_types" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "code" text,
    "description" text,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text)
);


alter table "public"."module_document_status_types" enable row level security;

create policy "module_document_status_types_select_authenticated"
on "public"."module_document_status_types"
for select
to authenticated
using (true);

CREATE UNIQUE INDEX module_document_status_types_code_idx ON public.module_document_status_types USING btree (code);

CREATE UNIQUE INDEX module_document_status_types_pkey ON public.module_document_status_types USING btree (id);

alter table "public"."module_document_status_types" add constraint "module_document_status_types_pkey" PRIMARY KEY using index "module_document_status_types_pkey";

grant references on table "public"."module_document_status_types" to "authenticated";

grant select on table "public"."module_document_status_types" to "authenticated";

grant delete on table "public"."module_document_status_types" to "postgres";

grant insert on table "public"."module_document_status_types" to "postgres";

grant references on table "public"."module_document_status_types" to "postgres";

grant select on table "public"."module_document_status_types" to "postgres";

grant trigger on table "public"."module_document_status_types" to "postgres";

grant truncate on table "public"."module_document_status_types" to "postgres";

grant update on table "public"."module_document_status_types" to "postgres";

grant delete on table "public"."module_document_status_types" to "service_role";

grant insert on table "public"."module_document_status_types" to "service_role";

grant references on table "public"."module_document_status_types" to "service_role";

grant select on table "public"."module_document_status_types" to "service_role";

grant trigger on table "public"."module_document_status_types" to "service_role";

grant truncate on table "public"."module_document_status_types" to "service_role";

grant update on table "public"."module_document_status_types" to "service_role";

INSERT INTO public.module_document_status_types (id, name, code, description)
 VALUES
    (1, 'Uploaded', 'uploaded', 'Document is uploaded'),
    (2, 'Ready for extraction', 'ready_for_extraction', 'Document is ready for extraction'),
    (3, 'Processing', 'processing', 'Document is being processed'),
    (4, 'Needs approval', 'needs_approval', 'Document needs approval'),
    (5, 'Published', 'published', 'Document is published'),
    (6, 'Failed', 'failed', 'Document processing failed')
 ON CONFLICT (code) DO NOTHING;

select setval(
  pg_get_serial_sequence('public.module_document_status_types', 'id'),
  (select coalesce(max(id), 1) from public.module_document_status_types),
  true
);

