-- =============================================================================
-- org_employee_import_runs: delta report captured when an employee import
-- commits into a non-empty directory. `changes` holds the line-by-line diff
-- (joiners, leavers, movers, attribute changes) computed against the
-- directory state read just before the write, so the report survives later
-- edits to org_employees and needs no access to the original file. Storage
-- scales with churn, not headcount: unchanged employees are not recorded.
-- =============================================================================

create table "public"."org_employee_import_runs" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "file_name" text not null,
    "imported_by" uuid,
    "row_count" integer not null,
    "previous_employee_count" integer not null,
    "previous_run_id" bigint,
    "changes" jsonb not null default '[]'::jsonb,
    "created_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX org_employee_import_runs_pkey ON public.org_employee_import_runs USING btree (id);

alter table "public"."org_employee_import_runs" add constraint "org_employee_import_runs_pkey" PRIMARY KEY using index "org_employee_import_runs_pkey";

-- The employees page asks for the latest run per organization.
CREATE INDEX idx_org_employee_import_runs_org_created ON public.org_employee_import_runs USING btree (organization_id, created_at DESC);

alter table "public"."org_employee_import_runs" add constraint "org_employee_import_runs_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."org_employee_import_runs" validate constraint "org_employee_import_runs_organization_id_fkey";

alter table "public"."org_employee_import_runs" add constraint "org_employee_import_runs_imported_by_fkey" FOREIGN KEY (imported_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;
alter table "public"."org_employee_import_runs" validate constraint "org_employee_import_runs_imported_by_fkey";

alter table "public"."org_employee_import_runs" add constraint "org_employee_import_runs_previous_run_id_fkey" FOREIGN KEY (previous_run_id) REFERENCES public.org_employee_import_runs(id) ON DELETE SET NULL not valid;
alter table "public"."org_employee_import_runs" validate constraint "org_employee_import_runs_previous_run_id_fkey";

-- RLS: org members read; writes happen through the service client only, so no
-- insert/update/delete policies exist.
alter table "public"."org_employee_import_runs" enable row level security;

create policy "org_employee_import_runs_select"
on "public"."org_employee_import_runs"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "org_employee_import_runs_anon_deny"
on "public"."org_employee_import_runs"
as permissive
for all
to anon
using (false);

-- Grants
grant select on table "public"."org_employee_import_runs" to "authenticated";

grant delete on table "public"."org_employee_import_runs" to "postgres";
grant insert on table "public"."org_employee_import_runs" to "postgres";
grant references on table "public"."org_employee_import_runs" to "postgres";
grant select on table "public"."org_employee_import_runs" to "postgres";
grant trigger on table "public"."org_employee_import_runs" to "postgres";
grant truncate on table "public"."org_employee_import_runs" to "postgres";
grant update on table "public"."org_employee_import_runs" to "postgres";

grant delete on table "public"."org_employee_import_runs" to "service_role";
grant insert on table "public"."org_employee_import_runs" to "service_role";
grant references on table "public"."org_employee_import_runs" to "service_role";
grant select on table "public"."org_employee_import_runs" to "service_role";
grant trigger on table "public"."org_employee_import_runs" to "service_role";
grant truncate on table "public"."org_employee_import_runs" to "service_role";
grant update on table "public"."org_employee_import_runs" to "service_role";
