-- Exchange Agreement (EAPFS) fee schedule data (PSK-1920): exchanges,
-- fee_schedule_versions, fee_schedule_line_items, plus a private storage
-- bucket for the source PDFs.
--
-- Shared reference data, not org-scoped (mirrors the bloomberg_sid_*
-- tables' read-any-authenticated, write-via-service-role-only precedent) --
-- a fee schedule is the same for every org. Not linked to
-- contract_types.EAFeeSchedule; that type is for the unrelated
-- document-classification pipeline.
--
-- No insert/update/delete policies below: these tables are populated only
-- by scripts/seed-exchange-agreements.local.ts (and its future
-- non-local equivalent) via the service-role key, which bypasses RLS
-- entirely. There is no authenticated write path -- Postsig staff don't use
-- the client app to maintain this data -- so RLS's default-deny for
-- anything without a matching policy is exactly the intended behavior.

-- Restricts reads to orgs with the exchange-agreements module toggle on
-- (organization_modules.settings.exchange_agreements_enabled under the cpm
-- module) -- the same per-org admin toggle already used for CSV
-- export/MCP/invoices (set from the admin panel). Centralizes the check
-- instead of each select policy below inlining its own EXISTS subquery.
create or replace function "public"."has_exchange_agreements_access"()
returns boolean
language sql
stable
security invoker
set search_path to 'public', 'pg_temp'
as $$
    select exists (
        select 1
        from "public"."organization_modules" om
        join "public"."app_modules" am on am.id = om.module_id
        where om.organization_id = public.user_organization_id()
          and am.code = 'cpm'
          and coalesce((om.settings->>'exchange_agreements_enabled')::boolean, false)
    );
$$;

-- exchanges: lookup for the 4 exchanges the FE renders (only euronext has
-- versions/line items today; the rest use the FE's existing empty state).
create table "public"."exchanges" (
    "id" bigint generated by default as identity not null,
    "code" text not null,
    "name" text not null,
    "currency" text not null,
    "created_at" timestamptz not null default now()
);

CREATE UNIQUE INDEX "exchanges_pkey" ON "public"."exchanges" USING btree ("id");
alter table "public"."exchanges" add constraint "exchanges_pkey" PRIMARY KEY using index "exchanges_pkey";

alter table "public"."exchanges" add constraint "exchanges_code_unique" UNIQUE ("code");

comment on column "public"."exchanges"."currency" is 'Display symbol (e.g. €, £, $), not an ISO code — matches ExchangeSummary.currency in lib/exchange-agreement/types.ts.';

-- fee_schedule_versions: one row per vintage/release. version/effective_date/
-- invalidated_date/source_doc are release-wide in the source export --
-- constant across every product line and row in one vintage.
create table "public"."fee_schedule_versions" (
    "id" bigint generated by default as identity not null,
    "exchange_id" bigint not null,
    "vintage_slug" text not null,
    "version" text not null,
    "effective_date" date not null,
    "invalidated_date" date,
    "source_doc" text,
    "source_document_path" text,
    "created_at" timestamptz not null default now()
);

CREATE UNIQUE INDEX "fee_schedule_versions_pkey" ON "public"."fee_schedule_versions" USING btree ("id");
alter table "public"."fee_schedule_versions" add constraint "fee_schedule_versions_pkey" PRIMARY KEY using index "fee_schedule_versions_pkey";

comment on column "public"."fee_schedule_versions"."vintage_slug" is 'Export directory name, e.g. enx_emda_fee_schedule_01.07.2026_efd.';
comment on column "public"."fee_schedule_versions"."source_doc" is 'Original source PDF filename from the export. Populated even when the binary is not yet available.';
comment on column "public"."fee_schedule_versions"."source_document_path" is 'Storage object path in the exchange-fee-schedule-docs bucket once the PDF is uploaded. Null until then -- View Source stays disabled.';

-- Scoped to exchange, not bare-column-unique: the FE's logicalVersions()
-- merge-by-version-number depends on version numbers being unique per
-- exchange, not globally.
alter table "public"."fee_schedule_versions" add constraint "fee_schedule_versions_exchange_slug_unique" UNIQUE ("exchange_id", "vintage_slug");
alter table "public"."fee_schedule_versions" add constraint "fee_schedule_versions_exchange_version_unique" UNIQUE ("exchange_id", "version");

CREATE INDEX "idx_fee_schedule_versions_exchange_effective" ON "public"."fee_schedule_versions" USING btree ("exchange_id", "effective_date");

alter table "public"."fee_schedule_versions" add constraint "fee_schedule_versions_exchange_id_fkey" FOREIGN KEY ("exchange_id") REFERENCES "public"."exchanges"("id") not valid;
alter table "public"."fee_schedule_versions" validate constraint "fee_schedule_versions_exchange_id_fkey";

-- fee_schedule_line_items: the priced rows. No column (or combination) here
-- is a reliable per-row unique key in the source export, so the surrogate id
-- is the only per-row identity; re-seeding must delete-then-insert per
-- version_id (see replace_fee_schedule_line_items below), not upsert.
create table "public"."fee_schedule_line_items" (
    "id" bigint generated by default as identity not null,
    "version_id" bigint not null,

    "product_id" text not null,
    "price_point_id" text,
    "vintage_price_point_id" text,

    "title" text not null,
    "section_family" text,
    "section_path" text[],
    "row_label" text[],
    "column_labels" text[],

    "fee" numeric,
    "text_value" text,
    "currency" text,

    "use_type" text,
    "counterparty_role" text,
    "asset_class" text,
    "market" text,
    "venues" text,
    "level" text,
    "customer_tier" text,
    "user_class" text,
    "distribution_channel" text,
    "data_timeliness" text,
    "display_medium" text,
    "granularity" text,
    "user_count_tier" text,

    "product_code" text,
    "product_code_root" text,

    "fee_basis" text,
    "charge_subtype" text,
    "fee_basis_notes" text,
    "consolidated_pack" text,

    "page" int,
    "block_id" text,

    "created_at" timestamptz not null default now()
);

CREATE UNIQUE INDEX "fee_schedule_line_items_pkey" ON "public"."fee_schedule_line_items" USING btree ("id");
alter table "public"."fee_schedule_line_items" add constraint "fee_schedule_line_items_pkey" PRIMARY KEY using index "fee_schedule_line_items_pkey";

comment on column "public"."fee_schedule_line_items"."product_id" is 'Export cluster id -- stable across vintages for the same product, but NOT unique per row within one vintage (one product_id can span many distinct priced rows). Use for cross-version product tracking only, never as a per-row key.';
comment on column "public"."fee_schedule_line_items"."section_family" is 'The FE''s "product line". Blank on a large, inconsistent fraction of rows in the source export (25-45% per vintage) -- the seed script maps blanks to a placeholder value; see the EAPFS data implementation plan for the open question this represents.';
comment on column "public"."fee_schedule_line_items"."product_code" is 'Exchange Agreement Product Code (e.g. MAFFL2-TPLNDRUA). Future join key to vendor_products.product_code (see migration 20260803120000) for Service Order/Invoice matching -- not joined yet.';
comment on column "public"."fee_schedule_line_items"."page" is 'Page number in the source PDF -- provenance for deep-linking once source_document_path is populated.';

CREATE INDEX "idx_fee_schedule_line_items_version" ON "public"."fee_schedule_line_items" USING btree ("version_id");
CREATE INDEX "idx_fee_schedule_line_items_product" ON "public"."fee_schedule_line_items" USING btree ("product_id");
CREATE INDEX "idx_fee_schedule_line_items_product_code" ON "public"."fee_schedule_line_items" USING btree ("product_code") where "product_code" is not null;

alter table "public"."fee_schedule_line_items" add constraint "fee_schedule_line_items_version_id_fkey" FOREIGN KEY ("version_id") REFERENCES "public"."fee_schedule_versions"("id") ON DELETE CASCADE not valid;
alter table "public"."fee_schedule_line_items" validate constraint "fee_schedule_line_items_version_id_fkey";

-- Atomic delete+insert for one version: a client-side delete-then-N-inserts
-- isn't atomic, so a failure partway through re-seeding would leave a
-- version with partial line items indistinguishable from "never seeded".
create or replace function "public"."replace_fee_schedule_line_items"(
    p_version_id bigint,
    p_rows jsonb
)
returns void
language plpgsql
security invoker
set search_path to 'public', 'pg_temp'
as $$
begin
    delete from "public"."fee_schedule_line_items" where "version_id" = p_version_id;

    insert into "public"."fee_schedule_line_items" (
        "version_id", "product_id", "price_point_id", "vintage_price_point_id",
        "title", "section_family", "section_path", "row_label", "column_labels",
        "fee", "text_value", "currency",
        "use_type", "counterparty_role", "asset_class", "market", "venues", "level",
        "customer_tier", "user_class", "distribution_channel", "data_timeliness",
        "display_medium", "granularity", "user_count_tier",
        "product_code", "product_code_root",
        "fee_basis", "charge_subtype", "fee_basis_notes", "consolidated_pack",
        "page", "block_id"
    )
    select
        p_version_id, r.product_id, r.price_point_id, r.vintage_price_point_id,
        r.title, r.section_family, r.section_path, r.row_label, r.column_labels,
        r.fee, r.text_value, r.currency,
        r.use_type, r.counterparty_role, r.asset_class, r.market, r.venues, r.level,
        r.customer_tier, r.user_class, r.distribution_channel, r.data_timeliness,
        r.display_medium, r.granularity, r.user_count_tier,
        r.product_code, r.product_code_root,
        r.fee_basis, r.charge_subtype, r.fee_basis_notes, r.consolidated_pack,
        r.page, r.block_id
    from jsonb_to_recordset(p_rows) as r(
        product_id text, price_point_id text, vintage_price_point_id text,
        title text, section_family text, section_path text[], row_label text[], column_labels text[],
        fee numeric, text_value text, currency text,
        use_type text, counterparty_role text, asset_class text, market text, venues text, level text,
        customer_tier text, user_class text, distribution_channel text, data_timeliness text,
        display_medium text, granularity text, user_count_tier text,
        product_code text, product_code_root text,
        fee_basis text, charge_subtype text, fee_basis_notes text, consolidated_pack text,
        page int, block_id text
    );
end;
$$;

alter table "public"."exchanges" enable row level security;
alter table "public"."fee_schedule_versions" enable row level security;
alter table "public"."fee_schedule_line_items" enable row level security;

create policy "exchanges_anon_deny" on "public"."exchanges" for all to anon using (false);
create policy "exchanges_select" on "public"."exchanges" for select to authenticated using (has_exchange_agreements_access());
revoke all on "public"."exchanges" from anon;

create policy "fee_schedule_versions_anon_deny" on "public"."fee_schedule_versions" for all to anon using (false);
create policy "fee_schedule_versions_select" on "public"."fee_schedule_versions" for select to authenticated using (has_exchange_agreements_access());
revoke all on "public"."fee_schedule_versions" from anon;

create policy "fee_schedule_line_items_anon_deny" on "public"."fee_schedule_line_items" for all to anon using (false);
create policy "fee_schedule_line_items_select" on "public"."fee_schedule_line_items" for select to authenticated using (has_exchange_agreements_access());
revoke all on "public"."fee_schedule_line_items" from anon;

-- Private, service-role-write, shared-read bucket for source PDFs -- new
-- rather than reusing documents/contract_docs, since those are org-scoped
-- by folder path and this data is not.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'exchange-fee-schedule-docs',
    'exchange-fee-schedule-docs',
    false,
    52428800, -- 50MB
    array['application/pdf']
);

create policy "exchange_fee_schedule_docs_select" on storage.objects
    for select to authenticated
    using (bucket_id = 'exchange-fee-schedule-docs' and has_exchange_agreements_access());

create policy "exchange_fee_schedule_docs_anon_deny" on storage.objects
    for all to anon
    using (bucket_id = 'exchange-fee-schedule-docs' and false);
