-- =============================================================================
-- org_units: HR hierarchy tree built from the employee roster (PSK-1846)
-- =============================================================================

create table "public"."org_units" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "level" text not null,
    "name" text not null,
    "parent_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);

-- Primary key
CREATE UNIQUE INDEX org_units_pkey ON public.org_units USING btree (id);

alter table "public"."org_units" add constraint "org_units_pkey" PRIMARY KEY using index "org_units_pkey";

-- Composite-FK target so referencing rows pin tenancy (same pattern as
-- groups_org_id_unique / users_org_id_unique in folders_schema_5).
CREATE UNIQUE INDEX org_units_org_id_unique ON public.org_units USING btree (organization_id, id);

-- Identity is the path, not (level, name): the same name may repeat under
-- different parents. NULLS NOT DISTINCT makes roots (parent_id null) unique
-- too, which is what lets the upsert walk target this constraint.
alter table "public"."org_units" add constraint "org_units_path_unique" UNIQUE NULLS NOT DISTINCT (organization_id, parent_id, level, name);

-- Indexes
CREATE INDEX idx_org_units_org ON public.org_units USING btree (organization_id);
CREATE INDEX idx_org_units_parent ON public.org_units USING btree (parent_id);

-- Foreign keys
alter table "public"."org_units" add constraint "org_units_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."org_units" validate constraint "org_units_organization_id_fkey";

alter table "public"."org_units" add constraint "org_units_parent_fkey" FOREIGN KEY (organization_id, parent_id) REFERENCES public.org_units(organization_id, id) ON DELETE CASCADE not valid;
alter table "public"."org_units" validate constraint "org_units_parent_fkey";

-- Check constraints
alter table "public"."org_units" add constraint "org_units_level_check" CHECK (level IN ('entity', 'business_group', 'division', 'business_unit', 'department', 'team', 'cost_center'));

-- Cost centers are codes orthogonal to the org chart: always flat, never tree nodes.
alter table "public"."org_units" add constraint "org_units_cost_center_flat_check" CHECK (level <> 'cost_center' OR parent_id IS NULL);

-- RLS (mirrors org_employees: org members read; admins 11/12 write; role 12 deletes)
alter table "public"."org_units" enable row level security;

create policy "org_units_select"
on "public"."org_units"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "org_units_insert"
on "public"."org_units"
as permissive
for insert
to authenticated
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "org_units_update"
on "public"."org_units"
as permissive
for update
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))))
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "org_units_delete"
on "public"."org_units"
as permissive
for delete
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = 12))))));

create policy "org_units_anon_deny"
on "public"."org_units"
as permissive
for all
to anon
using (false);

-- Audit
CREATE TRIGGER audit_org_units_trigger AFTER INSERT OR DELETE OR UPDATE ON public.org_units FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();

-- Grants
grant delete on table "public"."org_units" to "authenticated";
grant insert on table "public"."org_units" to "authenticated";
grant references on table "public"."org_units" to "authenticated";
grant select on table "public"."org_units" to "authenticated";
grant trigger on table "public"."org_units" to "authenticated";
grant update on table "public"."org_units" to "authenticated";

grant delete on table "public"."org_units" to "postgres";
grant insert on table "public"."org_units" to "postgres";
grant references on table "public"."org_units" to "postgres";
grant select on table "public"."org_units" to "postgres";
grant trigger on table "public"."org_units" to "postgres";
grant truncate on table "public"."org_units" to "postgres";
grant update on table "public"."org_units" to "postgres";

grant delete on table "public"."org_units" to "service_role";
grant insert on table "public"."org_units" to "service_role";
grant references on table "public"."org_units" to "service_role";
grant select on table "public"."org_units" to "service_role";
grant trigger on table "public"."org_units" to "service_role";
grant truncate on table "public"."org_units" to "service_role";
grant update on table "public"."org_units" to "service_role";

-- =============================================================================
-- org_employees.org_unit_id: the employee's leaf node in the tree
-- =============================================================================

alter table "public"."org_employees" add column "org_unit_id" bigint;

alter table "public"."org_employees" add constraint "org_employees_org_unit_fkey" FOREIGN KEY (organization_id, org_unit_id) REFERENCES public.org_units(organization_id, id) not valid;
alter table "public"."org_employees" validate constraint "org_employees_org_unit_fkey";

CREATE INDEX idx_org_employees_org_unit ON public.org_employees USING btree (org_unit_id);
