-- Exchange Agreement (Euronext) support: a per-product code, plus the two new
-- contract types that carry it.
--
-- Euronext product descriptions differ only by market and level, so the fuzzy
-- name matcher that resolves an extracted product line to a vendor_products row
-- both mis-matches and forks duplicates. The Exchange Agreement Product Code
-- (e.g. MAFFL2-TPLNDRUA) is stable across every Euronext document -- Schedule of
-- Fees, Service Order, Invoice -- so it becomes the reliable join key.

ALTER TABLE "public"."vendor_products"
ADD COLUMN "product_code" text;

COMMENT ON COLUMN "public"."vendor_products"."product_code" IS 'Exchange Agreement Product Code (e.g. MAFFL2-TPLNDRUA). Stable identifier used to match product lines across Schedule of Fees, Service Order and Invoice documents.';

-- Partial so the many products with no code do not collide on NULL.
CREATE UNIQUE INDEX "vendor_products_vendor_id_product_code_key"
ON "public"."vendor_products" ("vendor_id", "product_code")
WHERE "product_code" IS NOT NULL;

-- The versions table mirrors vendor_products columns explicitly.
ALTER TABLE "public"."vendor_products_versions"
ADD COLUMN "product_code" text;

COMMENT ON COLUMN "public"."vendor_products_versions"."product_code" IS 'Snapshot of vendor_products.product_code at this version';

INSERT INTO "public"."contract_types" ("id", "name")
VALUES
  (12, 'Exchange Agreement Service Order'),
  (13, 'Exchange Agreement Invoice')
ON CONFLICT ("id") DO NOTHING;

-- The id column is `generated by default as identity`, so explicit inserts leave
-- the sequence behind and the next generated id would collide.
SELECT setval(
  pg_get_serial_sequence('public.contract_types', 'id'),
  (SELECT MAX("id") FROM "public"."contract_types")
);
