-- =============================================================================
-- Cost allocation tables (PSK-1846 phase 2): contract_cost_allocations,
-- contract_cost_allocation_lines, cost_allocation_budgets
-- =============================================================================

-- Composite-FK targets that do not exist yet (same pattern as
-- org_units_org_id_unique). contracts.id / org_employees.id are already PKs,
-- so these uniques cannot fail on existing data.
CREATE UNIQUE INDEX contracts_org_id_unique ON public.contracts USING btree (organization_id, id);
CREATE UNIQUE INDEX org_employees_org_id_unique ON public.org_employees USING btree (organization_id, id);

-- =============================================================================
-- contract_cost_allocations: one allocation per scope (whole contract, or one
-- row per product). mode 'active_users' stores no lines and resolves live.
-- =============================================================================

create table "public"."contract_cost_allocations" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "contract_id" bigint not null,
    "product_id" bigint,
    "mode" text not null,
    "created_by" uuid,
    "updated_by" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);

CREATE UNIQUE INDEX contract_cost_allocations_pkey ON public.contract_cost_allocations USING btree (id);

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_pkey" PRIMARY KEY using index "contract_cost_allocations_pkey";

-- Composite-FK target so the lines pin tenancy to their allocation.
CREATE UNIQUE INDEX contract_cost_allocations_org_id_unique ON public.contract_cost_allocations USING btree (organization_id, id);

-- One allocation per scope; NULLS NOT DISTINCT so two whole-contract rows
-- (product_id null) collide too.
alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_scope_unique" UNIQUE NULLS NOT DISTINCT (contract_id, product_id);

CREATE INDEX idx_contract_cost_allocations_org ON public.contract_cost_allocations USING btree (organization_id);
CREATE INDEX idx_contract_cost_allocations_contract ON public.contract_cost_allocations USING btree (contract_id);
CREATE INDEX idx_contract_cost_allocations_product ON public.contract_cost_allocations USING btree (product_id);

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."contract_cost_allocations" validate constraint "contract_cost_allocations_organization_id_fkey";

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_contract_fkey" FOREIGN KEY (organization_id, contract_id) REFERENCES public.contracts(organization_id, id) ON DELETE CASCADE not valid;
alter table "public"."contract_cost_allocations" validate constraint "contract_cost_allocations_contract_fkey";

-- vendor_products carries no organization_id (products are vendor-scoped), so
-- this is the one plain FK. vendor_products(id) is the grain contract_users.
-- product_id and the engine's contractId:productId key use;
-- vendor_products_details is per contract x product x year — the wrong grain.
alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_product_fkey" FOREIGN KEY (product_id) REFERENCES public.vendor_products(id) not valid;
alter table "public"."contract_cost_allocations" validate constraint "contract_cost_allocations_product_fkey";

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;
alter table "public"."contract_cost_allocations" validate constraint "contract_cost_allocations_created_by_fkey";

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;
alter table "public"."contract_cost_allocations" validate constraint "contract_cost_allocations_updated_by_fkey";

alter table "public"."contract_cost_allocations" add constraint "contract_cost_allocations_mode_check" CHECK (mode IN ('active_users', 'manual'));

-- =============================================================================
-- contract_cost_allocation_lines: percent per target, exclusive arc between
-- org_units and org_employees. Only percent is stored; amounts are derived.
-- =============================================================================

create table "public"."contract_cost_allocation_lines" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "allocation_id" bigint not null,
    "org_unit_id" bigint,
    "org_employee_id" bigint,
    "percent" numeric(7,4) not null
);

CREATE UNIQUE INDEX contract_cost_allocation_lines_pkey ON public.contract_cost_allocation_lines USING btree (id);

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_pkey" PRIMARY KEY using index "contract_cost_allocation_lines_pkey";

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_allocation_unit_unique" UNIQUE (allocation_id, org_unit_id);
alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_allocation_employee_unique" UNIQUE (allocation_id, org_employee_id);

CREATE INDEX idx_contract_cost_allocation_lines_org ON public.contract_cost_allocation_lines USING btree (organization_id);
CREATE INDEX idx_contract_cost_allocation_lines_allocation ON public.contract_cost_allocation_lines USING btree (allocation_id);
CREATE INDEX idx_contract_cost_allocation_lines_org_unit ON public.contract_cost_allocation_lines USING btree (org_unit_id);
CREATE INDEX idx_contract_cost_allocation_lines_org_employee ON public.contract_cost_allocation_lines USING btree (org_employee_id);

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."contract_cost_allocation_lines" validate constraint "contract_cost_allocation_lines_organization_id_fkey";

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_allocation_fkey" FOREIGN KEY (organization_id, allocation_id) REFERENCES public.contract_cost_allocations(organization_id, id) ON DELETE CASCADE not valid;
alter table "public"."contract_cost_allocation_lines" validate constraint "contract_cost_allocation_lines_allocation_fkey";

-- NO ACTION on purpose: org_units.parent_id cascades deletes (a node delete
-- takes its subtree), and that cascade must never propagate into financial
-- rows — a node with allocation lines simply cannot be dropped.
alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_org_unit_fkey" FOREIGN KEY (organization_id, org_unit_id) REFERENCES public.org_units(organization_id, id) not valid;
alter table "public"."contract_cost_allocation_lines" validate constraint "contract_cost_allocation_lines_org_unit_fkey";

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_org_employee_fkey" FOREIGN KEY (organization_id, org_employee_id) REFERENCES public.org_employees(organization_id, id) not valid;
alter table "public"."contract_cost_allocation_lines" validate constraint "contract_cost_allocation_lines_org_employee_fkey";

alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_percent_check" CHECK (percent > 0 AND percent <= 100);

-- Exclusive arc, same num_nonnulls pattern as inv_kpi_value.
alter table "public"."contract_cost_allocation_lines" add constraint "contract_cost_allocation_lines_target_check" CHECK (num_nonnulls(org_unit_id, org_employee_id) = 1);

-- =============================================================================
-- cost_allocation_budgets: per-target, per-fiscal-year amount in the org base
-- currency. No proration; a sub-year window compares against the whole FY.
-- =============================================================================

create table "public"."cost_allocation_budgets" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "org_unit_id" bigint,
    "org_employee_id" bigint,
    "fiscal_year" integer not null,
    "amount" numeric(14,2) not null,
    "created_by" uuid,
    "updated_by" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);

CREATE UNIQUE INDEX cost_allocation_budgets_pkey ON public.cost_allocation_budgets USING btree (id);

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_pkey" PRIMARY KEY using index "cost_allocation_budgets_pkey";

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_unit_fy_unique" UNIQUE (org_unit_id, fiscal_year);
alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_employee_fy_unique" UNIQUE (org_employee_id, fiscal_year);

CREATE INDEX idx_cost_allocation_budgets_org ON public.cost_allocation_budgets USING btree (organization_id);
CREATE INDEX idx_cost_allocation_budgets_org_unit ON public.cost_allocation_budgets USING btree (org_unit_id);
CREATE INDEX idx_cost_allocation_budgets_org_employee ON public.cost_allocation_budgets USING btree (org_employee_id);

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."cost_allocation_budgets" validate constraint "cost_allocation_budgets_organization_id_fkey";

-- NO ACTION for the same reason as the allocation lines: a node delete must
-- never cascade away financial rows.
alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_org_unit_fkey" FOREIGN KEY (organization_id, org_unit_id) REFERENCES public.org_units(organization_id, id) not valid;
alter table "public"."cost_allocation_budgets" validate constraint "cost_allocation_budgets_org_unit_fkey";

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_org_employee_fkey" FOREIGN KEY (organization_id, org_employee_id) REFERENCES public.org_employees(organization_id, id) not valid;
alter table "public"."cost_allocation_budgets" validate constraint "cost_allocation_budgets_org_employee_fkey";

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;
alter table "public"."cost_allocation_budgets" validate constraint "cost_allocation_budgets_created_by_fkey";

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL not valid;
alter table "public"."cost_allocation_budgets" validate constraint "cost_allocation_budgets_updated_by_fkey";

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_amount_check" CHECK (amount >= 0);

alter table "public"."cost_allocation_budgets" add constraint "cost_allocation_budgets_target_check" CHECK (num_nonnulls(org_unit_id, org_employee_id) = 1);

-- =============================================================================
-- RLS (mirrors org_employees: org members read; admins 11/12 write). Delete is
-- gated to 11/12 rather than org_employees' 12-only because replacing lines
-- and removing a scope are part of ordinary allocation editing.
-- =============================================================================

alter table "public"."contract_cost_allocations" enable row level security;

create policy "contract_cost_allocations_select"
on "public"."contract_cost_allocations"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "contract_cost_allocations_insert"
on "public"."contract_cost_allocations"
as permissive
for insert
to authenticated
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocations_update"
on "public"."contract_cost_allocations"
as permissive
for update
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))))
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocations_delete"
on "public"."contract_cost_allocations"
as permissive
for delete
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocations_anon_deny"
on "public"."contract_cost_allocations"
as permissive
for all
to anon
using (false);

alter table "public"."contract_cost_allocation_lines" enable row level security;

create policy "contract_cost_allocation_lines_select"
on "public"."contract_cost_allocation_lines"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "contract_cost_allocation_lines_insert"
on "public"."contract_cost_allocation_lines"
as permissive
for insert
to authenticated
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocation_lines_update"
on "public"."contract_cost_allocation_lines"
as permissive
for update
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))))
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocation_lines_delete"
on "public"."contract_cost_allocation_lines"
as permissive
for delete
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "contract_cost_allocation_lines_anon_deny"
on "public"."contract_cost_allocation_lines"
as permissive
for all
to anon
using (false);

alter table "public"."cost_allocation_budgets" enable row level security;

create policy "cost_allocation_budgets_select"
on "public"."cost_allocation_budgets"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "cost_allocation_budgets_insert"
on "public"."cost_allocation_budgets"
as permissive
for insert
to authenticated
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "cost_allocation_budgets_update"
on "public"."cost_allocation_budgets"
as permissive
for update
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))))
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "cost_allocation_budgets_delete"
on "public"."cost_allocation_budgets"
as permissive
for delete
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "cost_allocation_budgets_anon_deny"
on "public"."cost_allocation_budgets"
as permissive
for all
to anon
using (false);

-- Audit
CREATE TRIGGER audit_contract_cost_allocations_trigger AFTER INSERT OR DELETE OR UPDATE ON public.contract_cost_allocations FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();
CREATE TRIGGER audit_contract_cost_allocation_lines_trigger AFTER INSERT OR DELETE OR UPDATE ON public.contract_cost_allocation_lines FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();
CREATE TRIGGER audit_cost_allocation_budgets_trigger AFTER INSERT OR DELETE OR UPDATE ON public.cost_allocation_budgets FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();

-- Grants
grant delete on table "public"."contract_cost_allocations" to "authenticated";
grant insert on table "public"."contract_cost_allocations" to "authenticated";
grant references on table "public"."contract_cost_allocations" to "authenticated";
grant select on table "public"."contract_cost_allocations" to "authenticated";
grant trigger on table "public"."contract_cost_allocations" to "authenticated";
grant update on table "public"."contract_cost_allocations" to "authenticated";

grant delete on table "public"."contract_cost_allocations" to "postgres";
grant insert on table "public"."contract_cost_allocations" to "postgres";
grant references on table "public"."contract_cost_allocations" to "postgres";
grant select on table "public"."contract_cost_allocations" to "postgres";
grant trigger on table "public"."contract_cost_allocations" to "postgres";
grant truncate on table "public"."contract_cost_allocations" to "postgres";
grant update on table "public"."contract_cost_allocations" to "postgres";

grant delete on table "public"."contract_cost_allocations" to "service_role";
grant insert on table "public"."contract_cost_allocations" to "service_role";
grant references on table "public"."contract_cost_allocations" to "service_role";
grant select on table "public"."contract_cost_allocations" to "service_role";
grant trigger on table "public"."contract_cost_allocations" to "service_role";
grant truncate on table "public"."contract_cost_allocations" to "service_role";
grant update on table "public"."contract_cost_allocations" to "service_role";

grant delete on table "public"."contract_cost_allocation_lines" to "authenticated";
grant insert on table "public"."contract_cost_allocation_lines" to "authenticated";
grant references on table "public"."contract_cost_allocation_lines" to "authenticated";
grant select on table "public"."contract_cost_allocation_lines" to "authenticated";
grant trigger on table "public"."contract_cost_allocation_lines" to "authenticated";
grant update on table "public"."contract_cost_allocation_lines" to "authenticated";

grant delete on table "public"."contract_cost_allocation_lines" to "postgres";
grant insert on table "public"."contract_cost_allocation_lines" to "postgres";
grant references on table "public"."contract_cost_allocation_lines" to "postgres";
grant select on table "public"."contract_cost_allocation_lines" to "postgres";
grant trigger on table "public"."contract_cost_allocation_lines" to "postgres";
grant truncate on table "public"."contract_cost_allocation_lines" to "postgres";
grant update on table "public"."contract_cost_allocation_lines" to "postgres";

grant delete on table "public"."contract_cost_allocation_lines" to "service_role";
grant insert on table "public"."contract_cost_allocation_lines" to "service_role";
grant references on table "public"."contract_cost_allocation_lines" to "service_role";
grant select on table "public"."contract_cost_allocation_lines" to "service_role";
grant trigger on table "public"."contract_cost_allocation_lines" to "service_role";
grant truncate on table "public"."contract_cost_allocation_lines" to "service_role";
grant update on table "public"."contract_cost_allocation_lines" to "service_role";

grant delete on table "public"."cost_allocation_budgets" to "authenticated";
grant insert on table "public"."cost_allocation_budgets" to "authenticated";
grant references on table "public"."cost_allocation_budgets" to "authenticated";
grant select on table "public"."cost_allocation_budgets" to "authenticated";
grant trigger on table "public"."cost_allocation_budgets" to "authenticated";
grant update on table "public"."cost_allocation_budgets" to "authenticated";

grant delete on table "public"."cost_allocation_budgets" to "postgres";
grant insert on table "public"."cost_allocation_budgets" to "postgres";
grant references on table "public"."cost_allocation_budgets" to "postgres";
grant select on table "public"."cost_allocation_budgets" to "postgres";
grant trigger on table "public"."cost_allocation_budgets" to "postgres";
grant truncate on table "public"."cost_allocation_budgets" to "postgres";
grant update on table "public"."cost_allocation_budgets" to "postgres";

grant delete on table "public"."cost_allocation_budgets" to "service_role";
grant insert on table "public"."cost_allocation_budgets" to "service_role";
grant references on table "public"."cost_allocation_budgets" to "service_role";
grant select on table "public"."cost_allocation_budgets" to "service_role";
grant trigger on table "public"."cost_allocation_budgets" to "service_role";
grant truncate on table "public"."cost_allocation_budgets" to "service_role";
grant update on table "public"."cost_allocation_budgets" to "service_role";
