-- =============================================================================
-- org_employees: Organization-level employee directory
-- =============================================================================

-- Table
create table "public"."org_employees" (
    "id" bigint generated by default as identity not null,
    "organization_id" uuid not null,
    "first_name" text not null,
    "last_name" text not null,
    "email" text,
    "employee_id" text,
    "region" text,
    "country" text,
    "division" text,
    "department" text,
    "cost_center" text,
    "group_id" bigint,
    "start_date" date,
    "leave_date" date,
    "status" text not null default 'active',
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone
);

-- Primary key
CREATE UNIQUE INDEX org_employees_pkey ON public.org_employees USING btree (id);

alter table "public"."org_employees" add constraint "org_employees_pkey" PRIMARY KEY using index "org_employees_pkey";

-- Unique constraint: one email per organization (only when email is not null)
CREATE UNIQUE INDEX org_employees_org_email_unique ON public.org_employees USING btree (organization_id, lower(email)) WHERE email IS NOT NULL;

-- Indexes
CREATE INDEX idx_org_employees_org ON public.org_employees USING btree (organization_id);
CREATE INDEX idx_org_employees_email ON public.org_employees USING btree (email);
CREATE INDEX idx_org_employees_status ON public.org_employees USING btree (organization_id, status);
CREATE INDEX idx_org_employees_group ON public.org_employees USING btree (group_id);

-- Foreign keys
alter table "public"."org_employees" add constraint "org_employees_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE not valid;
alter table "public"."org_employees" validate constraint "org_employees_organization_id_fkey";

alter table "public"."org_employees" add constraint "org_employees_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE SET NULL not valid;
alter table "public"."org_employees" validate constraint "org_employees_group_id_fkey";

-- Check constraint on status
alter table "public"."org_employees" add constraint "org_employees_status_check" CHECK (status IN ('active', 'inactive', 'on_leave'));

-- RLS
alter table "public"."org_employees" enable row level security;

create policy "org_employees_select"
on "public"."org_employees"
as permissive
for select
to authenticated
using ((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))));

create policy "org_employees_insert"
on "public"."org_employees"
as permissive
for insert
to authenticated
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "org_employees_update"
on "public"."org_employees"
as permissive
for update
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))))
with check (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = ANY (ARRAY[11, 12])))))));

create policy "org_employees_delete"
on "public"."org_employees"
as permissive
for delete
to authenticated
using (((organization_id IN ( SELECT u.organization_id
   FROM users u
  WHERE (u.id = auth.uid()))) AND (EXISTS ( SELECT 1
   FROM user_roles2 ur
  WHERE ((ur.user_id = auth.uid()) AND (ur.role_id = 12))))));

create policy "org_employees_anon_deny"
on "public"."org_employees"
as permissive
for all
to anon
using (false);

-- Audit
CREATE TRIGGER audit_org_employees_trigger AFTER INSERT OR DELETE OR UPDATE ON public.org_employees FOR EACH ROW EXECUTE FUNCTION audit_trigger_function();

-- Grants
grant delete on table "public"."org_employees" to "authenticated";
grant insert on table "public"."org_employees" to "authenticated";
grant references on table "public"."org_employees" to "authenticated";
grant select on table "public"."org_employees" to "authenticated";
grant trigger on table "public"."org_employees" to "authenticated";
grant update on table "public"."org_employees" to "authenticated";

grant delete on table "public"."org_employees" to "postgres";
grant insert on table "public"."org_employees" to "postgres";
grant references on table "public"."org_employees" to "postgres";
grant select on table "public"."org_employees" to "postgres";
grant trigger on table "public"."org_employees" to "postgres";
grant truncate on table "public"."org_employees" to "postgres";
grant update on table "public"."org_employees" to "postgres";

grant delete on table "public"."org_employees" to "service_role";
grant insert on table "public"."org_employees" to "service_role";
grant references on table "public"."org_employees" to "service_role";
grant select on table "public"."org_employees" to "service_role";
grant trigger on table "public"."org_employees" to "service_role";
grant truncate on table "public"."org_employees" to "service_role";
grant update on table "public"."org_employees" to "service_role";

-- =============================================================================
-- Add org_employee_id FK to contract_users
-- =============================================================================

alter table "public"."contract_users" add column "org_employee_id" bigint;

alter table "public"."contract_users" add constraint "contract_users_org_employee_id_fkey" FOREIGN KEY (org_employee_id) REFERENCES public.org_employees(id) ON DELETE SET NULL not valid;
alter table "public"."contract_users" validate constraint "contract_users_org_employee_id_fkey";

CREATE INDEX idx_contract_users_org_employee ON public.contract_users USING btree (org_employee_id);
